nextcloud/calendar

- README.md
@georgehrke can you add more of the readme related changes here? The correct URIs for Travis and Scrutinizer and such stuff. ;)
> Update ReadME to NextCloud links

- css/app/globals.css
> Styles input left button right element.

- js/package.json
Was tired of seeing this warning when npm installs
> update phantomjs name

- js/app/controllers/calendarlistcontroller.js
- js/app/controllers/subscriptioncontroller.js
- templates/part.createsubscription.php
Fixes https://github.com/nextcloud/calendar/issues/58
> fix webcal input field not clearing & clean subscription controller

- js/app/controllers/editorcontroller.js
- js/app/service/eventseditordialogservice.js
Fixes https://github.com/nextcloud/calendar/issues/65
> Fix update button appearing everytime

- templates/part.datepicker.php
fixes https://github.com/nextcloud/calendar/issues/48
please review @raghunayyar @tcitworld
> fix datepicker in app-navigation

- css/app/calendarlist.css
- templates/main.php
possible fix for https://github.com/nextcloud/calendar/issues/68
please review @raghunayyar @tcitworld
> fix scrollability of calendar-list

- templates/part.settings.php
please review @raghunayyar @tcitworld
> use fancy checkbox styles from core

- .travis.yml
I put the credentials into the travis-ci settings.
Will work if merged :smile: 
https://travis-ci.org/nextcloud/calendar/builds/161913182
> Add nigthly creation in travis

- .travis.yml
Adds the date to the nightlies. This will build up a little archive.
> Add date to nightly

- js/app/controllers/calcontroller.js
Guess someone has forgotten about him.
> Remove console.log() call

- js/app/controllers/importcontroller.js
> fix import by changing random color call

- README.md
Had to search in packages.json and then bower.json and I think we could save someone the time.
> Added a reference to fullcalendar in the README

- l10n/.tx/config
> Update transifex project

- js/bower.json
please review @jancborchardt @tcitworld
> update angular-bootstrap to 2.2.0

- css/app/calendarlist.css
- templates/main.php
- templates/part.datepicker.php
Fixes: https://github.com/nextcloud/calendar/issues/85
This is an urgent fix, lets get this in asap @georgehrke @nextcloud/calendar
> Fix for overlapping datepicker.

- README.md
please review @tcitworld @jancborchardt @MariusBluem
> add note to not use root or sudo

- templates/editor.popover.php
- templates/editor.sidebar.php
- templates/part.calendarlist.item.php
Please review @georgehrke @raghunayyar
> Use new checkbox styles for shares

- js/app/models/simpleEventModel.js
- tests/js/unit/models/simpleEventModelSpec.js
fixes https://github.com/nextcloud/calendar/issues/35
> make it possible to create events in UTC

- controller/viewcontroller.php
> remove some usages of OC ns

- appinfo/application.php
- controller/proxycontroller.php
- js/app/controllers/calendarlistcontroller.js
- js/app/service/webcalService.js
- js/app/utility/webcalUtility.js
- tests/js/unit/services/webcalServiceSpec.js
- tests/js/unit/utility/webcalUtilitySpec.js
- tests/php/controller/proxycontrollerTest.php
> catch more GuzzleHttp exceptions

- js/app/models/veventModel.js
- tests/js/unit/models/veventModelSpec.js
fixes #145 
please review @raghunayyar @tcitworld @raimund-schluessler
> fix expanding of repeating events on fdow

- js/app/controllers/calcontroller.js
don't save new view in publicMode, because the request will fail anyway
please review @tcitworld @raghunayyar @MariusBluem
> don't save new view in publicMode

- js/app/models/veventModel.js
- tests/js/unit/models/veventModelSpec.js
downstream patch
fixes #189 
please review @kukukk @tcitworld @MariusBluem
> Sanitize malformed dates

- js/app/service/calendarService.js
> fix bug introduced by refactoring

- controller/settingscontroller.php
- controller/viewcontroller.php
- js/app/controllers/settingscontroller.js
- js/app/service/settingsservice.js
- templates/part.fullcalendar.php
- templates/part.settings.php
- tests/js/unit/services/settingsServiceSpec.js
- tests/php/controller/settingscontrollerTest.php
- tests/php/controller/viewcontrollerTest.php
fix #19 
please review @eppfel @tcitworld @jancborchardt 
to test this delete the 'currentView' row from oc_preferences.
To test it again delete both the 'currentView' and 'firstRun' row.
> Show import button on first run

- README.md
- appinfo/info.xml
fixes https://github.com/nextcloud/calendar/issues/67
> Version 1.4.1

- js/app/controllers/editorcontroller.js
- templates/editor.popover.php
- templates/editor.sidebar.php
> enable calendar when selecting it in editor

- js/app/controllers/calendarlistcontroller.js
- js/app/models/calendarListItemModel.js
- js/app/service/calendarService.js
- js/config/config.js
- templates/part.calendarlist.item.php
- tests/js/unit/controllers/calendarlistcontrollerSpec.js
- tests/js/unit/models/calendarListItemModelSpec.js
> require sharingAPI to create new shares

- js/app/controllers/calcontroller.js
- js/app/service/eventseditordialogservice.js
- tests/js/unit/services/eventsEditorDialogServiceSpec.js
> fixing event title in grid changing back when editing twice

- js/app/controllers/attendeecontroller.js
- js/app/models/simpleEventModel.js
- tests/js/unit/models/simpleEventModelSpec.js
> fix sending the RSVP parameter for attendees

- css/app/calendarlist.css
- templates/part.calendarlist.item.php
please review @nextcloud/calendar 
fixes #99
> fix styling issue with too long group names / too long translations

- templates/part.settings.php
Remember we only capitalize the first word @nextcloud/calendar ;)
> fix capitalization of Settings & import

- css/app/calendarlist.css
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
> Fix icon share padding

- css/app/eventdialog.css
- templates/editor.sidebar.php
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
@jancborchardt
> Fix glitchy looking whitespace in event details

- controller/viewcontroller.php
- js/app/controllers/datepickercontroller.js
- js/app/controllers/settingscontroller.js
- js/app/directives/fullCalendarDirective.js
- js/app/factory/calendarFactory.js
- js/app/factory/icalFactory.js
- js/app/service/calendarService.js
- js/app/service/eventseditordialogservice.js
- js/config/config.js
- templates/part.fullcalendar.php
- tests/js/unit/controllers/calendarlistcontrollerSpec.js
- tests/js/unit/factory/calendarFactorySpec.js
- tests/js/unit/factory/icalFactorySpec.js
- tests/js/unit/models/calendarListItemModelSpec.js
- tests/js/unit/models/calendarModelSpec.js
- tests/js/unit/services/calendarServiceSpec.js
- tests/js/unit/services/eventsEditorDialogServiceSpec.js
- tests/php/controller/viewcontrollerTest.php
> use proper constants

- controller/proxycontroller.php
- js/app/controllers/calendarlistcontroller.js
- js/app/models/webcalModel.js
- js/app/service/calendarService.js
- js/app/service/webcalService.js
- tests/php/controller/proxycontrollerTest.php
> save 301 responses from webcal subscriptions

- js/app/controllers/calcontroller.js
- js/app/models/calendarmodel.js
- js/app/models/veventModel.js
- js/app/models/webcalModel.js
- tests/js/unit/models/veventModelSpec.js
> lazy load timezones when rendering events

- css/app/print.css
Hides the sidebar on print view.
We also could consider bundling https://github.com/fullcalendar/fullcalendar/blob/master/src/common/print.css
> hide sidepanel on print view

- js/app/controllers/calcontroller.js
- js/app/controllers/calendarlistcontroller.js
- js/app/service/hashService.js
- js/config/run.js
- tests/js/unit/services/hashServiceSpec.js
~~tests don't pass locally, no clue why 😕~~
Jasmine does weird stuff sometimes
fixes #41
> add web protocol handler for webcal

- js/app/models/webcalModel.js
> fix visual deletion of webcal

- js/app/directives/datetimepickerDirective.js
- templates/editor.popover.php
- templates/editor.sidebar.php
please review @ccoenen @eppfel 
fixes #25
> better tabindex for event editors

- js/app/controllers/calendarlistcontroller.js
- js/app/service/calendarService.js
- js/config/config.js
- tests/js/unit/controllers/calendarlistcontrollerSpec.js
OC.Share is obviously not defined when sharing API is disabled
> fix unsharing/editing shares when sharing API is disabled

- js/app/directives/datetimepickerDirective.js
- templates/editor.popover.php
- templates/editor.sidebar.php
> don't toggle allday when clicking on disabled time field when editor in readonly mode

- js/.jshintrc
- js/app/directives/fullCalendarDirective.js
fixes #23 
please review @nextcloud/calendar 
We can just use underscore's debound function. It's part of Nextcloud 9, 10 and 11
> debounce vertical window resizing

- templates/part.calendarlist.item.php
- templates/part.createsubscription.php
- templates/part.publicinformations.php
Fix https://github.com/nextcloud/calendar/issues/233, please review @nextcloud/calendar
> change WebDAV to iCal wording, fix #233

- templates/part.publicinformations.php
fix wording
please review @nextcloud/calendar @jancborchardt
> fix wording settings -> Subscribe & embed

- css/app/datepicker.css
fixes #315 
please review @tcitworld @nextcloud/calendar
> fix arrows for datepicker

- css/app/confirmation.css
- js/app/directives/confirmationDirective.js
- templates/main.php
- templates/part.calendarlist.item.php
fixes #341 
please review @tcitworld @raimund-schluessler
> add second step for calendar deletion as a temporary solution

- CHANGELOG.md
- README.md
- appinfo/info.xml
> Increment version number 1.5.1

- appinfo/application.php
please review @bastoGrande @tcitworld @nextcloud/calendar 
fixes #368
> use closure for adding navigation entry

- CHANGELOG.md
- appinfo/info.xml
> release 1.5.2

- js/app/service/calendarService.js
fixes #378 
please review @tcitworld
> fix visual deletion when unsharing a calendar with a user

- js/app/controllers/editorcontroller.js
- js/app/models/simpleEventModel.js
- tests/js/unit/models/simpleEventModelSpec.js
> make sure user can not set dtend to something earlier than dtstart

- appinfo/info.xml
Signed-off-by: Marius Blüm <marius@lineone.io>
> Optimize info.xml for App Store

- js/bower.json
cf https://github.com/angular/angular.js/blob/master/CHANGELOG.md#163-scriptalicious-bootstrapping-2017-03-08
> Update Angular to 1.6.3

- js/bower.json
Stumbled on this during `make`, please review @nextcloud/calendar  :)
> add angular version resolution to bower.json

- js/gulpfile.js
- tests/js/config/karma.js
previously the source maps pointed to themselves ...
> fix source maps

- issue_template.md
Signed-off-by: Marius Blüm <marius@lineone.io>
> it’s nextcloud.log

- js/app/controllers/calendarlistcontroller.js
> don't use webcal names longer than 100 characters

- js/.bowerrc
- js/bower.json
- js/package.json
- js/yarn.lock
- fixes #264 (via https://github.com/fullcalendar/fullcalendar/pull/3600)
- removes mercurial dependency
> Ditch bower hg

- css/app/calendar.css
> color weekends slightly darker

- controller/viewcontroller.php
- js/app/factory/calendarFactory.js
- js/config/config.js
- templates/part.fullcalendar.php
- tests/js/unit/factory/calendarFactorySpec.js
- tests/php/controller/viewcontrollerTest.php
> allow editing props of shared calendars and disallow editing shares for sharee

- js/app/controllers/editorcontroller.js
- js/app/directives/datetimepickerDirective.js
- templates/editor.popover.php
- templates/editor.sidebar.php
> set ending time one hour later also when clicking on disabled time input (in order to disable allDay)

- appinfo/info.xml
According to @jancborchardt's feedback on https://github.com/nextcloud/contacts/pull/177 😉 
@georgehrke
Signed-off-by: Marius Blüm <marius@lineone.io>
> Fix summary + description

- js/app/models/calendarmodel.js
> properly display errors when querying events

- css/app/settings.css
> fix visibility of import progress bar

- js/app/models/veventModel.js
- tests/js/unit/models/veventModelSpec.js
> sanitize missing VALUE=DATE

- js/app/factory/calendarFactory.js
- js/app/service/calendarService.js
- tests/js/unit/factory/calendarFactorySpec.js
- tests/js/unit/services/calendarServiceSpec.js
make use of https://github.com/nextcloud/server/pull/4401
> use owner-displayname if available

- .travis.yml
- appinfo/info.xml
- controller/viewcontroller.php
- js/app/service/calendarService.js
- js/bower.json
- js/config/config.js
- templates/editor.sidebar.php
- templates/main-asset-pipeline-unsupported.php
- templates/main.php
- templates/part.fullcalendar.php
- tests/js/unit/services/calendarServiceSpec.js
- tests/php/controller/viewcontrollerTest.php
fixes https://github.com/nextcloud/calendar/issues/433
> remove Nextcloud 9 and 10 legacy code

- css/app/calendarlist.css
- css/app/datepicker.css
- templates/part.buttonarea.php
- templates/part.datepicker.php
> Flex on app-navigation buttons

- appinfo/routes.php
- controller/viewcontroller.php
- js/app/models/calendarListItemModel.js
- tests/js/unit/models/calendarListItemModelSpec.js
fixes #239 
This will create links like `http://nextcloud.dev/index.php/apps/calendar/p/WX9UN5XVXXHZE444/Geburtstage-von-Freunden`
> make public sharing links readable

- Makefile
- js/gulpfile.js
> fix nightly builds

- templates/public.php
See https://github.com/nextcloud/server/pull/5959
> Logo claim is not used anymore

- templates/part.eventsattendees.php
This fixes the typical look of the DOM checkbox with the design of NC (flat and blue background).
> Fix checkbox styling

- controller/emailcontroller.php
Required due to https://github.com/nextcloud/server/pull/6366
@georgehrke can you release this before 12.0.3 gets out please?
> Update email usage

- Makefile
> make sure not to include .DS_STORE in appstore bundles

- Makefile
> remove occ signature from makefile

- CHANGELOG.md
- appinfo/info.xml
> Release 1.5.6

- js/app/filters/datepickerfilter.js
> fix display of year in upper left corner for certain cases

- js/app/controllers/importcontroller.js
- js/app/filters/importerrorfilter.js
- js/app/models/ImportFileWrapperModel.js
- js/app/service/veventService.js
- tests/js/unit/filters/importErrorFilterSpec.js
- tests/js/unit/services/veventServiceSpec.js
> add special treatment for duplicate errors when importing calendars

- js/app/filters/reminderfilter.js
- tests/js/unit/filters/reminderFilterSpec.js
supersedes #659 
@tcitworld Can you verify that this works with french locale? 
Then i will go ahead and fix the unit tests
> fix escaping of alarm type names

- js/app/controllers/valarmcontroller.js
- templates/part.eventsalarms.php
because they are not implemented in the CalDAV server yet
> show warning when a user has email reminders

- js/app/factory/calendarFactory.js
- tests/js/unit/factory/calendarFactorySpec.js
> fix displayname on public sharing site

- templates/editor.popover.php
- templates/editor.sidebar.php
> fix submit buttons in event editor, broken by #669

- appinfo/info.xml
adjusts order of elements to https://apps.nextcloud.com/schema/apps/info.xsd
> fix order of elements in info.xml

- js/app/models/simpleEventModel.js
- js/app/models/veventModel.js
- tests/js/unit/models/simpleEventModelSpec.js
- tests/js/unit/models/veventModelSpec.js
> fix parsing all-day events with DTSTART only

- js/app/controllers/importcontroller.js
- js/app/models/ImportFileWrapperModel.js
- templates/part.import.dialog.php
- tests/data/garbage.ics
> add better error handling for importing calendars

- js/app/models/veventModel.js
- tests/js/unit/models/veventModelSpec.js
> fix handling of events with recurrence exceptions only

- CHANGELOG.md
- appinfo/info.xml
> release 1.6.1

- CHANGELOG.md
- appinfo/info.xml
> release 1.5.8

- js/app/controllers/editorcontroller.js
> Add name when using contacts for location

- css/app/calendar.scss
- css/app/eventdialog.scss
- templates/part.calendarlist.item.php
Mostly use CSS4 variables instead of SASS ones.
Closes https://github.com/nextcloud/calendar/issues/938
> Fix dark theme

- css/app/datepicker.scss
> Fix position of New Calendar button in IE11

- appinfo/info.xml
Just a tiny one, so this link does not need to be touched anymore.
Signed-off-by: Micha Felle <micha@dietpi.com>
> Update documentation link to "latest" docs version

- src/components/Editor/Timezonepicker.vue
- src/components/Editor/TitleTimepicker.vue
- src/main.js
- src/views/EditSidebar.vue
> show sidebar values

- .travis.yml
- appinfo/info.xml
Signed-off-by: Julius Härtl <jus@bitgrid.net>
> Fix travis database tests

- controller/proxycontroller.php
> Improve url filter in ProxyController, less false positives

- js/gulpfile.js
- templates/main.php
> Don't ship special build with babel for IE anymore

- css/app/calendarlist.scss
- css/app/datepicker.scss
> Fix SCSS linting

- CHANGELOG.md
- appinfo/info.xml
> Version 1.7.1

- appinfo/routes.php
- lib/Controller/ContactController.php
Signed-off-by: Jakob <jakob.roehrl@web.de>
> api for getting a avatar photo

- src/views/Calendar.vue
> Calendar should not be selectable in Embedded mode

- src/components/Editor/IllustrationHeader.vue
> Add a transition fade effect when illustration header pic changes

- .github/no-response.yml
> Add config for no-response bot

- css/app-sidebar.scss
- package-lock.json
- src/components/Editor/Repeat/Repeat.vue
- src/components/Editor/Repeat/RepeatSummary.vue
- src/components/Editor/Repeat/RepeatSummaryReadOnly.vue
This implements a repeat summary and based on that a read-only view for the repeat tab.
> Repeat summary

- css/app-sidebar.scss
> Move end datepicker in second line if window's width too small

- src/views/EditSimple.vue
Current route name is obviously not the sidebar one, but the popover one.
> Fix clicking more button in New event popover

- css/app-sidebar.scss
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
- src/components/Editor/Invitees/OrganizerNoEmailError.vue
> Show error message when user has no email configured

- src/views/EditSidebar.vue
- src/views/EditSimple.vue
> Hide editor buttons when saving is already in progress

- Makefile
https://github.com/nextcloud/calendar/issues/1020#issuecomment-544427084
> Delete the entire js folder on make clean to get rid of old v1 code

- src/utils/illustration.js
> Find illustrations based on category if no illustration is matching title

- src/views/Calendar.vue
> Update Today in calendar-grid

- css/global.scss
- src/views/Calendar.vue
> Show warning if detected timezone is UTC

- src/fullcalendar/select.js
- src/views/Calendar.vue
Same as https://github.com/nextcloud/calendar/pull/1543, just for new event
> Also open new event in sidebar if window too narrow

- src/store/calendarObjectInstance.js
> Default time to 10am to 11am when changing from allDay to timed

- src/components/Editor/Properties/PropertyTitle.vue
- src/views/EditSidebar.vue
> Rename Untitled event in editor to Event title

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/views/EditSidebar.vue
> Put text inside ActionLink component to prevent weird formatting

- css/fullcalendar.scss
- src/views/Calendar.vue
fixes #1571
Dark Mode:
Normal Mode:
I really love our new CSS vars. It's so easy to use ❤
> Show week number inside calendar-grid in month view

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
- src/components/Editor/Alarm/AlarmListItem.vue
- src/components/Editor/Properties/PropertyTitleTimePicker.vue
- src/components/Editor/Repeat/RepeatEndRepeat.vue
- src/components/Shared/DatePicker.vue
- src/components/Shared/TimePicker.vue
- src/utils/moment.js
Fixes #920 
On top of that, it makes sure that all date pickers we use are properly localised.
> Fix locale / language bug

- src/components/Editor/Properties/PropertySelect.vue
> PropertySelect: emit the value, not the entire object

- src/mixins/PropertyMixin.js
> Hide property info in read-only mode

- src/components/Editor/Properties/PropertyTitleTimePicker.vue
> Do not show [ ] All day checkbox in read-only mode

- src/models/calendar.js
- src/models/principal.js
- src/models/rfcProps.js
- src/store/calendars.js
- src/utils/color.js
- src/views/EditSidebar.vue
- tests/javascript/unit/models/calendar.test.js
- tests/javascript/unit/models/rfcProps.test.js
- tests/javascript/unit/utils/color.test.js
fixed #1588 
Cleans up calendar model and adds tests
> Cleanup of calendar model, show calendar by default if owned by user

- src/components/Editor/IllustrationHeader.vue
> Remove titles from illustration svgs

- package-lock.json
- src/models/calendar.js
- src/store/calendars.js
- tests/javascript/unit/models/calendar.test.js
> Add timezone at creation of calendar

- src/defaults/defaultCategories.js
- tests/javascript/unit/defaults/defaultAlarmProvider.test.js
- tests/javascript/unit/defaults/defaultCategories.test.js
> Add unit tests for default alarms and default categories

- css/app-sidebar.scss
- src/views/EditSimple.vue
> Move Show More button to upper right corner of popover

- src/mixins/EditorMixin.js
- src/store/calendarObjectInstance.js
- src/store/calendars.js
> Store calendar object instance in vue, allow to transfer data from popover to sidebar

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release 2.0.0 beta2

- css/app-sidebar.scss
> Disable textbox resize, since we use autosize

- src/components/Editor/Properties/PropertyText.vue
- src/models/rfcProps.js
- tests/javascript/unit/models/rfcProps.test.js
> Give description field a default height of 2 rows

- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
> Hide calendar-picker if user has only one writable calendar

- src/components/Editor/Repeat/RepeatSummary.vue
> Do not show recurrence summary when repeat is set to NONE

- src/components/Editor/Alarm/NoAlarmView.vue
- src/components/Editor/Invitees/NoInviteesView.vue
- src/components/Editor/Invitees/OrganizerNoEmailError.vue
> Minor wording changes as per #1576

- package-lock.json
- src/components/Shared/DatePicker.vue
- src/filters/alarmFormat.js
- src/filters/dateRangeFormat.js
- src/fullcalendar/eventSourceFunction.js
- src/store/calendars.js
- src/utils/illustration.js
- src/utils/timezone.js
> fix all translation reporting

- src/services/timezoneDataProviderService.js
> ReAdd TZID to VTIMEZONE blocks

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/SettingsImportSection.vue
- src/components/Editor/IllustrationHeader.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
- src/fullcalendar/eventDrop.js
- src/fullcalendar/eventResize.js
- src/fullcalendar/eventSource.js
- src/mixins/EditorMixin.js
- src/store/calendars.js
- src/store/settings.js
- src/views/Calendar.vue
> Promise to async/await

- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/Settings/ImportScreen.vue
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>
> l10n: Triple dot to ellipsis

- appinfo/app.php
- appinfo/routes.php
- lib/AppInfo/Application.php
- lib/Controller/ContactController.php
- lib/Controller/EmailController.php
- lib/Controller/PublicViewController.php
- lib/Controller/SettingsController.php
- lib/Controller/ViewController.php
- lib/RepairSteps/CurrentViewNameRepairStep.php
- tests/php/unit/Controller/ContactControllerTest.php
- tests/php/unit/Controller/EmailControllerTest.php
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/SettingsControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
- tests/php/unit/RepairSteps/CurrentViewNameRepairStepTest.php
> Enforce strict types in PHP

- .travis.yml
- composer.json
- tests/php/unit/Controller/ContactControllerTest.php
- tests/php/unit/Controller/EmailControllerTest.php
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/SettingsControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
- tests/php/unit/RepairSteps/CurrentViewNameRepairStepTest.php
> Test on PHP7.4, remove Firefox as dependency

- package-lock.json
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
> Allow to send publicly shared link via email

- src/fullcalendar/eventOrder.js
- src/fullcalendar/eventSource.js
- src/fullcalendar/eventSourceFunction.js
- src/views/Calendar.vue
- tests/javascript/unit/fullcalendar/eventOrder.test.js
- tests/javascript/unit/fullcalendar/eventSource.test.js
- tests/javascript/unit/fullcalendar/eventSourceFunction.test.js
> Order all-day events by calendar first, title second

- src/components/Editor/Invitees/InviteesListSearch.vue
> Do not show Empty message when clicking the search attendee multiselect

- src/fullcalendar/navLinkDayClick.js
- src/fullcalendar/navLinkWeekClick.js
- src/views/Calendar.vue
- tests/javascript/unit/fullcalendar/navLinkDayClick.test.js
- tests/javascript/unit/fullcalendar/navLinkWeekClick.test.js
> Implement Fullcalendar's navLinkDayClick and navLinkWeekClick

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
- src/components/AppNavigation/CalendarList.vue
- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/ImportScreen.vue
- src/components/Editor/Alarm/AlarmListItem.vue
- src/components/Editor/Alarm/AlarmTimeUnitSelect.vue
- src/components/Editor/Invitees/AvatarParticipationStatus.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
- src/components/Editor/Properties/PropertySelect.vue
- src/components/Editor/Properties/PropertySelectMultiple.vue
- src/components/Editor/Repeat/RepeatEndRepeat.vue
- src/components/Editor/Repeat/RepeatFirstLastSelect.vue
- src/components/Editor/Repeat/RepeatFreqMonthlyOptions.vue
- src/components/Editor/Repeat/RepeatFreqSelect.vue
- src/components/Editor/Repeat/RepeatFreqYearlyOptions.vue
- src/components/Editor/Repeat/RepeatOnTheSelect.vue
- src/components/Shared/CalendarPicker.vue
- src/components/Shared/CalendarPickerOption.vue
- src/components/Shared/TimezoneSelect.vue
- src/views/Calendar.vue
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
> Do not import the entire nextcloud/vue lib

- babel.config.js
> use builtins where possible

- package-lock.json
- package.json
- webpack.prod.js
Similar to https://github.com/nextcloud/calendar/compare/bugfix/noid/remove_comments_production?expand=1
Brings bundle size down by a couple of hundred kB
> Remove comments from final minified build

- css/app-sidebar.scss
- src/components/Editor/Alarm/AlarmList.vue
- src/components/Editor/Alarm/AlarmListNew.vue
Related to #1576 
It was not really discoverable, that clicking the "New reminder" button multiple times, gives you different alarms.
And if you want an alarm 15 mins before, clicking 4 times and deleting three reminders (at time, 5 mins before, 10 mins before) is not really intuitive either.
> Replace New Reminder button with Multiselect to allow easier selection of alarm

- CHANGELOG.md
- appinfo/info.xml
- package.json
> Increment version to 2.0.0 beta3

- lib/Controller/ViewController.php
- package-lock.json
- src/components/Editor/Invitees/InviteesList.vue
- src/services/talkService.js
- src/store/settings.js
- src/views/Calendar.vue
- templates/main.php
- tests/php/unit/Controller/ViewControllerTest.php
> Allow to create talk rooms from calendar

- controller/proxycontroller.php
> Support more IPv6 addresses in ProxyController

- CHANGELOG.md
- appinfo/info.xml
> Release 1.7.2

- src/utils/illustration.js
> Add more illustration words

- css/fullcalendar.scss
- src/fullcalendar/eventRender.js
- src/fullcalendar/eventSource.js
- src/fullcalendar/eventSourceFunction.js
- src/utils/color.js
- tests/javascript/unit/fullcalendar/eventSource.test.js
- tests/javascript/unit/fullcalendar/eventSourceFunction.test.js
- tests/javascript/unit/utils/color.test.js
Implements #1197:
As I'm new to the codebase (and Vue in general), I'm *very* open to criticism! My method for detecting light vs. dark calendar colors felt particularly hacked together; if a better, more general solution exists, I'd prefer to use it.
> Add a reminder icon for events with notifications

- css/fullcalendar.scss
> Fix today indicator in day and week view

- README.md
- appinfo/info.xml
> Update Readme and info.xml with new features

- lib/Controller/ViewController.php
- tests/php/unit/Controller/ViewControllerTest.php
> Allow to override defaults of calendar-app

- CHANGELOG.md
- appinfo/info.xml
> Release 2.0.0 RC

- lib/Controller/PublicViewController.php
- tests/php/unit/Controller/PublicViewControllerTest.php
> Also set talk_enabled in PublicViewController

- src/fullcalendar/eventDrop.js
- src/fullcalendar/eventSource.js
- src/fullcalendar/freeBusyEventSource.js
- src/fullcalendar/vtimezoneNamedTimezoneImpl.js
- src/services/timezoneDataProviderService.js
- src/views/Calendar.vue
- tests/javascript/unit/fullcalendar/eventDrop.test.js
- tests/javascript/unit/fullcalendar/eventSource.test.js
- tests/javascript/unit/fullcalendar/vtimezoneNamedTimezoneImpl.test.js
> Fix resolving timezone alias

- css/fullcalendar.scss
> Style more event popover

- src/components/Editor/Properties/PropertySelectMultiple.vue
Fixes #1827 
|![6590F35F-C818-48AF-83FD-A758294A7544](https://user-images.githubusercontent.com/1250540/72731554-39d9e000-3b94-11ea-9002-13b358d33516.jpg)|![7046E49F-4F19-4FD3-8934-5CA25E9ACBE8](https://user-images.githubusercontent.com/1250540/72731561-3ba3a380-3b94-11ea-8edb-af9d51b2db2f.jpg)|
> Sort categories alphabetically

- src/fullcalendar/eventRender.js
- src/views/EditSimple.vue
- tests/javascript/unit/fullcalendar/eventRender.test.js
Fixes #1818 
|![579E8035-F0B9-4572-9DA9-43E48663CD5C](https://user-images.githubusercontent.com/1250540/72741921-f342b080-3ba8-11ea-8249-87477e90a805.jpg)|![7D563C40-A1C0-4362-8BBD-BC6D0F5B8A0F](https://user-images.githubusercontent.com/1250540/72741923-f50c7400-3ba8-11ea-953a-93a24265a333.jpg)|
|![46057AF6-B760-400E-A948-AD0150F1E658](https://user-images.githubusercontent.com/1250540/72741926-f63da100-3ba8-11ea-85ba-f00d0c1e9fb4.jpg)|![972790B1-5E3A-4BA8-9AD8-A147D0D4AB6E](https://user-images.githubusercontent.com/1250540/72741930-f76ece00-3ba8-11ea-8fd0-641c269b3495.jpg)|
|![2285A0DF-2B49-4DBA-8B1A-C42A0A3A1C9F](https://user-images.githubusercontent.com/1250540/72741932-f89ffb00-3ba8-11ea-8216-ad02cf1b8dff.jpg)|![F69B852B-D1CB-4DFA-AE80-B07765285 …
> Position new event popover based on .fc-event for day and week view

- src/components/Editor/Properties/PropertySelectMultiple.vue
- src/components/Editor/Properties/PropertySelectMultipleColoredOption.vue
fixes #1819 
|![ECA14A72-3062-45AB-AA09-5E476776B223](https://user-images.githubusercontent.com/1250540/72739464-f7b89a80-3ba3-11ea-9981-b2191239cff7.jpg) | ![5B3CC0BF-D5EA-4204-BCCF-F2E65D1A4190](https://user-images.githubusercontent.com/1250540/72739479-fdae7b80-3ba3-11ea-8441-fa38ab8538eb.jpg)|
|![88859435-1C44-4A89-8123-905E459824B5](https://user-images.githubusercontent.com/1250540/72739515-10c14b80-3ba4-11ea-9756-32a032c47b09.jpg)|![0CBCAC6D-677A-4542-896E-0DBDEF1C9375](https://user-images.githubusercontent.com/1250540/72739523-1323a580-3ba4-11ea-9e2d-8934f0af6488.jpg)|
|![9A4EDB27-50BE-471B-9402-9023758CBBD9](https://user-images.githubusercontent.com/1250540/72739533-1585ff80-3ba4-11ea-8ecc-4ff1f3acc651.jpg)|![37FD7CEA-01FD-4B26-9EBC-E2E05C7 …
> Show self-added categories in list, making it easier to remove them

- CHANGELOG.md
- appinfo/info.xml
- package.json
> Release 2.0.1

- .travis.yml
- appinfo/info.xml
Needed for https://github.com/nextcloud/server/pull/18765
> Increment max-version to 19

- src/utils/illustration.js
* Agile ceremonies
* Lunch, Conference, Pair (as in pair programming)
* Some short-hands/misspellings
Fixes # (issue)
1. Create events in the calendar with strings matching the newly added string
2. The chosen illustration should be used rather than the default.
> Illustrations: add a few more activities

- src/main.js
- src/router.js
- src/services/windowTitleService.js
- tests/javascript/jest.setup.js
- tests/javascript/unit/services/windowTitleService.test.js
> Properly localize date in document title

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
> Reset date to 1 before adding one month in top left Datepicker

- css/app-sidebar.scss
|![before_white_timed](https://user-images.githubusercontent.com/1250540/73462949-d3677580-437c-11ea-8711-998c387d1966.jpg)|![after_white_timed](https://user-images.githubusercontent.com/1250540/73462965-d82c2980-437c-11ea-93cc-42cfaee7244e.jpg)|
|![before_white_allday](https://user-images.githubusercontent.com/1250540/73463149-1295c680-437d-11ea-8af0-9b5fe030d2fd.jpg)|![after_white_allday](https://user-images.githubusercontent.com/1250540/73463152-1295c680-437d-11ea-8a06-c30d58924d76.jpg)|
|![before_dark_timed](https://user-images.githubusercontent.com/1250540/73463158-13c6f380-437d-11ea-96b9-88d7de9ed38d.jpg)|![after_dark_timed](https://user-images.githubusercontent.com/1250540/73463156-132e5d00-437d-11ea-8772-43377bafa5a6.jpg)| …
> Fix issue with background-color for icon in datepicker

- src/models/calendar.js
- tests/javascript/unit/models/calendar.test.js
> Fallback to calendarUri if displayname is undefined

- package-lock.json
- package.json
Not sure why dependabot missed those
> Update remaining fullcalendar packages

- src/components/Editor/Properties/PropertyTitleTimePicker.vue
> Properly format read-only datepicker, cleanup dead code

- css/fullcalendar.scss
- src/fullcalendar/dayRender.js
- src/fullcalendar/localeWeekendProvider.js
- src/views/Calendar.vue
- tests/javascript/unit/fullcalendar/dayRender.test.js
- tests/javascript/unit/fullcalendar/localeWeekendProvider.test.js
> Stop hardcoding saturday and sunday as weekend, change it based on locale

- lib/Controller/PublicViewController.php
- lib/Controller/SettingsController.php
- lib/Controller/ViewController.php
- package-lock.json
- package.json
- src/components/AppNavigation/Settings.vue
- src/store/settings.js
- src/utils/router.js
- src/utils/settings.js
- src/views/Calendar.vue
- templates/main.php
- tests/javascript/unit/utils/router.test.js
- tests/javascript/unit/utils/settings.test.js
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/SettingsControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
> Make "show more" configurable 

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
> Handle disabled file_sharing app

- src/components/AppNavigation/Settings/SettingsImportSection.vue
- src/components/Shared/CalendarPicker.vue
> Fix importing ics files on Windows

- src/store/calendarObjectInstance.js
> Fix setting the end timezone

- src/mixins/EditorMixin.js
- src/store/calendarObjectInstance.js
> Preserve duration when modifying starttime

- css/app-settings.scss
- lib/Controller/PublicViewController.php
- lib/Controller/SettingsController.php
- lib/Controller/ViewController.php
- src/components/AppNavigation/Settings.vue
- src/store/settings.js
- src/views/Calendar.vue
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/SettingsControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
Related to #577 (not fixing though, as it's not adding automatic detection)
> Add slotDuration to ConfigController and ViewControllers

- src/store/calendarObjectInstance.js
> Only create recurrence-exceptions for forked events

- lib/Controller/PublicViewController.php
Now all embedding is good again
> Allow embedding in the CSP

- src/store/calendarObjectInstance.js
> Trigger must always be DATE-TIME

- src/components/Editor/Alarm/AlarmListItem.vue
- src/store/calendarObjectInstance.js
> Always allow editing an alarm if it is absolute

- src/store/settings.js
Related to #2071, but not entirely fixing it yet.
> Fix registering significant change properties for calendar.js

- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/ShortcutOverview.vue
This PR just fixes some style warnings (missing trailing comma and a linebreak).
> Fix style warnings

- src/services/caldavService.js
> Enabling WebCal Caching on CalDAV requests

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/SettingsImportSection.vue
- src/components/AppNavigation/Settings/SettingsTimezoneSelect.vue
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Shared/DatePicker.vue
- src/main.js
- src/utils/illustration.js
- src/views/Calendar.vue
> Use nc/dialogs instead of ocp.toast

- css/app-sidebar.scss
- package-lock.json
- package.json
- src/components/Editor/Properties/PropertyText.vue
- src/directives/linkify.js
> Clickable links in read-only mode

- src/components/Shared/DatePicker.vue
> Fixes regression, open timepicker on selecting date

- css/app-sidebar.scss
- src/components/Editor/Properties/PropertyCalendarPicker.vue
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
fixes #2007
|![popover_before](https://user-images.githubusercontent.com/1250540/82787130-14245680-9e66-11ea-980a-47684427bfc0.png)|![popover_after](https://user-images.githubusercontent.com/1250540/82787138-1ab2ce00-9e66-11ea-881b-d8c9a2171061.png)|
|![sidebar_before](https://user-images.githubusercontent.com/1250540/82787160-24d4cc80-9e66-11ea-9639-722fc2e76a25.png)|![sidebar_after](https://user-images.githubusercontent.com/1250540/82787235-4930a900-9e66-11ea-8c2a-32bfa1947599.png)|
> Move calendar-picker above time-picker

- css/app-sidebar.scss
fixes #2291 
|![before](https://user-images.githubusercontent.com/1250540/83496545-8aa20380-a4b9-11ea-9f14-6f2fd296214a.png)|![after](https://user-images.githubusercontent.com/1250540/83496535-88d84000-a4b9-11ea-98a7-33f4cb91fdb9.png)|
> Hide the submit button of the sidebar title

- src/components/AppNavigation/Settings/SettingsImportSection.vue
> Do not mix $t and $n for the same strings

- package-lock.json
- package.json
- src/components/AppNavigation/CalendarList.vue
- src/store/calendars.js
- src/views/Calendar.vue
> Make calendar-list sortable

- src/store/calendars.js
- src/views/Calendar.vue
Fixes a regression introduced by the calendar store cleanup.
> Fix regression in public sharing page

- css/app-navigation.scss
|![45B2F4D0-092C-458E-9F4A-044371A3DF7E](https://user-images.githubusercontent.com/1250540/91291205-01872980-e795-11ea-835b-cb8758ad0aa2.png)|![4643A68C-B760-4DF7-96BB-C0E4FA42BB2D](https://user-images.githubusercontent.com/1250540/91291111-dd2b4d00-e794-11ea-814f-ab85e399e8e6.png)|
> Fix layout issues of calendar sharing

- CHANGELOG.md
- appinfo/info.xml
- package.json
> Release 2.0.4

- package-lock.json
> Downgrade nc/moment to 1.1.0

- src/views/Dashboard.vue
|![F7FA70AE-4C8B-490C-A8AF-A81FB4272641](https://user-images.githubusercontent.com/1250540/92882382-2a075880-f410-11ea-93c2-2b4e93f3db92.png)|![0B664FEE-E314-4FF1-B83E-207AFDAE8296](https://user-images.githubusercontent.com/1250540/92882369-27a4fe80-f410-11ea-966d-bf7cff3eec6d.png)|
> Do not shrink calendar-dot in dashboard view

- src/views/Dashboard.vue
|![C284BB19-9D51-4853-8F67-906CCA280D6F](https://user-images.githubusercontent.com/1250540/92887039-794f8800-f414-11ea-9647-476e904fe5f9.png)|![07845959-A616-41CA-B740-09C3F28FE304](https://user-images.githubusercontent.com/1250540/92887021-76549780-f414-11ea-8440-87f7f3c1d40f.png)|
> Dashboard: Filter events before now

- CHANGELOG.md
- appinfo/info.xml
- package.json
> Release 2.1.1

- .github/workflows/php-test.yml
- appinfo/info.xml
Please review @nextcloud/calendar @rullzer @MorrisJobke
> Up max-version to 21 for server master compatibility

- src/components/Editor/Alarm/AlarmListItem.vue
> Prevent click on edit button to toggle the edit mode twice through click-outside

- src/components/Editor/Alarm/AlarmListItem.vue
> Fix reminder input positioning

- appinfo/info.xml
Broken link now fixed. 
Fixes #1814 
> Fix broken link

- src/fullcalendar/localization/localeProvider.js
Fix calendar rendering with complex locale, e.g. Locales contain script code (zh_Hans_CN)
Fixes: #2633
Follow instructions in #2633
> Fix calendar rendering with complex locale

- .github/workflows/app-code-check.yml
Because on master/21 the command doesn't do anything.
Please give a brief summary of your changes and which issue they address.
Fixes https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#app-code-checker-deprecation
1. Wait for happy CI
In case you changed, added or removed UI elements, please provide a set of before / after screenshots:
|xxxxxxx|xxxxx|
> Run the app code checker against stable20

- composer.json
- composer.lock
No need to keep this updated with https://github.com/nextcloud/calendar/pull/2806 if it's unused.
I'll add Psalm soon.
> Drop the unused phan

- src/views/Dashboard.vue
> Hide cancelled events on dashboard

- package.json
- webpack.common.js
Both folders were considered when building
> Add vendor/ and coverage/ to .stylelintignore

- .github/workflows/package.yml
> Add a package Github action

- css/freebusy.scss
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
- src/fullcalendar/eventSources/freeBusyResourceEventSource.js
- src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
- src/utils/freebusy.js
- tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
> Improve free/busy colors

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/npm-test.yml
- .github/workflows/package.yml
- package-lock.json
- package.json
Backport of https://github.com/nextcloud/calendar/pull/2986
> [stable2.2] Update some deps

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
- src/components/AppNavigation/Settings/ShortcutOverview.vue
Adding a Keyboard shortcut for the List View.
There is still the need for adding the Shortcuts Description to all the different translations.
This closes Issue #2717.
> Keyboard shortcut for List View

- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
Unify the spelling in applications.
> l10n: Correct spelling

- src/components/Editor/Properties/PropertyTitleTimePicker.vue
- src/components/Editor/Repeat/RepeatExceptionWarning.vue
Spelling unification in Nextcloud applications.
> l10n: Unify spelling

- lib/Controller/EmailController.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Extract a space from the translation

- src/components/Editor/Invitees/AvatarParticipationStatus.vue
- src/components/Editor/Invitees/InviteesListItem.vue
> Improve attendance tooltip of resources

- src/components/Editor/FreeBusy/FreeBusy.vue
> Show attendee role in free busy modal

- src/components/AppNavigation/CalendarList/Trashbin.vue
Reported by a Transifex translator.
> l10n: Change "at" to "on"

- src/fullcalendar/eventSources/eventSource.js
- src/store/calendars.js
Fixes #3125 
This one took longer than I'd like to admit :exploding_head: 
Turns out that I searched in all the wrong places but I learned a lot about the calendar app.
> Show restored events immediately

- css/freebusy.scss
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/utils/freebusy.js
> Add caption for free to free busy modal

- src/components/AppNavigation/CalendarList/Trashbin.vue
Fixes #3174 
I got inspired by https://stackoverflow.com/a/26915414. HTML tables are a bit hacky but the forced width works alright.
> Fix whitespace in trash bin modal

- src/components/AppNavigation/CalendarList/Trashbin.vue
> Improve trash bin table header readability

- src/components/AppNavigation/CalendarList/Trashbin.vue
Fixes https://github.com/nextcloud/calendar/issues/3176
> Show date/time of deleted event, move calendar to subline too

- src/components/Editor/Invitees/AvatarParticipationStatus.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
> Fix status indicator overlapping

- package-lock.json
- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/services/caldavService.js
Fixes #3175 
~~Requires my over engineered code from https://github.com/nextcloud/cdav-library/pull/492.~~ (merged)
**EDIT:** Updated screenshot again
> Show calendar color in trash bin

- package-lock.json
- package.json
Both packages have to be updated at the same time due to some breaking changes.
> Bump jest and babel-jest to 27.0.5

- package-lock.json
- src/components/AppNavigation/CalendarList/Moment.vue
> Use ISO8601 timestamps for the CalDAV trashbin

- src/components/Editor/Alarm/AlarmListNew.vue
> Fix 'add reminder' dropdown position

- src/components/AppNavigation/CalendarList/Moment.vue
1. Delete an item
2. Open trashbin
3. Wait 30 seconds
> Fix live time update on trashbin view

- lib/Controller/PublicViewController.php
- lib/Controller/ViewController.php
- src/services/talkService.js
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
> Fix Talk conversation creation with NC22

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
Fix #3311 
Don't include rooms and resources when trying to share a calendar.
> Fix calendar sharing search

- package-lock.json
- package.json
Signed-off-by: Richard Steinmetz <richard@steinmetz.cloud>
> Bump calendar-js to 2f550aa99d961c78da9684f11c8f6ed4d5aae7ba

- src/components/AppNavigation/CalendarList/Trashbin.vue
> Fix trashbin scrolling

- css/app-navigation.scss
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/126135889-b2ac1047-4914-4182-9177-873555f25483.png) | ![image](https://user-images.githubusercontent.com/42591237/126135987-435c3ad3-d9d2-4b2c-b537-55a407a13bff.png) |
> fix settings design regression

- src/components/AppNavigation/CalendarList/Trashbin.vue
> [stable2.3] Fix scrolling for trashbin

- src/components/AppNavigation/CalendarList/Trashbin.vue
This sorts the deleted items to show the latest ones on top.
> Sort objects in trash bin by newest first

- src/components/Editor/Properties/PropertySelect.vue
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/126874494-8f982d46-bd69-45a6-b13e-6010f7eabffd.png) | ![image](https://user-images.githubusercontent.com/42591237/126874464-f0aac214-fac9-4828-869b-ce300c0af2ae.png) |
> improve editor design

- src/components/AppNavigation/CalendarList/Trashbin.vue
> Correctly show vobject title in trash bin

- css/app-sidebar.scss
- src/views/EditSidebar.vue
Fix https://github.com/nextcloud/calendar/issues/1960
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/126864565-31979387-2dd2-4b05-8712-af4557015a06.png) | ![image](https://user-images.githubusercontent.com/42591237/126864539-2486647a-3bad-4af5-bc12-5adb30d6d16e.png) |
> Sticky save buttons

- package-lock.json
- package.json
- src/components/AppNavigation/Settings/SettingsImportSection.vue
- src/fullcalendar/duration.js
- src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
- src/fullcalendar/eventSources/freeBusyResourceEventSource.js
- src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
- src/models/calendarObject.js
- src/models/event.js
- src/models/schedulingObject.js
- src/services/timezoneDataProviderService.js
- src/store/calendarObjectInstance.js
- src/store/calendarObjects.js
- src/store/calendars.js
- src/store/settings.js
- src/utils/calendarObject.js
- tests/assets/loadAsset.js
- tests/javascript/unit/models/calendarObject.test.js
- tests/javascript/unit/models/event.test.js
- tests/javascript/unit/models/recurrenceRule.test.js
- tests/javascript/unit/models/schedulingObject.test.js
- tests/javascript/unit/store/settings.test.js
Ref https://github.com/nextcloud/calendar-js/issues/272
> Install @nextcloud/calendar-js via the npm registry

- css/fullcalendar.scss
https://user-images.githubusercontent.com/42591237/127341158-95ab1c50-5aec-4fbb-b3dc-2429ad656124.mp4
https://user-images.githubusercontent.com/42591237/127340843-524ee68f-50cc-405d-8cf3-d603b800d3fb.mp4
> fix list table

- css/fullcalendar.scss
<details><summary>Sry for the private links but I've used my private data on this to show it on real data. Don't know if thats the best way to do it...  If someone wants to show it on fake data, please go ahead and just create the videos and substitute the ones that I've created.</summary>
https://cloud.nextcloud.com/f/4058580
https://cloud.nextcloud.com/f/4058585
</details>
> fix month view

- css/fullcalendar.scss
https://user-images.githubusercontent.com/42591237/127358658-68bfe213-1c6b-4845-9450-5e3744f95b73.mp4
https://user-images.githubusercontent.com/42591237/127358455-ea98b2b9-1072-41a5-af27-5e0b74f11248.mp4
> fix week view

- src/components/AppNavigation/CalendarList/Trashbin.vue
> Show loading view while loading deleted objects

- src/components/Editor/AvatarParticipationStatus.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
> Fix status indicator alignment

- src/components/Editor/Properties/PropertyTitle.vue
- src/directives/focus.js
> Autofocus event title on popover

- css/app-sidebar.scss
- src/components/Editor/Resources/ResourceListSearch.vue
- src/components/Editor/Resources/ResourceSeatingCapacity.vue
- src/services/caldavService.js
Ref #3184 
Add a seating capacity and feature filters to the resource search. The design could need some improvements. I'm open for feedback and suggestions.
> Filter resources by seating capacity and features

- package-lock.json
- package.json
The update contains changes required for #3415.
> Update cdav-library to e188e3e1ae56d1103d35b9db3ac6a1934522a82e

- src/components/Editor/Resources/ResourceListSearch.vue
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Change of translation source

- src/store/calendarObjectInstance.js
Fix #3472
<details>
```
-e CALENDAR_BRANCH=fix/3472/default-status \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.178.34 \
--user=www-data \
```
</details>
> Set default status

- package-lock.json
- package.json
- src/components/Editor/Resources/ResourceListItem.vue
- src/models/resourceProps.js
Fixes https://github.com/nextcloud/calendar/issues/3419
~Requires https://github.com/nextcloud/cdav-library/pull/558~ via this PR
Adds an action menu for booked rooms and resources containing more information about the resource/room.
> Add actions menu for booked resources

- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Resources/ResourceListItem.vue
- src/views/EditSidebar.vue
Closes https://github.com/nextcloud/calendar/issues/3516
> Replace last icons with material design variants, clean up leftovers

- src/components/AppNavigation/CalendarList/Trashbin.vue
fixes: https://github.com/nextcloud/calendar/issues/3171
Signed-off-by: Romain Lebrun Thauront <romain@framasoft.org>
> Delete all items in trash bin

- lib/AppInfo/Application.php
- lib/Profile/AppointmentsAction.php
- lib/Service/Appointments/AppointmentConfigService.php
Fixes https://github.com/nextcloud/calendar/issues/3541
> Add profile page integration for appointments

- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Migration/Version2040Date20210908101001.php
- lib/Service/Appointments/AppointmentConfigService.php
> Modify Migration for Appointments and Add Start and End

- lib/Db/AppointmentConfig.php
Add start, end and rename buffer to timeBeforeNextSlot
> Add new properties to appts configuration entity

- src/components/Editor/Resources/ResourceListItem.vue
Small improvement from the design discussion with @nimishavijay and @st3iny
> Show resource/room remove action last

- src/components/Editor/Resources/ResourceList.vue
Both if branches rendered the same element with the same message
> Combine identical element

- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
- src/models/appointmentConfig.js
> Add copy link action to appointment configs

- css/app-modal.scss
- src/components/AppNavigation/AppointmentConfigList.vue
- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/Confirmation.vue
- src/models/appointmentConfig.js
- src/store/appointmentConfigs.js
> Add confirmation to appointment config modal

- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
> Add icons for new appointments

- lib/Service/Appointments/DailyLimitFilter.php
- tests/php/unit/Service/Appointments/DailyLimitFilterTest.php
* Look into all of the principal's calendars
* Do the filtering for our special property in PHP
* Create an appointment config with a daily limit of 1 appointment
* Create an event on an upcoming day. Mangle with the oc_calendar_objects data so this event has `X-NC-APPOINTMENT:xyz` where xyz is the token (check URL) of your appointment config
* Try to find slots on the day of that event vs on others
On master: slots were always available
With this patch: the whole day does not show any slots anymore
Requires https://github.com/nextcloud/server/pull/29660. This won't work with Nextcloud 23 RC1 therefore.
> Fix appointments daily max filter

- lib/Service/Appointments/DailyLimitFilter.php
- tests/php/unit/Service/Appointments/DailyLimitFilterTest.php
Fixes https://github.com/nextcloud/calendar/issues/3637
> Do not conflict appointments with cancelled or free events

- src/views/Appointments/Overview.vue
Fix #3623 
Fix #3642
Fix #3644
> Improve appointments overview page

- src/store/calendars.js
This will help us debug https://github.com/nextcloud/calendar/issues/3649.
> Log the calendar ID and response data of inprocessible calendar objects

- src/components/Appointments/AppointmentBookingConfirmation.vue
- src/views/Appointments/Booking.vue
> Show confirmation modal after booking appointments

- src/components/Appointments/AppointmentDetails.vue
Fix #3684
Fix #3685 
Fix #3686 
Fix #3687
> Improve appointment slot booking modal

- lib/Service/Appointments/AvailabilityGenerator.php
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Include the availability settings in the Availability Generator
> Add the Availability Logic to slot generation

- lib/Service/Appointments/AvailabilityGenerator.php
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Change the structure to account for more than one slot per day.
> Fix appointment availability structure

- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Service/Appointments/AppointmentConfigService.php
- lib/Service/Appointments/AvailabilityGenerator.php
- package-lock.json
- package.json
- src/components/AppointmentConfigModal.vue
- src/models/appointmentConfig.js
Fixes https://github.com/nextcloud/calendar/issues/3653
> Add appointments availability

- src/components/AppNavigation/AppointmentConfigList.vue
- src/components/AppointmentConfigModal.vue
- src/models/appointmentConfig.js
- src/store/calendars.js
Fixes https://github.com/nextcloud/calendar/issues/3694
> Fetch the appointment availability default from caldav, if possible

- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/DurationSelect.vue
- src/models/appointmentConfig.js
I mussed have rebased them away before the merge.
> Fix missing appointments commits

- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/NumberInput.vue
> Allow empty daily max input

- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Fixes https://github.com/nextcloud/calendar/issues/3708
> Add preview action link to appointments

- src/components/Appointments/AppointmentDetails.vue
- src/views/Appointments/Booking.vue
> Show an error when booking a slot fails

- src/components/AppointmentConfigModal/VisibilitySelect.vue
Nobody understood it. Now it should be more clear.
> Clarify what public/private means for appointment visibility

- src/components/AppNavigation/AppointmentConfigList.vue
- src/components/AppointmentConfigModal.vue
- src/store/calendars.js
They don't work right now, so they have to be filtered out.
> Do not allow shared calendars for appointments

- src/views/Appointments/Conflict.vue
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Replace comma with a dot

- src/components/Appointments/AppointmentBookingConfirmation.vue
- src/views/Appointments/Booking.vue
> Show appointment booking confirmation on whole page

- src/views/Appointments/Booking.vue
> Show placeholder if no bookable slots are available

- src/components/AppNavigation/Settings.vue
> Show link to personal availability settings

- lib/Service/Appointments/BookingCalendarWriter.php
Fixes https://github.com/nextcloud/calendar/issues/3711
> Add default reminders to appointments

- lib/Service/Appointments/MailService.php
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
> l10n: Changed case of word

- lib/Service/Appointments/BookingCalendarWriter.php
> Add preparation and followup duration events to calendar

- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Fixes https://github.com/nextcloud/calendar/issues/3740
> Fix wrong appointments delete icon

- lib/Service/Appointments/BookingCalendarWriter.php
> Add Metadata for Appointments' Preparation and Followup Duration Events

- lib/Db/AppointmentConfigMapper.php
- lib/Db/BookingMapper.php
executeStatement is available only in Nextcloud 22
Closes #3763
> Remove usages of executeStatement

- .github/workflows/lint.yml
- composer.json
- lib/Controller/AppointmentController.php
- lib/Controller/ViewController.php
- lib/Db/AppointmentConfig.php
- lib/Profile/AppointmentsAction.php
- lib/Service/Appointments/AvailabilityGenerator.php
- lib/Service/Appointments/BookingService.php
> Add php 7.2 linter and fix errors

- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/DurationInput.vue
Fix #3724
The code isn't beautiful but it works fine.
> Move minutes inside the appointment config duration input

- css/app-navigation.scss
Ref https://github.com/nextcloud/server/issues/29591
> Fix navigation button padding

- .github/workflows/php-test.yml
- appinfo/info.xml
> Drop version 20, limit php versions, add authors

- lib/Db/BookingMapper.php
Fix https://github.com/nextcloud/server/issues/30094
Fix https://github.com/nextcloud/server/issues/30093
> Fix SQL error when deleting a user

- appinfo/info.xml
> Fix user documentation url

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/npm-test.yml
- .github/workflows/php-test.yml
- appinfo/info.xml
> Rename master to main

- src/components/Editor/SaveButtons.vue
> Fix minor typo

- css/fullcalendar.scss
> Follow up to design changes in month view

- src/store/calendars.js
Ref https://github.com/nextcloud/calendar-js/pull/379
This is the only occurrence.
> Prepare for circular import fix in @nextcloud/calendar-js

- src/components/AppNavigation/CalendarList/Trashbin.vue
Fix is very similar to https://github.com/nextcloud/tasks/pull/1873
Closes #3894
> Fix trashbin being inacessible when the calendar of a deleted object's unavailable

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
resolve #3932 
ActionInput has been improved for accessibility. Aria-Label has been added to the input.
Signed-off-by: julia.kirschenheuter <julia.kirschenheuter@nextcloud.com>
> Enhancement for "New calendar"

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderTodayButton.vue
fixes #3934
unneeded attributes "title" and "aria-label" has been removed
Signed-off-by: julia.kirschenheuter <julia.kirschenheuter@nextcloud.com>
> Remove unneeded data from AppNavigationHeaderTodayButton

- README.md
Ref https://github.com/nextcloud/groupware/issues/6
> Update installation and maintainers info on readme

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
> Add plus-icon for AppNavigationHeaderNewEvent

- src/components/AppNavigation/Settings/SettingsImportSection.vue
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
> l10n: Remove dot in plural string

- lib/Controller/PublicViewController.php
> Fix broken public calendar

- .github/workflows/lint.yml
- .github/workflows/php-test.yml
- appinfo/info.xml
- composer.json
- composer.lock
- lib/Db/AppointmentConfig.php
- lib/Db/Booking.php
- lib/Service/JSDataService.php
Ref https://github.com/nextcloud/groupware/issues/27
> Add PHP8.1 support

- src/components/CalendarGrid.vue
- src/fullcalendar/localization/momentPlugin.js
Fix #2960
I refactored the `momentPlugin` to a factory pattern. Before, it directly imported the Vuex store to load the current locale which caused some problems. My guess that this is caused by a race condition or low level bug somewhere in V8 (JS-Engine of Chrome).
Please give this one a good test.
> Fix crash on Chromium when opening the simple editor from an URL

- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/store/settings.js
- src/views/Dashboard.vue
Fix #4096 
This fixes time formatting for the dashboard widget and trash bin modal. Both instances now respect the configured time zone.
> Fix trashbin and dashboard not respecting configured timezone

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
- src/router.js
> Fix view switching on creating new events

- src/components/Editor/FreeBusy/FreeBusy.vue
Fix #4137
Fix #4209
This is a regression from #4114
> Fix free busy not rendering

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
Followup to #4241 
```
[Vue warn]: Invalid prop: type check failed for prop "size". Expected Number with value 22, got String with value "22".
```
> Fix invalid icon size prop type

- src/components/Appointments/AppointmentBookingConfirmation.vue
> Improve appointment booking message

- css/app-settings.scss
Fix #4219
| --- | --- |
| ![before](https://user-images.githubusercontent.com/47037905/168540022-4f7a5c9a-b150-4bec-8cc5-d717cd852633.png) | ![image](https://user-images.githubusercontent.com/1479486/170779563-90918984-d206-41fd-8978-f7aa08d56d69.png) |
> Fix squished settings checkbox

- src/components/Editor/Invitees/InviteesListSearch.vue
> Use randomId() everywhere

- src/components/EventRender.vue
- src/fullcalendar/eventSources/eventSourceFunction.js
- tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Fixes https://github.com/nextcloud/calendar/issues/3162
Supersedes https://github.com/nextcloud/calendar/pull/3994
> Show icon for events with attendees

- .github/workflows/lint.yml
- .github/workflows/php-test.yml
- appinfo/info.xml
- composer.json
- composer.lock
It has reached EOL https://www.php.net/supported-versions.php
> Drop PHP7.3 support

- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
- src/components/Editor/Resources/ResourceListItem.vue
Fix #4380 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/179680174-b88b1371-79b8-45a4-a47b-a01e229d201f.png) | ![Screenshot 2022-07-19 at 09-20-56 July 2022 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/179691611-67d53edc-675d-43cf-b93a-5a1a6e0209a5.png) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/179691927-6e362f8b-c32e-45d7-a981-897bf98cffe4.png) | ![Screenshot 2022-07-19 at 09-23-49 July 2022 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/179691999-e6aab9e3-7bb2-4ffa-9fc7-25fc8519b2cf.png) ![Screenshot 2022-07-19 at 09-24-06 July 2022 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/179692000-310145e8-2800-4c2 …
> Fix invitee and resource name wrapping

- src/components/AppNavigation/Settings.vue
For https://github.com/nextcloud/server/issues/32350
> Rename settings to Calendar Settings

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/Editor/AvatarParticipationStatus.vue
- src/components/Editor/Properties/PropertyTitleTimePicker.vue
- src/components/Icons/IconCircles.vue
- src/views/Dashboard.vue
migration of avatar participants status
icon circles on sharing calendar
icon timezone on property
> Migrate leftover icons to material design

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/npm-test.yml
- .github/workflows/php-test.yml
> Add summary jobs for build, lint and test workflows

- .github/workflows/php-test.yml
> Adjust testing matrix for Nextcloud 25 on main

- css/app-sidebar.scss
Fix #4532 
| --- | --- |
| ![before](https://user-images.githubusercontent.com/12728974/191539908-3492ccff-bb67-4183-b401-2ef8126f8516.png) | ![image](https://user-images.githubusercontent.com/1479486/191962314-e73d97b3-8eb5-424f-8b19-ecbb3d673f73.png) |
> Fix date timer picker being cut of in simple editor

- css/fullcalendar.scss
Fix #4527
Fix #4528
My changes are best reviewed with hidden white space changes.
> Improve contrast of current day header

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
Fix #4252
| Before | After
| --- | --- |
| ![Screenshot 2022-09-23 at 15-18-45 September 2022 - Calendar - Nextcloud](https://user-images.githubusercontent.com/1479486/191969149-d1b17d62-96fd-4d9e-a030-8e1224be07c3.png) | ![image](https://user-images.githubusercontent.com/1479486/191969018-f29e6f54-3c60-4dec-a3d8-e3871eb2bdae.png) |
> Improve new calendar button design

- css/fullcalendar.scss
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>
Before : 
After :
> Fix : Checkbox icon position in Deck events

- src/views/Appointments/Conflict.vue
> Fix appointments confirmation page background

- package-lock.json
- package.json
- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/components/AppNavigation/Settings.vue
- src/main.js
Fixes #4526 
Fix copying text to the clipboard
Remove using on vue-clipboard2
See the reference https://github.com/nextcloud/tasks/pull/2115
> Fix copying text to the clipboard

- css/fullcalendar.scss
Fix #4541
| --- | --- |
| ![Bildschirmfoto vom 2022-09-23 17-41-36](https://user-images.githubusercontent.com/1374172/192000473-81ce5e83-290c-4760-b12d-1d3cea20cf32.png) | ![image](https://user-images.githubusercontent.com/1479486/194544746-3407f9a3-a5a6-4d29-a8a6-a4af6baf0706.png) |
| ![Bildschirmfoto vom 2022-09-23 17-50-58](https://user-images.githubusercontent.com/1374172/192001628-3edf87cd-1cae-4a02-a264-c411778ff119.png) | ![image](https://user-images.githubusercontent.com/1479486/194544663-2499a8ca-3148-437f-b71a-85a6fe981d7a.png) |
> Fix fc border color

- src/views/Appointments/Booking.vue
Fixes #4543 
| Before | After
|---|---|
| ![Bildschirmfoto vom 2022-09-23 18-48-58](https://user-images.githubusercontent.com/1374172/192013617-d5782f01-de5c-460e-a687-ce113ddaeb65.png) | ![Bildschirmfoto vom 2022-09-23 18-53-45](https://user-images.githubusercontent.com/1374172/192013646-886022ea-48e5-454e-8f9b-c680959a6920.png) |
> Add missing background color for appointments page

- src/views/Appointments/Booking.vue
[booking-scroll.webm](https://user-images.githubusercontent.com/1479486/195109957-d6a7c6c6-9dde-43cc-a4ba-448c4e1f453c.webm)
[scroll-mobile.webm](https://user-images.githubusercontent.com/1479486/195109968-0ea8194d-953c-4b40-96e0-27bb515b34d1.webm)
> Improve design of appointments booking page

- package-lock.json
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
> Fix lockfile

- .github/dependabot.yml
Ref https://github.com/nextcloud/groupware/issues/54
Composer: @st3iny and me
NPM: @JuliaKirschenheuter and @st3iny
> Assign dedicated Dependabot bump reviewers

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/npm-test.yml
- .github/workflows/package.yml
- .github/workflows/php-test.yml
Same as https://github.com/nextcloud/mail/pull/7422.
> Only test PRs, not pushes

- src/components/Appointments/AppointmentBookingConfirmation.vue
> Fix styles for appointment confirmation dialogue

- lib/Dashboard/CalendarWidget.php
- tests/php/unit/Dashbaord/CalendarWidgetTest.php
> Fix mobile widget showing past events and limiting results too much

- CHANGELOG.md
> Forward port complete changelogs to main

- README.md
> Add new screenshot for readme

- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/Settings.vue
Good evening,
since I got the same error as in #4694, I tried to fix it myself. 
Now it works for me again
Before:
After:
> Fix clipboard copy

- lib/Service/Appointments/BookingCalendarWriter.php
Fixes https://github.com/nextcloud/calendar/issues/3854
> Add location to booking VEVENT

- src/components/Shared/DatePicker.vue
i spent one hour of my life trying to bisect this, just to realize that the popover component is changed.
fixes #4630
> Fix disabled timezone

- package-lock.json
- package.json
https://github.com/nextcloud/nextcloud-vue/releases/tag/v7.1.0
> Bump @nextcloud/vue to 7.1.0

- src/components/Shared/DatePicker.vue
> [stable4.1] Fix timezone multi-select popup

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v3.5.3

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v4.1.1

- src/store/calendarObjectInstance.js
- src/utils/alarms.js
> Improve handling of email alarms

- CHANGELOG.md
> Forward port v4.1.1 changelog

- src/components/AppNavigation/CalendarList/Trashbin.vue
> feat: migrate trash bin buttons to NcButton

- css/app-sidebar.scss
- css/public.scss
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderTodayButton.vue
- src/components/AppNavigation/EmbedHeader/EmbedHeaderTodayButton.vue
- src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
- src/components/AppNavigation/Settings/ImportScreen.vue
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/Confirmation.vue
- src/components/Appointments/AppointmentDetails.vue
- src/components/Appointments/AppointmentSlot.vue
- src/components/Editor/InvitationResponseButtons.vue
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Properties/PropertyColor.vue
- src/components/Editor/Repeat/RepeatFreqMonthlyOptions.vue
- src/components/Editor/Repeat/RepeatFreqWeeklyOptions.vue
- src/components/Editor/Repeat/RepeatFreqYearlyOptions.vue
- src/components/Editor/SaveButtons.vue
> Replace <button> with ButtonVue and fix styles in AppointmentSlot.vue

- src/components/Appointments/AppointmentSlot.vue
:broom: 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/209139006-6febc9c1-5a81-48b7-bd59-6b6e98b4943d.png) | ![image](https://user-images.githubusercontent.com/1479486/209137814-bd13d8e9-5c71-4ed8-9abf-9977be56b2aa.png) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/209138633-3f9b2252-962e-45d5-a01c-c5c9c62ed2bb.png) | ![image](https://user-images.githubusercontent.com/1479486/209137989-6cec6a55-738f-46bb-a236-e3177e1bf67a.png) |
> fix(appointments): equalize slot booking button width

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v4.1.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v4.2.0-rc1

- appinfo/info.xml
- package-lock.json
- package.json
> Bump main to v4.3.0-alpha.0

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v4.2.0

- CHANGELOG.md
> Forward port 4.2.0 changelog

- appinfo/info.xml
Signed-off-by: p-bo <pavel.borecki@gmail.com>
> App metadata - add links to admin and dev docs

- .github/workflows/lint-php.yml
Ref https://github.com/nextcloud/groupware/issues/41
To maintain fewer actions in our repository.
> ci: use shared workflow for php lint

- .github/workflows/lint-eslint.yml
Ref https://github.com/nextcloud/groupware/issues/41
To maintain fewer actions in our repository.
> ci: use shared workflow for eslint

- css/app-sidebar.scss
Fixes https://github.com/nextcloud/calendar/issues/4870
| --- | --- |
| ![image](https://user-images.githubusercontent.com/7427347/210213293-dc3217fe-94a6-4584-b4d5-93f074fa50d9.png) | ![image](https://user-images.githubusercontent.com/7427347/210774555-60a82067-98ff-4751-8f4e-a7d74d45f102.png) |
> Widen input to account for charets

- package-lock.json
- package.json
Ref https://github.com/vuejs/vue-jest#installation
> chore(npm): replace vue-jest with @vue/vue2-jest

- .github/workflows/appstore-build-publish.yml
- .github/workflows/fixup.yml
- .github/workflows/lint-eslint-when-unrelated.yml
- .github/workflows/lint-eslint.yml
- .github/workflows/lint-info-xml.yml
- .github/workflows/lint-php-cs.yml
- .github/workflows/lint-php.yml
- .github/workflows/node-when-unrelated.yml
- .github/workflows/node.yml
> chore(CI): Update main php testing versions and workflow templates

- src/views/Calendar.vue
Was removed as part of a87dfb4bc0c00d0e68fee9d06c664f645faa46a3
> fix(appointments): Fix disabling appointments feature

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v4.2.2

- CHANGELOG.md
> chore: Forward port v4.2.2 changelog

- lib/Controller/BookingController.php
- tests/php/unit/Controller/BookingControllerTest.php
> Refine exception handling for booking controller

- .github/workflows/php-test.yml
> Run stable3.5 phpunit workflows on NC 22 to 24 only

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release v4.2.3

- lib/AppInfo/Application.php
- lib/Notification/Notifier.php
- lib/Service/Appointments/BookingService.php
- lib/Service/Appointments/MailService.php
- tests/php/unit/Notification/NotifierTest.php
- tests/php/unit/Service/Appointments/MailServiceTest.php
> Add email notifications for organiser to appointments

- src/views/EditSidebar.vue
> l10n: Fixed grammar

- package-lock.json
Bump dependencies that dependabot didn't catch
> [stable4.2] chore: bump json5

- src/utils/closestColor.js
Add attributions to vendored code from #5005.
I'm no lawyer but it's probably a good idea to include proper attribution.
> chore: add attributions

- .github/workflows/package.yml
:crossed_fingers: it helps with the CI failure in https://github.com/nextcloud/calendar/pull/4971
> ci(package): Use Composer v2

- .github/workflows/lint-php.yml
- .github/workflows/php-test.yml
- appinfo/info.xml
- composer.json
- composer.lock
- vendor-bin/cs-fixer/composer.json
- vendor-bin/cs-fixer/composer.lock
- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
Fixes https://github.com/nextcloud/calendar/issues/5019
> feat(deps): Revive PHP7.4 support

- .github/workflows/php-test.yml
> chore(CI): Adjust testing matrix for Nextcloud 26 on main

- .github/workflows/lint-php.yml
- .github/workflows/php-test.yml
- appinfo/info.xml
- composer.json
- composer.lock
I tested this locally with PHP 7.4 and it works fine.
> [stable4.3] feat: revive support for php 7.4

- appinfo/info.xml
- package-lock.json
- package.json
```
f46a3d8a feat: revive support for php 7.4
d0eb730d fix(appointments): calendar booking notifications
2f8b3e9d fix(attachments): generate proper urls to dav service
```
> v4.3.0-rc.2

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> release: v4.3.0

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
> fix: indicate if calendar is shared by me

- src/models/appointmentConfig.js
> fix(appointments): set visibility to private by default

- src/views/Calendar.vue
> chore: remove dead code left over from #5077

- src/fullcalendar/localization/dateFormattingConfig.js
Updated file to arrange in a 'date, day' manner.
Fix https://github.com/nextcloud/calendar/issues/4891
Fix https://github.com/nextcloud/calendar/issues/5162
> Fix date formatting in list view

- src/components/AppNavigation/EditCalendarModal.vue
- src/components/AppNavigation/EditCalendarModal/InternalLink.vue
Fixes #4890 
Ref https://github.com/nextcloud/calendar/pull/5187#issuecomment-1533238302 for a mockup
I created a new (feature) PR because some changes can't be backported. It contains new translations.
> feat: implement dedicated calendar modal save button

- css/app-navigation.scss
- css/fullcalendar.scss
- src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
- src/components/Appointments/AppointmentDetails.vue
Explanation: the color-primary variables are not to be used in components because the introduce problems with high-contrast primary colors. Fix this by using the primary-element variables instead.
> Use the color-primary-element* variables

- .github/workflows/php-test.yml
> chore(CI): Adjust testing matrix for Nextcloud 27 on main

- css/app-settings.scss
> Better display of default slot duration and reminder

- lib/Listener/AppointmentBookedListener.php
> fix(appointements): add context for translators for the talk room name string

- renovate.json
User names should not start with an at symbol.
> chore: fix renovate requests for review

- Makefile
- README.md
Add a link to the installation prerequistes and add composer install to make command
Fixes https://github.com/nextcloud/calendar/issues/5247
> fix: add requistes link to README

- .github/workflows/npm-test.yml
- .github/workflows/php-test.yml
Add the codedov token so coverage reports are reliable again.
> chore: add codecov token

- src/components/Editor/Invitees/InviteesList.vue
- src/services/talkService.js
Fixes https://github.com/nextcloud/calendar/issues/5377
> feat(talkintegration): Set Talk conversation description

- appinfo/info.xml
- package-lock.json
- package.json
Fixes https://github.com/nextcloud/calendar/issues/5401
> Release v4.5.0-rc.1

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Fixes https://github.com/nextcloud/calendar/issues/5403
> build: v4.5.0-rc2

- src/views/Appointments/Booking.vue
Demo (before changing icon to material)
https://user-images.githubusercontent.com/2197836/173613401-972af52b-6ad0-4d68-a7fe-0257ececaae3.mp4
> Show indicator when loading slots and show toast in case of error

- renovate.json
Ref https://github.com/nextcloud/calendar/pull/5515
Ref https://github.com/nextcloud/calendar/pull/5492
> chore(renovate): add multimonth to fullcalendar family

- lib/Listener/AppointmentBookedListener.php
Fixes https://github.com/nextcloud/calendar/issues/5496
https://github.com/nextcloud/calendar/pull/4025#discussion_r829414631
> fix(appointments): Make rooms public

- .github/workflows/php-test.yml
> [stable4.6] chore: update workflows

- src/fullcalendar/localization/localeProvider.js
> Fix: translate month in year view

- src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
> fix(attachments): folder picker opening twice

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Rate limit appointment booking and config creation
- Apointment confirmation modal button style
- Filtering in sharing search
- Attachment folder picker opening twice
> Release v4.6.3

- CHANGELOG.md
Fixes https://github.com/nextcloud/calendar/issues/5640
> chore: forward port v4.6.1, v4.6.2, v4.6.3 changelog

- src/components/Editor/AvatarParticipationStatus.vue
Fixes https://github.com/nextcloud/calendar/issues/3433
> fix(scheduling): Rephraze "Invitation sent" to "Awaiting response"

- src/resources/holiday_calendars.json
Resolves: https://github.com/nextcloud/calendar/issues/5797
> fix: update holiday calendars

- src/resources/holiday_calendars.json
Follow up to https://github.com/nextcloud/calendar/pull/5815
> fix: kazakhstan holiday calendars

- css/app-sidebar.scss
- src/views/EditSidebar.vue
> fix(editor): bring back the three-dot menu

- src/components/AppNavigation/Settings.vue
- src/components/Shared/CalendarPicker.vue
Fixes:
- Search not working
- Remove the clear button
https://github.com/nextcloud/calendar/assets/1479486/b97d677c-c755-4135-818b-a1f7664e53d4
> fix: default calendar picker search and make it not clearable

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/components/AppNavigation/EditCalendarModal.vue
- src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
- src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
- src/components/Appointments/AppointmentDetails.vue
- src/components/Editor/AvatarParticipationStatus.vue
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/components/Shared/DatePicker.vue
- src/views/Appointments/Overview.vue
- src/views/EditSidebar.vue
Fix #5693 
I also removed some dead styles during testing.
> chore(vue3): migrate ::v-deep to :deep

- lib/AppInfo/Application.php
- lib/Listener/CalendarReferenceListener.php
- lib/Reference/ReferenceProvider.php
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
- src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/components/CalendarGrid.vue
- src/fullcalendar/interaction/eventClick.js
- src/mixins/EditorMixin.js
- src/reference.js
- src/store/calendars.js
- src/views/Calendar.vue
- src/views/EditSimple.vue
- webpack.config.js
For #5746
1. Create a new calendar
2. Add events to the calendar
3. Create a share link for the calendar (URL includes the /p/ part)
4. Open Talk or Text
5. Paste the link
> feat: Calendar widget for publicly shared calendars

- src/views/EditSimple.vue
Fix #5840
https://github.com/nextcloud/calendar/assets/1479486/26d31f67-6885-478c-bda8-296eb3d1dbcf
> fix(editor): switching to sidebar after creating a new event

- src/components/CalendarGrid.vue
- src/fullcalendar/interaction/eventClick.js
https://github.com/nextcloud/calendar/pull/5847#discussion_r1530260926
> Fix: can't click on widget event after conversation change in Talk

- .github/workflows/php-test.yml
> chore(CI): Adjust testing matrix for Nextcloud 29 on main

- lib/Reference/ReferenceProvider.php
- src/components/CalendarGrid.vue
- src/reference.js
- src/views/Calendar.vue
For  https://github.com/nextcloud/calendar/issues/5746
1. Create a new calendar
2. Add events to the calendar
3. copy internal link of a calendar
4. Open Talk or Text
5. Paste the link
PS: try testing with multiple calendar, mixing private and public link in one/multiple conversations
> Feat: calendar widget for private calendars

- appinfo/info.xml
- package-lock.json
- package.json
> release: v4.7.0-rc.2

- src/views/EditSidebar.vue
Fixes https://github.com/nextcloud/calendar/issues/5933
🏚️ Before | 🏡 After
---|---
> Fix misplaced empty content

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> build: release v4.7.0

- src/components/AppNavigation/EditCalendarModal/ShareItem.vue
- src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
Fix https://github.com/nextcloud/calendar/issues/4406
TODO:
> Add email information when sharing

- src/components/CalendarGrid.vue
The calendar options are resolved asynchronously but the ref was accessed in `mounted()` which led the resize observer to not getting set up.
Now, the resize observer is started after the options were resolved and the FullCalendar component is actually mounted.
https://github.com/nextcloud/calendar/assets/1479486/885dbe8b-dc68-43cf-b270-c57dab648862
https://github.com/nextcloud/calendar/assets/1479486/87e5c0dc-01d7-413f-b05b-d92a9777ec6d
> fix: delay initializing the resize observer until FC is ready

- package-lock.json
- package.json
- webpack.config.js
Ref https://github.com/nextcloud/calendar-js/pull/720
~Upstream release is pending.~
> chore: bump @nextcloud/calendar-js to 7.0.0

- .gitignore
Added VS Code IDE folder to git ignore list
> fix: Ignore VScode IDE directory

- package-lock.json
This audit fix resolves 1 of the total 10 vulnerabilities found in your project.
* [ws](#user-content-ws)
* ws affected by a DoS when handling a request with many HTTP headers
* Severity: **high** (CVSS 7.5)
* Reference: [https://github.com/advisories/GHSA-3h5v-q93c-6h6q](https://github.com/advisories/GHSA-3h5v-q93c-6h6q)
* Affected versions: 8.0.0 - 8.17.0
* Package usage:
* `node_modules/ws`
> [stable4.7] Fix npm audit

- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
- src/components/Editor/Attachments/AttachmentsList.vue
- src/components/Editor/Properties/PropertySelect.vue
- src/components/Editor/Properties/PropertySelectMultiple.vue
- src/components/Editor/Resources/ResourceListSearch.vue
- src/components/Editor/Resources/ResourceRoomType.vue
- src/components/Shared/CalendarPicker.vue
- src/components/Shared/DatePicker.vue
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Resolves https://github.com/nextcloud/calendar/issues/6080
Fixes all console warnings and errors I encountered.
> Fix misc console errors and warnings

- lib/Service/CalendarInitialStateService.php
> [stable 4.7] fix: check if userId is null

- tests/php/unit/Service/CalendarInitialStateServiceTest.php
This is a follow-up to https://github.com/nextcloud/calendar/pull/6115.
cc @am97
> test: Add unit test for anonymous initial state access

- src/components/AppNavigation/EditCalendarModal/InternalLink.vue
- src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
- src/components/AppNavigation/Settings.vue
in alignment with @jancborchardt - see https://github.com/nextcloud/server/pull/45972 for reference
> Update copy icon to Material Design icon

- css/app-navigation.scss
Fix https://github.com/nextcloud/calendar/issues/6144
| A | B |
| - | - |
| ![Screenshot from 2024-07-15 16-48-51](https://github.com/user-attachments/assets/1e52e2e4-24aa-4881-8abb-9aa17e81ec93)|![Screenshot from 2024-07-15 16-48-06](https://github.com/user-attachments/assets/059613fe-a880-4586-8911-05126eaca5b3) |
> AppNavigationHeaderDatePicker: adjust border radius

- src/views/Calendar.vue
Fix https://github.com/nextcloud/calendar/issues/6153
| A | B |
| - | - |
|![image](https://github.com/user-attachments/assets/74e1cdea-3d51-45c1-9a58-688f4e2ce851)| ![image](https://github.com/user-attachments/assets/40a28a87-ee69-4c49-a49b-fcea973fa027) |
> style(Calendar): remove extra spaces sidebar

- appinfo/info.xml
- composer.json
- composer.lock
> Drop support for Nextcloud <30 and PHP 8.0

- CHANGELOG.md
- package-lock.json
- package.json
Purposely leaving out the fixes that will be released in v4.7.13
> release: v5.0.0-alpha.1

- package-lock.json
Manual backport of https://github.com/nextcloud/calendar/pull/6205
> [stable4.7] chore(deps): update fast-xml-parser to 4.4.1

- css/app-navigation.scss
Give a border to the sidebar button
| ![image](https://github.com/user-attachments/assets/b2580646-adf2-4cbd-bee5-e508f09ce56b) | ![image](https://github.com/user-attachments/assets/9936fa7c-d8e3-4f47-9e15-e95a6f79f1d3) |
| ![image](https://github.com/user-attachments/assets/982d3df9-eb76-488b-9f42-29d9e4b9acc3) | ![image](https://github.com/user-attachments/assets/a1584fc1-3f0f-43fa-b9b8-e2a114ed274d) | 
cc @nextcloud/designers
> fix: add border to sidebar button

- src/components/Editor/Repeat/Repeat.vue
Recurrence selection was not working, now it works. 
Fixes #6228
> fix: recurrance selection

- src/components/Editor/Repeat/Repeat.vue
- src/store/calendarObjectInstance.js
Recurrence until selection was broken. Now its fixed.
> fix: recurrance until selection

- css/fullcalendar.scss
> fix(fc): adjust week day header border radius to new design

- css/app-settings.scss
- src/components/AppNavigation/Settings/SettingsImportSection.vue
| --- | --- |
| ![grafik](https://github.com/user-attachments/assets/b97ec5b9-553b-4cad-a37d-717d941925d9) | ![grafik](https://github.com/user-attachments/assets/bfd169ec-372c-4c1d-b665-ffa106e572d4) |
> fix(settings): adjust design of import button

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> release: v5.0.0-beta.3

- src/components/Editor/FreeBusy/FreeBusy.vue
- src/components/Editor/FreeBusy/RoomAvailabilityList.vue
- src/components/Editor/FreeBusy/RoomAvailabilityModal.vue
See: https://sass-lang.com/documentation/breaking-changes/mixed-decls/
> chore: fix sass deprecation with mixed declaration in nested rules

- css/app-sidebar.scss
- src/components/Editor/Properties/PropertyTitle.vue
- src/views/EditSimple.vue
fix #6404
fix #6403
| b | a |
| ![image](https://github.com/user-attachments/assets/980f9c14-74be-4fcf-8e34-8ca3eae82fff) | <img width="532" alt="image" src="https://github.com/user-attachments/assets/2bbfe9b2-5685-48cc-95c6-e044ee941069"> |
> fix(rtl): align event title

- src/components/Shared/CalendarPicker.vue
> fix(calendarPicker): undefined calendar

- renovate.json
Ref https://github.com/nextcloud/groupware/blob/8f662c09e9c6784ae297e0b8186eac961862b6f2/README.md.
> chore: Update renovate bump reviewers

- src/components/Appointments/AppointmentDetails.vue
- src/utils/localeTime.js
- src/views/Appointments/Booking.vue
> Feat: [Appointments] Better UX after you select a date and time while booking appointments

- .nextcloudignore
Tool configuration and e2e tests should not be shipped.
> fix(release): Ignore unnecessary files

- .github/workflows/npm-test.yml
reflecting org template values
> Bump checkout to v4 and codecov to v5

- src/components/Editor/Invitees/InviteesList.vue
- src/views/EditSimple.vue
Resolves https://github.com/nextcloud/calendar/issues/6585
| Read-only | Editing | Editing (no invitees) |
| --- | --- | --- |
| ![spectacle_20241230_101853](https://github.com/user-attachments/assets/284a94f5-2ab4-46e4-9b88-8a13759b2b5a) | ![spectacle_20241230_101918](https://github.com/user-attachments/assets/69fb2909-93cc-4f37-91da-0cc752f6274e) | ![spectacle_20241230_101934](https://github.com/user-attachments/assets/8d7047f6-d5e2-4754-b521-6a243c49ee7f) |
> feat(editor): allow adding attendees in simple editor

- src/models/rfcProps.js
- tests/javascript/unit/models/rfcProps.test.js
> feat: improve the description text

- .github/workflows/php-test.yml
- appinfo/info.xml
- package-lock.json
- package.json
> feat: add support for nextcloud 32

- src/views/ContactsMenuAvailability.vue
| Before | After | 
| --- | --- |
| ![image](https://github.com/user-attachments/assets/4e2a0158-9f91-41aa-9a87-ec5d19fd6088) | ![spectacle_20250128_092536](https://github.com/user-attachments/assets/13c650d4-9c29-4d3d-9525-8d6fc9cabc8d) |
> fix: show display name instead of user id in availability integration

- appinfo/info.xml
- package-lock.json
- package.json
Reverts nextcloud/calendar#6716
The automation takes over after this.
> Revert "release v5.0.10"

- src/views/EditSidebar.vue
Resolves: #6713
Resolves: https://github.com/nextcloud/calendar/issues/6547
> fix: EditSideBar bug

- src/mixins/EditorMixin.js
Fix https://github.com/nextcloud/calendar/issues/6711
> Fix date selector resetting time

- css/app-settings.scss
- src/components/AppNavigation/Settings/ShortcutOverview.vue
Fix https://github.com/nextcloud/calendar/issues/6726
(No scroll bar.)
| Normal screen | Small screen |
| --- | --- |
| ![spectacle_20250217_171733](https://github.com/user-attachments/assets/a66675e6-f7e4-4c03-9c2b-ede8764ae551) | ![spectacle_20250217_172153](https://github.com/user-attachments/assets/bbdc58f8-ace2-47bc-a49e-dcb3c456cb0f) |
> fix: keyboard shortcut modal not being responsive

- src/mixins/EditorMixin.js
Ref https://github.com/nextcloud/calendar/pull/6725#discussion_r1959669015
> refactor: don't rely on locale when parsing date

- lib/Dashboard/CalendarWidget.php
- tests/php/unit/Dashbaord/CalendarWidgetTest.php
> fix: do not show items from deleted calendars in widget

- css/app-sidebar.scss
- src/components/AppNavigation/Settings/ShortcutOverview.vue
- src/components/Editor/CalendarPickerHeader.vue
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/fullcalendar/interaction/eventDrop.js
- src/store/calendarObjectInstance.js
- src/utils/attendee.js
- src/views/ContactsMenuAvailability.vue
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
- tests/javascript/unit/fullcalendar/interaction/eventDrop.test.js
Don't allow attendee to edit 
- dates
- Title
- Attendees
- Resources 
to avoid running into  #6701
> fix: restrict attendees edit priveleges in the frontend

- src/components/Editor/Invitees/InviteesListItem.vue
> [stable4.7] fix: do not show attendee actions in viewing mode

- src/mixins/EditorMixin.js
- src/store/calendarObjectInstance.js
Fix https://github.com/nextcloud/calendar/issues/6881
> Fix end time resetting when changing day

- src/mixins/EditorMixin.js
After https://github.com/nextcloud/calendar/pull/6882
> chore: fix jsdoc copy paste issue

- src/services/talkService.js
Fixes https://github.com/nextcloud/spreed/issues/14886
Due to changes in the Talk API, rooms with type `event` cannot be modified after they're created.
To reproduce this issue on `main`, create a new event with a description, and only after writing the description, create a Talk room.
This PR aims to keep backwards compatibility for Nextcloud 30 and lets older versions still set the description if Talk supports it. 
Integrating with a newer Talk version ignores the error that will be returned when trying to set a description on a room type `event` and lets the user proceed. The description will be set in the Talk Event Listener instead.
The `description` API call can be removed as soon as Calendar min support is Nextcloud 31.
> fix(talkintegration): allow room creation with description

- appinfo/info.xml
Taken from the repository readme.
> fix: update app store description

- lib/AppInfo/Application.php
- lib/BackgroundJob/CleanUpOutdatedBookingsJob.php
- lib/Dashboard/CalendarWidget.php
- lib/Db/AppointmentConfig.php
- lib/Db/Booking.php
- lib/Listener/AppointmentBookedListener.php
- lib/Listener/CalendarReferenceListener.php
- lib/Listener/UserDeletedListener.php
- lib/Migration/Version2040Date20210908101001.php
- lib/Migration/Version3000Date20211109132439.php
- lib/Migration/Version3010Date20220111090252.php
- lib/Migration/Version4050Date20230614163505.php
- lib/Notification/Notifier.php
- lib/Profile/AppointmentsAction.php
- lib/Reference/ReferenceProvider.php
- lib/Service/Appointments/AvailabilityGenerator.php
- lib/Service/Appointments/BookingCalendarWriter.php
- lib/Service/Appointments/Interval.php
- lib/Service/Appointments/TimezoneGenerator.php
- lib/Service/JSDataService.php
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
And fix all new issues.
1. Add `#[Override]` annotation to all overriden methods (automatically via `psalter`).
2. Fix scalar type casting issues manually: `InvalidOperand - Cannot process ints and floats in strict binary operands mode, please cast explicitly`
> chore(deps-dev): update psalm to ^6.10.0

- css/fullcalendar.scss
| - | - |
| ![image](https://github.com/user-attachments/assets/3222c288-73fd-4615-943e-2ca7dc96cd58)| ![swappy-20250425_171731](https://github.com/user-attachments/assets/ae8aa36c-9939-479f-8363-62c17ce8c96e) |
> Make event margin be in vw instead of percentage

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Always show alarm unit in pural
- Appointment slots start and end time
- Improve confirmation dialog message
- Undefined calendar
- Fix npm audit
- Do not show attendee actions in viewing mode
- Do not show attendee list when there are no attendees in viewing mode
- Do not show items from deleted calendars in widget
- Enable directory selection in file picker
- Free busy ignoring user's time zone
- Slot header format not respecting user's locale
- Handle timezones with no transitions properly
- Keyboard shortcut modal not being responsive
- Resolve undefined variable error and add logging
- Use folder icon as fallback
> chore(release): v4.7.17

- src/store/calendarObjectInstance.js
* Resolves: #6838
- added logic to remove the organizer once the last attendee is removed
> fix: remove organizer when there are no attendees

- appinfo/info.xml
- package-lock.json
- package.json
- Filter out event type rooms from suggestions
> chore: Release 5.3.0-RC.1

- composer.json
- composer.lock
- Updated composer to php 8.4 max
> chore: update composer to php 8.4 max

- package-lock.json
This audit fix resolves 8 of the total 18 vulnerabilities found in your project.
* [vue-loader](#user-content-vue-loader)
* [vue-template-compiler](#user-content-vue-template-compiler)
* Caused by vulnerable dependency:
* Affected versions: 4.2.0-beta.1 - 6.3.1
* Package usage:
* `node_modules/@nextcloud/dialogs`
* Caused by vulnerable …
> [stable5.3] Fix npm audit

- src/components/Editor/Alarm/AlarmListItem.vue
Resolves: https://github.com/nextcloud/calendar/issues/7090
Checked is for checkboxes not radio selection
> fix: alarm type not binding properly

- .editorconfig
- .github/workflows/e2e-test.yml
- .gitignore
- package-lock.json
- package.json
- playwright.config.js
- tests/javascript/e2e/event.spec.ts
- tests/javascript/e2e/login.ts
Add some basic E2E tests to make sure that the app loads correctly.
> test: add basic e2e tests using playwright

- package-lock.json
This audit fix resolves 11 of the total 21 vulnerabilities found in your project.
* [compression](#user-content-compression)
* [form-data](#user-content-form-data)
* [on-headers](#user-content-on-headers)
* [vue-loader](#user-content-vue-loader)
* [vue-template-compiler](#user-content-vue-template-compiler)
* Caused by vulnerable dependency:
* …
> [stable5.4] Fix npm audit

- src/views/EditSimple.vue
> Fix event modal overflow

- src/components/Editor/AddTalkModal.vue
| - | - |
| <img width="621" height="184" alt="image" src="https://github.com/user-attachments/assets/6952b236-0067-4121-b7bd-1645f9f1a60b" /> |  <img width="623" height="219" alt="swappy-20250821_125110" src="https://github.com/user-attachments/assets/1d298279-286a-49d4-8635-a2a7a9b0104e" /> |
> Fix AddTalkModal styling

- .github/workflows/e2e-test.yml
- package.json
Automated update of the npm and node engines versions according to [Nextcloud standards](https://github.com/nextcloud/standards/issues/5).
> build: update node and npm engines versions

- src/components/Editor/FreeBusy/FreeBusy.vue
This reverts commit d0afc02d1283d3058edc297f288a97e6417bb338.
accidental main push
> Revert "fix(free-busy): make backgound solid for attendees' slots"

- src/views/Proposal/ProposalEditor.vue
- Fixed issue with availability loading overriding currently loaded user data
- Fixed issue with participation required setting the wrong status
> fix: meeting proposals minor ui fixes

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> chore: Version 6.0.0 RC 1

- .github/workflows/php-test.yml
> chore(CI): Adjust testing matrix for Nextcloud 32 on main

- .github/workflows/php-test.yml
Close https://github.com/nextcloud/calendar/pull/7352
> chore(CI): Adjust testing matrix for Nextcloud 32 on stable6.0

- css/global.scss
- src/views/EditSimple.vue
Cancel confirmation dialog wasn't working properly for the simple editor
> fix(EditSimple): cancel confirmation dialog

- src/components/Editor/CalendarPickerHeader.vue
| - | - | 
| <img width="163" height="175" alt="image" src="https://github.com/user-attachments/assets/1b820d02-cc14-465d-945d-2cc7325c1f33" /> | <img width="175" height="181" alt="swappy-20250909_135037" src="https://github.com/user-attachments/assets/10c7c541-44d9-45e7-91dd-6ad52476c39a" /> |
> fix(CalendarPickerHeader): fix alignment

- css/app-full.scss
- src/components/Editor/AvatarParticipationStatus.vue
- src/views/EditFull.vue
- tests/php/unit/BackgroundJob/CleanupOutdatedBookingJobTest.php
Fixes leaking styles into other apps (modal header becoming invisible).
There should be no visual changes inside the Calendar app.
> Merge global styles into SFCs

- package-lock.json
- package.json
Fix https://github.com/nextcloud/calendar/issues/7451
> fix: set vue loader to compatible version

- package-lock.json
- package.json
Update from `2.2.10` to `2.2.11`
> chore: update calendar availability vue

- src/components/AppNavigation/EditCalendarModal/ShareItem.vue
- src/components/Editor/FreeBusy/FreeBusy.vue
- templates/main.php
Corrects unrelated files being modified when running linters on PR's
- Applied cs:fix
- Applied npm run lint:fix
> chore: apply cs:fix and npm lint:fix

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
Manual backport of https://github.com/nextcloud/calendar/pull/7486
> [stable5.5] close view selection menu after click

- appinfo/info.xml
- package-lock.json
- package.json
> chore: Release 6.0.0
