- controller/viewcontroller.php
- js/app/service/calendarservice.js
- templates/part.fullcalendar.php
- tests/unit/controller/viewcontrollerTest.php
Nextcloud9 has a bug, that it doesn't save color, enabled and displayname when sending a MKCOL for a subscription.
This patch mitigates the issue by sending an additional update request when running on Nextcloud 9.
> add workaround to fix webcal creation under Nextcloud9

- js/app/controllers/editorcontroller.js
- templates/editor.popover.php
- templates/editor.sidebar.php
please review @jancborchardt @eppfel @raghunayyar 
fixes one issue in https://github.com/nextcloud/calendar/issues/72
> editor: show calendar selection only if more than one writable calendar is available

- css/app/eventdialog.css
- js/app/controllers/editorcontroller.js
- templates/editor.sidebar.php
please review @jancborchardt @eppfel @raghunayyar
> introduce details tab in sidebar

- css/app/calendarlist.css
Fix #119, please review @moy @tcitworld @nextcloud/calendar :)
Before:
After (all full-hour grid lines are darker #eee, just like the row lines in Files, user management and elsewhere):
> border styles for grid, highlight full-hour horizontal lines, fix #119

- js/app/directives/fullCalendarDirective.js
remove eventLimit as of https://github.com/nextcloud/calendar/issues/134#issuecomment-254757018
with the recent fixes made to the calendar list, the calendar list won't scroll together with the calendar view.
> remove eventLimit

- js/app/controllers/calcontroller.js
- js/app/directives/fullCalendarDirective.js
- js/app/models/fcEventModel.js
- tests/js/unit/models/fcEventModelSpec.js
fixes #16 
please review @nextcloud/calendar 
This fixes a longstanding issue, that caused users to not be able to drag and drop events between the all-day grid and the time-grids in day and week view.
Test this by dragging and dropping events from all-day to time grid and vice versa.
> fix dropping between grid and allday

- controller/contactcontroller.php
- css/app/eventdialog.css
- js/app/controllers/attendeecontroller.js
- templates/part.eventsattendees.php
- tests/php/controller/contactcontrollerTest.php
I would like to have some `&hellip;` at the end when they're truncated, but `uib-typeahead` doesn't seem to accept ternaries directly, so I guess we need a full filter just for this.
Fixes #45
> show email for attendee

- js/app/controllers/importcontroller.js
- js/app/models/ImportFileWrapperModel.js
- templates/part.import.dialog.php
fixes #194 
please review @tcitworld @nextcloud/calendar
> import empty calendars

- css/app/calendarlist.css
Not a core issue since it's correctly aligned on other apps. I'm sure there's better ways to fix this though.
cc @georgehrke @raghunayyar 
Before
After
> Quick and dirty fix for entry menu align

- js/app/controllers/calendarlistcontroller.js
- js/app/factory/calendarFactory.js
- js/app/models/calendarmodel.js
- js/app/models/webcalModel.js
- js/app/service/calendarService.js
- tests/js/unit/controllers/calendarlistcontrollerSpec.js
- tests/js/unit/factory/calendarFactorySpec.js
- tests/js/unit/models/calendarModelSpec.js
- tests/js/unit/services/calendarServiceSpec.js
move `update`, `delete`, `share`, `unshare`, `publish` and `unpublish` straight into the calendar respectively the webcal object to use these functions without having the CalendarService as dependency everywhere
this will come very handy at implementing:
- https://github.com/nextcloud/calendar/issues/24
- https://github.com/nextcloud/calendar/issues/31
- https://github.com/nextcloud/calendar/issues/42
> move some calendarService calls into Calendar and subscription model

- appinfo/info.xml
Didn't find the app on NC11 because I looked into the 'Office & text' category. IMO it should be listed there too like contacts https://github.com/nextcloud/contacts/blob/master/appinfo/info.xml and mail https://github.com/nextcloud/mail/blob/master/appinfo/info.xml
> app should be listed in the office category too

- css/app/calendarlist.css
Reverts nextcloud/calendar#212
After https://github.com/nextcloud/server/pull/2545
> Revert "Quick and dirty fix for entry menu align" and fix padding

- css/app/eventdialog.css
- js/.jshintrc
- js/app/controllers/editorcontroller.js
- templates/editor.popover.php
- templates/editor.sidebar.php
please review @nextcloud/calendar @eppfel
> make title, description and location autoresizing textareas

- css/app/eventdialog.css
- js/app/directives/datetimepickerDirective.js
please review @nextcloud/calendar @eppfel
> disable all-day when clicking on all-day

- js/app/controllers/importcontroller.js
please review @nextcloud/calendar 
fixes #245 
try to import a broken calendar
master just stops with the progress bar at some point
this fixes the error and shows a proper error message.
Don't know when this regression was introduced
> properly catch errors while importing

- js/app/models/veventModel.js
- tests/js/unit/models/veventModelSpec.js
fixes #251 
please review @tcitworld
> replace TRIGGER:P with TRIGGER:P0D

- Makefile
- controller/viewcontroller.php
- js/bower.json
- templates/main.php
- tests/php/controller/viewcontrollerTest.php
Since version 1.4.1 we added autoresizable inputs for title, description and location.
Autoresize was only added with Nextcloud 11
=> ship autosize with calendar and include it if version number is lower than 11
> ship autosize

- tests/bootstrap.php
Some unit tests fail, because they test code that uses the template engine. Some parts of Nextcloud's template engine use static code to access `IRequest`. Therefore we can't properly inject a correct `IRequest` object and use this hack.
> fixes unittest that fails recently

- js/app/directives/datetimepickerDirective.js
fixes #345 
please review @tcitworld @skjnldsv 
before:
after:
> show proper am/pm labels next to timepicker

- css/app/calendarlist.css
- js/app/directives/avatarDirective.js
- templates/main.php
- templates/part.calendarlist.item.php
> add avatar to sharing dropdown

- css/app/calendar.css
> increase font-size of fullcalendar labels

- js/app/controllers/calcontroller.js
Changed color of current day, to be more visible on screens with bad contrast (from #ffc to #ffa)
> Changed highlighting of the current day to be more visible

- css/app/eventdialog.css
- templates/editor.popover.php
- templates/editor.sidebar.php
fixes #72 
Before = Blue
After = green
> fix date timepicker layout in events editors

- js/app/models/veventModel.js
- tests/js/unit/models/veventModelSpec.js
fixes #142 
test will fail because of what I think is a bug in ical.js. 
Will send them a pr.
> fix handling of recurrence ID

- css/app/calendarlist.css
- templates/part.calendarlist.item.php
Same as https://github.com/nextcloud/server/pull/4337, but for the share icons in the Calendar.
Please review @kumzugloom @Pommesumdreher @MariusBluem @Bullnados @GetBoz @georgehrke @MariusBluem :)
> Fix AdBlock blocking share icon

- css/app/eventdialog.css
> fix click on disabled timeinput in firefox in sidebar

- css/app/calendarlist.css
fixes #314
The left sidebar from NextCloud use a right border in #ebebeb _(grey)_. The grid use the color #f8f8f8 _(darker grey)_. I changed the color to #ebebeb to improve the visibility. Maybe this is a little bit better to see the borders.
Before:
After:
> Refer to #314 - Make grid darker

- css/app/datepicker.css
some change in the core styles messed with out datepicker
before:
after:
> fix datepicker layout for Nextcloud 12

- js/app/controllers/calendarlistcontroller.js
we replaced `publishurl` and `publicurl` with a single `publicToken`
Therefore clicking on a newly created sharing link will take you to a 404 page.
This PR fixes this.
> fix clicking a newly created public share

- css/app/eventdialog.css
> add box sizing to fix date timepicker layout for nc 9,10,11

- css/app/eventdialog.css
Fix double scrollbar in advanced Editor. The height is not correct. It shows two scrollbars and a half button in NC12.0.0 (calendar Version 1.5.3).
Before:
After:
> Fix double scrollbar in advanced editor

- templates/part.publicinformations.php
It used to be IFRAME https://www.w3.org/TR/1999/REC-html401-19991224/present/frames.html#h-16.5
for reasons unknown, but now it is "iframe"
https://www.w3.org/TR/2014/REC-html5-20141028/embedded-content-0.html#the-iframe-element
Added something to start of sentence to avoid issue with Iframe or iframe.
> Spelling: iframe

- controller/emailcontroller.php
fixes #427 
I didn't find a way to make the calendar name bold yet :/
> use NC12 IEMailTemplate for fancier emails

- templates/public.php
Fix for public shared calender (header buttons on the right side) #509
> Fix for nc11 (public share header buttons)

- css/app/datepicker.css
- js/app/controllers/datepickercontroller.js
- templates/part.datepicker.php
- tests/js/unit/controllers/datepickercontrollerSpec.js
**Proposition for this issue:** https://github.com/nextcloud/calendar/issues/513
Add grey color to the week-ends and yellow color to the current day (today).
**Bug fix:** when changing month the selected day was the same as the current day. For example if the current day is 10th of July, when I changed month it was focusing the 10th of August.
This is fixed, now the first day of the month and the week is selected.
**Tests:** This pull-requests adds the missing tests on the DatepickerController.
> Add colors datepicker, focus day when navigating

- js/app/controllers/calendarlistcontroller.js
- js/app/models/calendarmodel.js
- js/app/service/calendarService.js
- templates/part.calendarlist.item.php
- tests/js/unit/models/calendarModelSpec.js
fixes #459 
(also empties the search field after creating new share)
> show displayname instead of userid after creating a new user share

- controller/viewcontroller.php
- js/app/controllers/calendarlistcontroller.js
- js/config/config.js
- templates/part.calendarlist.item.php
- templates/part.fullcalendar.php
- tests/php/controller/viewcontrollerTest.php
Fixes https://github.com/nextcloud/calendar/issues/525 on client side.
Please complete the tests, karma is long time no see.
> Disable publishing when Sharing by link is disabled

- js/gulpfile.js
I added the css files in the watch files to allow a dev to modify css without building by hand.
**Proposition:** I added a task lint that lints the css and the js files, but I don't think it is useful to lint in the watch task. Linters are long, while you are developing it is frustrating to wait for the build task... The linters could be a precommit hook instead.
> Watch css files and remove lint from watch task

- js/app/models/simpleEventModel.js
I'm committing this in behalf of @georgehrke, thanks for providing the fix.
> Fix patch logic: Properly remove parameter if it no longer exists

- js/app/service/mailerservice.js
stupid me changed names in Emailcontroller in https://github.com/nextcloud/calendar/commit/5aefb45ad4e0fcc533e89c47acfea13de6b26323 but didn't change property names in javascript 
required for 1.5.4
> fix property names in MailerService

- appinfo/routes.php
- js/app/service/autocompletionservice.js
- tests/js/unit/services/autocompletionServiceSpec.js
This prevents including the search term in webserver logs.
It will also break all clients using this API endpoint, which is
fine, as non-OCS APIs are meant to be private and shouldn't be used
by 3rdparty apps.
> autocompletion: Use 'POST' instead of 'GET' method to access API

- js/app/directives/fullCalendarDirective.js
> add minimum height for events in agenda View

- css/app/eventdialog.scss
> fix height of summary input in event editor popover

- tests/php/controller/proxycontrollerTest.php
Update only affected some classes used for testing in the ProxyControllerTest, ProxyController is unaffected by updated Guzzle lib.
> fix ProxyControllerTest, issues caused by updated Guzzle lib in the server

- templates/editor.sidebar.php
In response to issue #675, this doubles the size of the text area input for the event description by increasing the text area to two rows.
Before:
After:
> Double the height of the description text area (issue #675)

- js/app/controllers/editorcontroller.js
> always show the calendar selector in the editor for read-only calendars

- controller/viewcontroller.php
- templates/main.php
This fixes the public page layout for Nextcloud 14. Before this PR calendar was using public instead of base as layout value, which isn't equal with NC14 anymore.
I didn't move it to the newly introduced PublicTemplateResponse, since calendar still supports versions below 14.
Once 14 is a minimal requirement, we should move the public page with header to the new response.
Requires https://github.com/nextcloud/server/pull/10530
> Fix public layout rendering on Nextcloud 14

- css/app/calendarlist.scss
Fixes #730, tested with Firefox 61.0.1 and Chromium 68.0.3440.84 on Nextcloud 13
> "Settings & Import" no longer covers bottom calendar.

- css/app/calendar.scss
Closes #876
I didn't test on NC < 14, but it should be fine since it only puts back
old sidebar behaviour before nextcloud/server#10218
> Quickfix for sidebar on NC14

- controller/viewcontroller.php
Fixes #169 (will probably require NC 15 though, I don't think https://github.com/nextcloud/server/pull/11878 can be backported)
> Add @NoSameSiteCookieRequired to the publicIndexForEmbedding endpoint

- css/app/calendarlist.scss
Add circular highlight based on Primary theme colors as discussed in pull request #818
> Add theme color highlight to Today date

- controller/contactcontroller.php
- tests/php/controller/contactcontrollerTest.php
Fix issue #933 
When auto-completing an event location from a contact address,
render the address as a single line comma separated list of fields,
instead of a multi-line address.  This works better in the UI, and
works better in ICS files provided to mail clients like Thunderbird/Lightning
and Google/Calendar.
Signed-off-by: Brad Rubenstein <brad@wbr.tech>
> Provide autocompletion addresses as a single line.

- css/app/calendarlist.scss
- css/app/datepicker.scss
- js/.stylelintrc
Follow up to #1043 
(latest release, without #1043 and round buttons)
> Fix datepicker alignment

- js/app/controllers/calendarlistcontroller.js
- js/app/factory/calendarFactory.js
- js/app/models/calendarmodel.js
- js/app/service/calendarService.js
- js/config/config.js
- templates/part.calendarlist.item.php
- tests/js/stubs/app.js
The possibility to share a calendar with a circle is implemented in this commit and in commit e534c55 in nextcloud core.
There is a PR there: 
https://github.com/nextcloud/server/pull/6512
I've tested this functionality using nextcloud 12.
> Allow a calendar to be shared with circles.

- css/app/calendarlist.scss
- templates/part.calendarlist.item.php
In order to improve the understanding of calendars being enabled/disabled.
For v2 let's use checkboxes instead. https://github.com/nextcloud/calendar/issues/904#issuecomment-444225498
|Before|After|
|---|---|
|![](https://framapic.org/j4vInjeusP29/XPM0xunQtjHW.png)|![](https://framapic.org/QQMzmwywWZPb/veJ4MCGLWbQ9.png)|
> Always show border on calendar item

- .travis.yml
```
error is-wsl@2.1.0: The engine "node" is incompatible with this module. Expected version ">=8".
```
> Update NodeJS in CI from 6 to 10

- CHANGELOG.md
- appinfo/info.xml
> Calendar 2.0.0 beta1

- src/views/Calendar.vue
- webpack.common.js
fixes #1569 
Summoning our Webpack export @skjnldsv 😉 
This doesn't look right to me:
Master:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
calendar.js (1.99 MiB)
```
This branch:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
calendar.js (2.18 MiB)
```
I would have expect it to get much smaller when loading the locales dynamically 🤔
> load FullCalendar locale dynamically

- src/components/AppNavigation/AppNavigationHeader.vue
- src/views/Calendar.vue
fixes #1586 
Ideally we should setup a tool like puppeteer and have travis generate screenshots for us, so we can easily spot regressions like this one. #1596
Logged in:
Public:
> Do not show New event button on public page

- __mocks__/@nextcloud/l10n.js
- __mocks__/@nextcloud/router.js
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/AppNavigation/Settings/ImportScreenRow.vue
- src/components/Editor/IllustrationHeader.vue
- src/components/Shared/TimezoneSelect.vue
- src/mixins/EditorMixin.js
- src/models/calendar.js
- src/store/calendars.js
- src/utils/color.js
- src/utils/date.js
- src/utils/illustration.js
- src/utils/recurrence.js
- src/utils/timezone.js
- src/views/Calendar.vue
- tests/javascript/unit/utils/color.test.js
- tests/javascript/unit/utils/date.test.js
- tests/javascript/unit/utils/illustration.test.js
- tests/javascript/unit/utils/recurrence.test.js
- tests/javascript/unit/utils/router.test.js
- tests/javascript/unit/utils/settings.test.js
- tests/javascript/unit/utils/timezone.test.js
Replaced `getRandomColor` and `getDefaultColor` with `uidToColor`.
Wrote unit tests for most modules inside `utils/`
> Remove deprecated color utils, replace with uidToColor, add tests

- src/mixins/EditorMixin.js
- src/models/calendarObject.js
- src/router.js
fixes #21 
Allows to link to a specific event without knowing a specific recurrence-id.
Opening `/:view/:date/edit/sidebar/:object/next` will automatically forward to `/:view/:date/edit/sidebar/:object/{closest occurrence}`
> Link to event

- src/views/Calendar.vue
> Bring back now indicator in calendar-grid

- package-lock.json
- package.json
- src/main.js
As per https://babeljs.io/blog/2019/03/19/7.4.0#migration-from-core-js-2
> Replace babel/polyfill with core-js/stable

- src/components/Shared/DatePicker.vue
This fixes the noticeable delay when clicking the all-day checkbox.
It was caused by wrapping the Popover component inside an v-if.
On every checkbox toggle, it caused a massive stack of creating elements / destroying elements.
Related to #1576 #1570
> Fix delay when clicking all-day checkbox

- package-lock.json
- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/Settings/ImportScreen.vue
- src/store/calendarObjects.js
Reported at Transifex.
Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>
> l10n: Triple dot ellipsis

- css/app-navigation.scss
- src/components/AppNavigation/CalendarList/CalendarListItem.vue
> Remove the Shared label, because it is taking up too much space in the apps-navigation

- src/components/Editor/Alarm/AlarmListItem.vue
#1576
> The dropdown to edit the reminder is quite confusing … there’s 2 sets of 2 radio buttons each, but it looks like 1 list of 4 radio buttons. The "Edit reminder" should not switch anything in the menu but rather edit the view?
> Restructure menu for reminders

- src/components/AppNavigation/Settings.vue
> Prevent double escape of ampersand for Settings title

- src/fullcalendar/eventLimitText.js
- src/views/Calendar.vue
- tests/javascript/unit/fullcalendar/eventLimitText.test.js
Before:
After:
Prevents one week from taking over the entire month view.
> Bring back event-limit

- lib/Controller/ViewController.php
Try to access the calendar directly without logging in first.
It will throw a 500, because $userId is null and not a string.
This PR allows a null $userId in the constructor.
Authentication check is run before calling `index`, so we don't need to check for null there.
Nullable syntax is available on all supported PHP Versions.
> Make userid nullable

- src/views/Calendar.vue
Fixes:
```
main.esm.js:379 Use of eventRender as an event is deprecated. Please convert to a prop.
```
> Convert eventRender from event to prop

- src/store/calendarObjectInstance.js
- Open the new event editor
- pick a new end-date with date-picker
master:
- end is one day early
this branch:
- end is correct
> Always turn DTEND exclusive

- src/fullcalendar/windowResize.js
- src/views/Calendar.vue
- tests/javascript/unit/fullcalendar/windowResize.js
On master, if you resize a window to be bigger, fullcalendar properly scales up.
If you make the window smaller (height wise), fullcalendar will not size down.
This pull-request introduces a windowResize method that handles it instead of relying on the fullcalendar "parent" setting.
> Handle window resize on our own instead of relying on fullcalendar

- src/components/Shared/DatePicker.vue
- src/components/Shared/TimePicker.vue
fixes #1756 
fixes #1621
fixes #1144
Automatically turns:
- `from 17021990` to `from 17.02.1990`
- `from 17.02.1990 at 11` to `from 17.02.1990 at 11:00`
- `from 17.02.1990 at 1155` to `from 17.02.1990 at 11:55`
And nonetheless, actually allows entering stuff manually 🙈
> Parse user-input in DatePicker using moment to allow less strict parsing

- css/global.scss
On Master, Firefox has a vertical scrollbar, although all content is visible.
This pull-request disables vertical scrolling.
> Hide vertical scroll bar in Firefox

- src/router.js
If you configure URL rewrite, `generateURL` will by default always skip the index.php
Nonetheless, you can still open the URL with the `index.php`
If you access the URL with `index.php`, the router base will be wrong and routing will break:
http://nextcloud.local/index.php/apps/calendar/p/tsQnYebgwxrF67QK/dayGridMonth/now is broken
http://nextcloud.local/apps/calendar/p/tsQnYebgwxrF67QK/dayGridMonth/now works
This branch double checks for index.php and disables rewriting if there is one.
> Set no rewrite for generateUrl, in case URL contains index.php despite configured rewrite

- lib/Controller/ViewController.php
- src/utils/router.js
- tests/javascript/unit/utils/router.test.js
- tests/php/unit/Controller/ViewControllerTest.php
... e.g. because the app was disabled during update
fixes #1831
> replace old views in case migration didn't run correctly

- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
Copy embed Code should use `/embed/`, not `/e/`
https://github.com/nextcloud/calendar/blob/master/appinfo/routes.php#L37
https://github.com/nextcloud/calendar/blob/master/src/router.js#L98
fixes #1861
> Fix generated embed code

- css/fullcalendar.scss
fixes #1905 
fixes missing CSS var.
Does not change anything about the design.
Without the explicit background-color, fullcalendar is by default transparent, so the visible color was the main background-color anyway.
> Fix undefined css var

- src/utils/illustration.js
This commit adds "Gym" as a word to show working out illustrations,
as well as adds translations to Afrikaans and Esperanto.
Adds a word to match to working out events.
Fixes #1888
> Add "Gym" as keyword for working out illustrations

- src/views/EditSidebar.vue
> Properly localize subTitle of AppSidebar

- package-lock.json
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
Related to https://github.com/nextcloud/calendar/issues/1837#issuecomment-580059883
|![before](https://user-images.githubusercontent.com/1250540/73458714-fd696980-4375-11ea-9e28-6e5470a0ad8b.jpg)|![after](https://user-images.githubusercontent.com/1250540/73458717-ff332d00-4375-11ea-9185-4a5721704242.jpg)|
> Add hint to new calendar dropdown that subscriptions are read-only

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
The URI to the DAV resource has not been url-decoded.
Fixes #1893
> Fixed #1893

- src/utils/date.js
- tests/javascript/unit/utils/date.test.js
fixes #1944 
This fixes an issue with parsing the first day parameter.
The problem is that `new Date()` parsed the parameter as UTC, because it looked like an ISO string.
Resulting in:
`const d1 = new Date('2020-02-16')`
`Sat Feb 15 2020 16:00:00 GMT-0800 (Pacific Standard Time)`
This PR parses the first day parameter manually.
Turning `2020-02-26` into `Wed Feb 26 2020 00:00:00 GMT-0800 (Pacific Standard Time)`
> Fix parsing of First day parameter

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
Preparing the 2.0.2 release ...
I would still like to include the following in 2.0.2:
> Release 2.0.2

- src/models/calendar.js
To reproduce, just create a group with non-latin characters.
e.g. `Федот Щербаков`
Share calendar with that group and reload.
On Master the calendar won't load anymore,
With this branch, it will work just fine.
fixes #1894
> Unlike other hrefs, Sharee URIs are not encoded by the server .... Properly handle that

- lib/Controller/PublicViewController.php
This must have gotten lost during vue rewrite.
> Re-add @NoSameSiteCookieRequired to embedding route

- css/app-sidebar.scss
- src/views/EditSimple.vue
fixes #1925 
fixes #1934
fixes #2109 
There is still room for some improvement, but this makes sure that the popover will never be outside the current viewport.
> Make sure popover editor does not leave boundaries

- css/fullcalendar.scss
- src/fullcalendar/eventSourceFunction.js
- tests/javascript/unit/fullcalendar/eventSourceFunction.test.js
fixes #1931 
Having multi-line summaries in the calendar-grid can cause issues, where fullcalendar only shows "+x more" for all events in the same row, although there is enough space to display the non-multiline ones of them.
Since we don't allow multiline Summaries in titles anymore, this PR makes sure that we do not show multiline summaries in the calendar-grid. New lines are replaced with a single space.
Furthermore, this PR adds a proper ellipsis for long titles:
|![1E11D6E5-3D5A-4006-B793-762EBEA2005C](https://user-images.githubusercontent.com/1250540/78883793-43b80480-7a5a-11ea-90a1-26b881460f08.png)|![B34456EE-2B51-4D36-B012-B66C74C55DE0](https://user-images.githubusercontent.com/1250540/78883832-50d4f380-7a5a-11ea-87d3-1fbfe2980386.png)|
> Do not allow multiline summaries in Calendar-grid

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
> Release 2.0.3

- css/fullcalendar.scss
- lib/Controller/PublicViewController.php
- lib/Controller/SettingsController.php
- lib/Controller/ViewController.php
- package-lock.json
- package.json
- src/components/AppNavigation/Settings.vue
- src/fullcalendar/eventClick.js
- src/fullcalendar/eventRender.js
- src/fullcalendar/eventSourceFunction.js
- src/store/calendars.js
- src/store/fetchedTimeRanges.js
- src/store/settings.js
- src/utils/router.js
- src/views/Calendar.vue
- templates/main.php
- tests/javascript/unit/fullcalendar/eventClick.test.js
- tests/javascript/unit/fullcalendar/eventRender.test.js
- tests/javascript/unit/fullcalendar/eventSourceFunction.test.js
- tests/javascript/unit/utils/router.test.js
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
This is a start to address issue #28 . Feedback is welcome.
> First prototype to show tasks on calendar and redirect to tasks app

- css/app-settings.scss
- package-lock.json
- package.json
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderTodayButton.vue
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/ShortcutOverview.vue
- src/main.js
Related to #157 
| Action | Shortcut |
| Previous time-range | p or k |
| Next time-range | n or j |
| Today | t |
| New event | c |
| Day view | 1 or d |
| Week view | 2 or w |
| Month view | 3 or m |
Possible further shortcuts:
| Action | Shortcut |
| List #402 | 4 or l |
| Search #8  | / |
| Refresh #31 | r |
I do not want to add a shortcut for deleting an event, as long as we don't provide an undo.
> Add Keyboard shortcuts

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
With this PR also circles exactly matching the search query are correctly shown.
Fixes #2220
> Also show circles exactly matching query

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
fixes:
```
[DOM] Found 2 elements with non-unique id #users-groups-search: (More info: https://goo.gl/9p2vKq) 
```
We are not using the Id anywhere, not even for a label....
> Remove id for CalendarListItemSharingSearch component

- src/utils/timezone.js
- tests/javascript/unit/utils/timezone.test.js
Some timezones have more than one `/` in their name, and only the first part was being used.
|![nextcloud_tz_before](https://user-images.githubusercontent.com/2197836/83299499-927e5100-a1f6-11ea-951c-365ff8c7bcf7.png)|![nextcloud_tz_after](https://user-images.githubusercontent.com/2197836/83299505-97430500-a1f6-11ea-912e-318dfc5470e5.png)|
> Fix timezone names

- src/components/Shared/DatePicker.vue
- src/components/Shared/TimePicker.vue
- src/utils/localization.js
fixes #2174
fixes first day of week
fixes title of month in header
|![datepicker_before](https://user-images.githubusercontent.com/1250540/82889056-79517800-9f4a-11ea-87af-c3260642bc17.png)|![6C199988-3F02-4778-BEB6-A6E8C03DC456](https://user-images.githubusercontent.com/1250540/82891042-68eecc80-9f4d-11ea-9e50-b3260d16e0cf.png)|
> Fix Datepicker localization

- css/app-sidebar.scss
- src/components/Shared/CalendarPickerOption.vue
fixes #2324 
|![before](https://user-images.githubusercontent.com/1250540/84120947-c9ded000-aa36-11ea-9f09-0a5196af3122.png)|![after](https://user-images.githubusercontent.com/1250540/84120851-addb2e80-aa36-11ea-99a2-b0cf439babc7.png)|
> Fix handling of long calendar names in calendar-picker

- src/fullcalendar/eventSourceFunction.js
Follow up to #1798 
Tasks might not always have a `PERCENT-COMPLETE` so tasks with a `STATUS` of  `COMPLETED` should also get marked as such.
Add a task with the following data:
```
VERSION:2.0
PRODID:-//Nextcloud Tasks v0.13.1
BEGIN:VTODO
UID:f4b456d3-4c53-47a9-ae99-4ffdc2817715
CREATED:20200613T224342
LAST-MODIFIED:20200614T111359
DTSTAMP:20200614T111359
SUMMARY:fsdf
DUE:20200620T230000
DTSTART:20200613T230000
COMPLETED:20200614T111359
STATUS:COMPLETED
END:VTODO
END:VCALENDAR
```
> Also mark tasks as done when STATUS is set to COMPLETED

- css/fullcalendar.scss
Makes it much more obvious which date corresponds to which cell – we already do this in the week view:
Before | After
-|-
> Center date in month view cell

- src/models/rfcProps.js
- tests/javascript/unit/models/rfcProps.test.js
It's Canceled in american english, which is our source language
https://www.oxfordlearnersdictionaries.com/definition/american_english/cancel#cancel__9
> Cancelled -> Canceled

- src/fullcalendar/eventSource.js
- tests/javascript/unit/fullcalendar/eventSource.test.js
It's `readOnly`, not `isReadOnly`:
https://github.com/nextcloud/calendar/blob/80bf6f00115b872394211cc1c5e59ec695881744/src/models/calendar.js#L59
> Fix read-only property of fullcalendar event sources

- webpack.common.js
Also adds `symlink: false`, which is part of our standard conf: https://github.com/nextcloud/webpack-vue-config/blob/master/webpack.js#L65
> Remove unused webpack alias config

- .github/workflows/php-test.yml
- lib/AppInfo/Application.php
- lib/Dashboard/CalendarWidget.php
- lib/Service/JSDataService.php
- package-lock.json
- package.json
- src/dashboard.js
- src/views/Dashboard.vue
- tests/php/unit/Dashbaord/CalendarWidgetTest.php
- tests/php/unit/Service/JsDataServiceTest.php
- webpack.common.js
| No events | No events today | Events | List with ToDo |
|:---------:|:------:|:-------:|:--------:|
|![F1BAAB3B-17E6-4D4E-99D1-D725AEB2E2C0](https://user-images.githubusercontent.com/1250540/90607837-12b6c000-e202-11ea-95b4-76c2300ac214.png)|![5E4359A5-5180-40B9-AE19-5B79B8085847](https://user-images.githubusercontent.com/1250540/90607099-0c741400-e201-11ea-8475-19ecf6fc7a5d.png)|![95FB5E86-F5E9-4F43-8F16-6F1EB67786D0](https://user-images.githubusercontent.com/1250540/90606792-97084380-e200-11ea-90b8-5a2da45fc8fe.png)|![95C015E8-7EA2-413E-B9B3-C0BD94CB5A14](https://user-images.githubusercontent.com/1250540/91591498-4cec3400-e95d-11ea-937f-c3a6a44f981c.png)|
This PR implements a basic dashboard widget for Nextcloud 20.
> Dashboard widget

- src/components/CalendarGrid.vue
Regression introduced by #2498 
At the time the debounce function is called here, this refers to the object, not the instantiated Vue instance.
Hence we can't use arrow functions here.
> Fix saving current view

- CHANGELOG.md
- appinfo/info.xml
- package.json
Requires:
- https://github.com/nextcloud/calendar/pull/2523
Would be nice to have:
- https://github.com/nextcloud/calendar/pull/2528
- https://github.com/nextcloud/calendar/pull/2476
> Release 2.1.0

- src/views/Dashboard.vue
> Dashboard: include all-day events from today

- src/mixins/EditorMixin.js
Slipped through in https://github.com/nextcloud/calendar/pull/2528
Without that line, it just tries to load the event without waiting until calendars are loaded.
It fails, since it can't find the calendar.
> Fix opening events from search

- css/app-sidebar.scss
> allow some margin for organizer hint in attendee list

- src/store/calendarObjectInstance.js
This PR makes sure that events edited in the Nextcloud Calendar webinterface have their recurrenceRule.until timestamp set to UTC in order to be compliant with [RFC 5545, section 3.3.10](https://tools.ietf.org/html/rfc5545#section-3.3.10) (for details see #2675 )
Please give a brief summary of your changes and which issue they address.
Fixes #2675 
1. Create a timezone aware recurring event with an end date
2. Retrieve the calendar in ical form, e.g. through the `/remote.php/dav/calendars/<principal>/<calendar>/?export` endpoint
3. Verify that the UNTIL timestamp is timezone-aware and in UTC (i.e. ends in `Z`)
None
- N/A
> Fix #2675: RRULE UNTIL must be in UTC if DTSTART is timezone-aware

- src/components/CalendarGrid.vue
- src/directives/autosize.js
Since v2.1.0 (see https://github.com/nextcloud/calendar/pull/2498/commits/78132a974efdfba1f0554895bfd673ea710ce371 and https://github.com/nextcloud/calendar/pull/2528/commits/59519d2f42bddb2c0588e2e20b66314b27f059f7) `ResizeObserver` was used unconditionally, which caused the Calendar to fail to load and show a blank page on some older [browsers without support for it](https://www.caniuse.com/mdn-api_resizeobserver). `Now ResizeObserver` is used only when supported.
`ResizeObserver` ensures that the calendar grid is properly sized when the navigation bar and sidebar are opened and closed. It also ensures that the text areas are properly sized when shown in the sidebar.
Given that they are mostly "cosmetic" issues and that they should not affect many users no fallback was added for those …
> Fix blank page on browsers without support for ResizeObserver

- src/models/calendarShare.js
When a calendar is shared to a group named "Route#44" it was displayed as "Route%2344".  Companion PR for https://github.com/nextcloud/server/pull/24515
> fixes encoded display of names that contain a special character

- CHANGELOG.md
I've added an `h1` title and I've updated all the releases that were using `h1` to `h2`.
Hopefully, this would enable the "changelog" tab in the application details like we can see on other apps such as Contacts, Mail, News, etc...  
I've based my changes on Contacts' changelog: https://github.com/nextcloud/contacts/blob/master/CHANGELOG.md
Here are screenshots of Calendar vs Contacts apps details. See the "Details" and "Changelog" tabs for Contacts (in French, sorry):
Calendar | Contacts
--|--
This is a "meta" change, the app is still the same.
Nothing to test.
No UI changes.
> Cleaned up the changelog

- package-lock.json
- package.json
- src/fullcalendar/interaction/eventClick.js
Open task entries that are exposed by deck inside of the deck app by emitting an event that can be handled by apps
Requires https://github.com/nextcloud/deck/pull/2683
> Let apps handle clicks on todo entries

- composer.json
- composer.lock
I noticed in https://github.com/nextcloud/calendar/pull/2805 that this will blindly install pre-php8 libraries that are otherwise not compatible and thus cause trouble later on. CI already checks against all supported versions of php, there is no need to overwrite this.
> Do not override the php version

- .github/workflows/php-test.yml
- .gitignore
- composer.json
- composer.lock
- lib/Controller/PublicViewController.php
- lib/Controller/ViewController.php
- phpunit.unit.xml
- tests/php/unit/Controller/ContactControllerTest.php
- tests/php/unit/Controller/EmailControllerTest.php
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/SettingsControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
- tests/php/unit/RepairSteps/CurrentViewNameRepairStepTest.php
- tests/php/unit/Service/JsDataServiceTest.php
* Drops `christophwurst/nextcloud` as that is only required for static analysis, which there is none here at the moment
* Updates phpunit to the lastest available version (through `christophwurst/nextcloud_testing` and adjust the test code for this, mainly the deprecated `$this->at(...)` usage that throws warnings now
* Downgrades phpunit dynamically for php7.2 as the latest phpunit support php8 but not 7.2, there is no release that supports 7.2-8.0 unfortunately
* Does a weird move on `nextcloud/3rdparty`: the php-parser conflicts with the one from phpunit, hence for the stable20 tests we update that package there. This is super ugly, but I don't know any other way to resolve that. Phpunit throws errors otherwise. AFAIK the php-parser is not really used in Nextcloud except for unit tests …
> Test against php8

- src/views/Dashboard.vue
For Issue:
https://github.com/nextcloud/server/issues/22864
- "Upcoming events" button "Create new event" button is not 44px min
1. Compile new Calendar Module
2. Replace old Calendar JS Files to new Compiled JS Files in Nextcloud Server
3. Start Nextcloud Server
|![before](https://user-images.githubusercontent.com/64197016/101017306-33651480-356a-11eb-9505-6269b56a4c81.png)|![after](https://user-images.githubusercontent.com/64197016/101017362-4546b780-356a-11eb-9036-22b8ce6b5d65.png)|
> 'Create new event' spacing is now like 'Set up an account'

- src/fullcalendar/localization/localeProvider.js
Fixes compatibility up to at least Firefox 60 (well, at least loading the initial screen).
Closes #2757 (and probably a lot of similar issues).
> Change String#replaceAll with String#replace and the g switch

- package-lock.json
- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
- src/services/caldavService.js
This allows searching for exact matches of email addresses when sharee enumeration is off. Otherwise the server will always filter out the entries where the display name is not identical to the search string.
So to test you create a system user with an email address, disable sharee enumeration and try to share a calendar with that user. On master you won't get a result, here you will.
> Search DAV for principal as display name OR email

- src/components/Editor/FreeBusy/FreeBusy.vue
Signed-off-by: Christoph Wurst <christoph@winzerhof-wurst.at>
As a user I would like to see the name of the day when I browse the free/busy view, mostly to prevent picking weekend dates for business meetings.
Open free/busy
In case you changed, added or removed UI elements, please provide a set of before / after screenshots:
|![Bildschirmfoto von 2021-02-10 16-05-38](https://user-images.githubusercontent.com/1374172/107528376-0d876c00-6bba-11eb-923d-7275c1000913.png)|![Bildschirmfoto von 2021-02-10 16-04-03](https://user-images.githubusercontent.com/1374172/107528406-12e4b680-6bba-11eb-8bb4-c8d53053a708.png)|
@jancborchardt as discussed
> Show the name of the day in the free/busy view

- src/fullcalendar/eventSources/freeBusyEventSourceFunction.js
- src/fullcalendar/eventSources/freeBusyFakeBlockingEventSource.js
`rendering` was used in v4, in v5 `display` changes the way how events
are rendered. This caused blocks in the UI that then made the free/busy
schedule grow vertically and so became less useful.
Ref https://fullcalendar.io/docs/upgrading-from-v4
Ref https://fullcalendar.io/docs/background-events
Possibly a regression of https://github.com/nextcloud/calendar/pull/2498, for comparison here's the original PR for free/busy with a screenshot: https://github.com/nextcloud/calendar/pull/1731
Fixes # (issue)
1. Create an event
2. Add at least one attendee
3. View the free/busy UI
In case you changed, added or removed UI elements, please provide a set of before / after screenshots: …
> Fix fullcalendar v5 options for background events

- Makefile
The ci command is meant for any situation where you want to make sure
you're doing a clean install of your dependencies.
It is significantly faster than npm install. If a node_modules is
already present, it will be automatically removed before npm ci begins
its install.
Matches the GitHub actions to build the package.
The clean-dev rule is now unused and can be removed.
https://docs.npmjs.com/cli/v7/commands/npm-ci
1. make dev-setup
> Use npm ci to install front-end dependencies in dev

- src/store/calendars.js
Catch single faulty events to prevent a full calendar not showing anything.
1. Create an event
2. Make the calendar data invalid in the db
3. Load a time range with the faulty calendar object
> Catch invalid calendar objects

- src/views/Calendar.vue
The calendar grid was moved into its own component in 3a076313a6796db63a538719c3d25bf6f492ce41.
`updateTodayJob` and `updateTodayJobPreviousDate` were moved with it.
This commit just cleans up the left over code.
1. Take a look at the Calendar.vue file
2. Search for uses of the removed data.
3. Find none 😉
> minor: remove `updateTodayJob` from main Calendar.vue

- css/freebusy.scss
The blocking event (the slot for the selected time frame of the event)
is supposed to show with red border and no background. For some reason
this styling broke (possibly through a fullcalendar upgrade) and
therefore needed some stricter styling rules that turn off FC's default
background and reset the opacity to make the border stand out.
This brings the design back to the original design as done by Georg.
Ref https://github.com/nextcloud/calendar/pull/1731
> Fix free/busy blocking event background and border

- src/components/Editor/FreeBusy/FreeBusy.vue
Fullcalendar sorts resources by their ID. In our app that is the
attendee's email address. For the fake blocking event that shows the
current time slot we need to know the first and last resource to show a
special border on top/bottom. In some scenarios that didn't work before,
now it seems more reliable.
* Create an event
* Add user A with email b@domain.tld
* Add user B with email a@domain.tld
Master: borders don't make any sense
This branch: smooth borders that show an actual box
> Fix sorting of free/busy resources

- .github/workflows/npm-test.yml
- .github/workflows/php-test.yml
They are only required for private repos.
Ref https://github.com/codecov/codecov-action#usage
> Use Codecov without tokens

- css/fullcalendar.scss
This fixes #2679 
This pull request makes the right border on "today" visible again in month and week view when using Firefox.
before:
after:
> Fix right border on today not being visible in month and week view when using Firefox

- css/fullcalendar.scss
Fixes https://github.com/mwalbeck/nextcloud-breeze-dark/issues/232
This doesn't change anything with the default theme as ```--fc-list-event-hover-bg-color``` is normally set to the same colour as the default colour value of ```--color-background-hover```.
Before:
After:
> Fix white hover background on events in list view when using dark theme

- .stylelintrc
- src/components/Editor/FreeBusy/FreeBusy.vue
Adds a date picker to the free/busy UI so that you can navigate around more efficient than just prev/next days.
1. Create an event
2. Add participants
3. Open the free/busy UI
In case you changed, added or removed UI elements, please provide a set of before / after screenshots:
|![Bildschirmfoto von 2021-02-11 10-17-04](https://user-images.githubusercontent.com/1374172/107618823-7de1cc00-6c52-11eb-80e3-11514ad6baf7.png)|![Bildschirmfoto von 2021-02-11 10-16-14](https://user-images.githubusercontent.com/1374172/107618839-833f1680-6c52-11eb-9850-ba26e6ba616c.png)|
Todo
cc @jancborchardt @oparoz as discussed
> Add a date picker to the free/busy UI

- css/fullcalendar.scss
^ some artifacts of the regression. The today column was shown *above* the actual events and therefore events became impossible to click and some visual regressions with lines above events showed as well.
cc @mwalbeck
> Revert "Fix right border on today not being visible in month and week view when using Firefox"

- src/utils/illustration.js
- removed duplicate entry for 'Party' and 'Celebration'
- removed ambiguous terms 'Game' and 'Play' from matching with illustration of gaming controller [ game could also refer to any sports match, play could also be in an event title for a theater play ]
- added string 'Bike' to match with bicycle illustration
> Fix: illustration.js

- .github/workflows/build.yml
- package-lock.json
For some yet unknown reason the lockfile upgrade in https://github.com/nextcloud/calendar/pull/2986 causes build errors with npm 7.
So I downgraded my local npm, reset the package lock to the version before that PR and redid the updates. Now it builds again.
I've added node v15 to the build matrix so we hopefully catch those build breaks earlier.
This needs a manual fix for the backported updated on stable2.2.
To test
0. Make sure you have npm7
1. Run `npm ci`
2. Run `npm run dev`
on master: :boom: 
here: :sunglasses:
> Downgrade the package-lock.json format to v1

- src/components/Shared/DatePicker.vue
Was broken in https://github.com/nextcloud/calendar/commit/7d372b32eb6a646c0b649a80f7766bbd882df88e
- Closes #2983
It seems the `format` prop is required to have `HH:mm` to display the timepanel…for some reason
- Remove obsolete props `not-before` and `not-after` which are replaced by a `disabled-date` function prop in vue2-datepicker 3.0.0
Note: The `first-day-of-week` seems unused in `@nextcloud/vue` or `vue2-datepicker`, it should probably override the setting in `lang` instead of be set as a prop here.
For reference, it should be using the `window.firstDay` instead of raw moment data because of language vs locale issue (see https://github.com/nextcloud/calendar/pull/1583)
> Fix compatibility with latest versions of DateTimePicker not showing time panel

- .editorconfig
Editors configured to pick up the coding style from .editorconfig should
be told *.vue files use the same configuration as *.js files.
> Set editorconfig for Vue files

- package-lock.json
- package.json
I was too fast with #3078, #3086 and #3087. They break the main calendar component. I have to upgrade fullcalendar in one go and possibly adjust to some (breaking) changes.
> Revert the partial upgrade of fullcalendar to v5.7

- package-lock.json
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
- src/components/AppNavigation/CalendarList/Moment.vue
- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/services/caldavService.js
- src/services/windowTitleService.js
- src/store/calendars.js
- src/views/Calendar.vue
- src/views/Dashboard.vue
This adds a UI to list and restore deleted calendars and calendar objects, as discussed in https://github.com/nextcloud/server/issues/1662.
Todo
> Add a UI for the Nextcloud CalDAV trashbin

- src/components/Editor/FreeBusy/FreeBusy.vue
- src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
- src/fullcalendar/eventSources/freeBusyResourceEventSource.js
Fixes #3112 
Show the organizer of an event in the free/busy modal.
The required changes were already in the code but commented out :thinking:
> Show organizer in free busy modal

- src/components/Editor/Invitees/OrganizerListItem.vue
Follow up to #3132 
I missed a reference to `AvatarParticipationStatus` in `OrganizerListItem`. The organizer does not have a tooltip (and is an individual) so `isResource` can be false all the time.
> Add missing isResource property to OrganizerListItem

- package-lock.json
- src/components/AppNavigation/CalendarList/Trashbin.vue
> Add a footer for trash bin

- src/components/AppNavigation/CalendarList/Trashbin.vue
Ref https://github.com/nextcloud/calendar/pull/3130#issuecomment-854421937
This also hides the footer if the retention is set to 0.
> Show the trash bin retention only if one is available

- package-lock.json
- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/store/calendars.js
If an admin sets the retention duration to 0 then deletions will drop
data right away and remaining deleted items will be killed in the next
cron job. So there is nothing for the user to restore and we can safely
hide the item from the sidebar.
> Hide the trash bin if it's disabled

- css/fullcalendar.scss
Both condensed (one-line) and normal (2+ lines) events have no minimum height limit, resulting in cut-off event time and/or text.  This change introduces minimum limits for both event styles, guaranteeing that both time and text will be shown.  The trade-off here is that the event height no longer directly correlates exactly to the length of the event.
Before this change:
With this change:
This addresses #2644
> Add min-height limits for events

- src/components/Shared/CalendarPicker.vue
- src/components/Shared/DatePicker.vue
- src/views/EditSidebar.vue
Fix #3122
The slots of our calendar and date picker components still had the old syntax.
> Fix calendar and date picker

- css/fullcalendar.scss
Alternative fix for #2679 without the regression found with #2939 
Sorry about the previous fix, that regression wasn't great... Hopefully this fix is better.
Unsetting the background colour on today achieves the same result. In Calendar the background colour of today is set to `--color-main-background` which is the same as the parent table, so it isn't necessary to be set again when we want it to be the same colour. I have used `!important` as the original rule from fullcalendar is defined inline. Any change of the background during usage, like background colour change on highlight in monthly view, seems to happen inside the today element and not on the today element itself, so that isn't affected by this fix.
Before:
After:
cc @ChristophWurst
> Fix right border on today not being visible in month and week view when using Firefox, again

- css/app-sidebar.scss
Fixes #3160
The button was hidden before but the sidebar structure changed so the CSS rule did not apply.
> Hide title arrow button in sidebar

- src/models/calendar.js
- tests/javascript/unit/models/calendar.test.js
replacement for PR https://github.com/nextcloud/calendar/pull/3159
Tested on my local machine with 2 users
Signed-off-by: Andreas Demmelbauer <git@notice.at>
> make shared calendars visible/enabled by default

- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
The webcals is not officially registered (it's only assumed to be webcal over https), and it seems [1] some clients don't support it.
Nowdays everything should be using and redirecting to https anyway (and Nextcloud proxifies it's subscribed calendars). Also it's not possible to register a handler for `webcals`, only `webcal` (see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler).
Closes #2416 and #3050 and also related to #2197
[1] https://github.com/nextcloud/calendar/issues/2416
> Remove webcals support

- css/fullcalendar.scss
This increases the visibility of the calendar color, and fixes half of https://github.com/nextcloud/calendar/issues/2755
Before | After
-|-
> Increase size of dot on timed events in month view for visibility

- css/fullcalendar.scss
You can see the events of the current day be a bit too far up, because the 
This is fixed now (24 height + 2*4 padding = 32, like the other numbers), also including properly centering it and vertically aligning the number in it:
> Fix alignment of events in today cell in month view

- lib/Controller/PublicViewController.php
- tests/php/unit/Controller/PublicViewControllerTest.php
The server [already does the request](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php#L202) with the following header `Accept: 'text/calendar, application/calendar+json, application/calendar+xml'`. `text/calendar` isn't a MIME type requested by common browsers.
Closes https://github.com/nextcloud/server/issues/17746
> Redirect public view to public calendar ics endpoint if requested with Accept: 'text/calendar'

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
- src/utils/url.js
- tests/javascript/unit/utils/url.test.js
Fixes https://github.com/nextcloud/server/issues/25165
Fixes https://github.com/nextcloud/server/issues/17610
Fix https://github.com/nextcloud/server/issues/25459
#1985 introduced decoding of urls by using `decodeUri()` which does not fully reverse `urlencode()` of php. Instead all plus signs have to replaced with spaces manually and then `decodeURIComponent()` has be called. Principals of groups were encoded 2 times in a row because the decode wasn't working correctly which resulted in shares not being created.
I tested a couple exotic group names with spaces and special chars (e.g. `my group &%+`) and they all worked fine. Ideally, you should now be able to create a group containing spaces and then share calendars with those groups again.
Georg pointed out in the linked PR that this …
> Properly decode escaped principal urls

- src/components/AppNavigation/CalendarList/CalendarListItemSharingSearch.vue
- src/services/talkService.js
Fixes #3262 
The trailing slash is only added if the given url has one too. I also fixed talk room creation always reporting success even if it fails.
Those 2 things should work again:
1. Share calendars with circles
2. Create talk rooms from events (Sidebar -> Attendees)
> Fix missing slashes in generated urls

- css/fullcalendar.scss
Matches change in fullcalendar [v5.7.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.7.0).
This allows the min-height style that prevents vertical text clipping to be applied to the short-style event (one-line of text).  Without this rename, short events are unnecessarily vertically enlarged.
Related to #3121 and #2644.
> Rename fc-timegrid-event-condensed to fc-timegrid-event-short

- css/app-sidebar.scss
- src/components/Editor/Repeat/RepeatFreqSelect.vue
Vue-Multiselect [*should* calculate the multi-select position automatically](https://github.com/shentao/vue-multiselect/blob/master/src/multiselectMixin.js#L696-L715), but that fails for some reason on small screen sizes. We can force the position on the bottom.
On small screen sizes as well the input is too small to view the placeholder fully, increasing that a bit.
Before | After
--------|------
Maybe @nextcloud/vuejs has better knowledge of this kind of Vue-Multiselect issues.
> Fix event repeat multiselect width and position on low resolutions

- src/components/Editor/Invitees/InviteesListSearch.vue
Fixes #3189 
Always show the email addresses of user in the attendee search results. 
I also took the liberty to remove the `singleLabel` slot because it is only used when the selected option is displayed inside the multiselect field. This is not the case in our attendee search bar because we instantly clear the multiselect after selecting a new option and instead show all selected options in the list below.
Show only one row in this case to prevent displaying the email address twice. Works for search results from contacts too.
> Show email addresses in attendee search

- css/calendar.scss
- css/fullcalendar.scss
- css/icons.scss
- src/main.js
- templates/main.php
Ref #3178
Nearly all style sheets are now bundled by webpack and automatically rebuilt by the watcher. This should make developing more pleasant because we don't have to deal with the server cache anymore when scss style sheets are modified.
Now, the server compiles only one last style sheet: `css/icons.scss`. The icons are still compiled through the `icon-*()` scss mixins. Those could be migrated to the icon svg api but I suggest postponing the refactoring until its necessary (e.g. the server drops scss compilation).
> Bundle style sheets using webpack

- src/mixins/EditorMixin.js
Prevent frequent errors like:
```
vue.runtime.esm.js:619 [Vue warn]: Invalid prop: type check failed for prop "canModifyAllDay". Expected Boolean, got Null 
found in
---> <PropertyTitleTimePicker> at src/components/Editor/Properties/PropertyTitleTimePicker.vue
<AppSidebar>
<EditSidebar> at src/views/EditSidebar.vue
<Content>
<Calendar> at src/views/Calendar.vue
<App> at src/App.vue
<Root>
```
> Use nullish coalescing operator in editor mixin

- package-lock.json
- package.json
> [stable2.3] Bump calendar-js to 2f550aa99d961c78da9684f11c8f6ed4d5aae7ba

- src/store/calendars.js
Tasks might not have a startDate or endDate so we need to check for that before trying to reload a time range.
Closes #3331.
> Don't throw error when restoring a task

- src/views/EditSidebar.vue
Fixes #3351 
The calendar picker still works for the first event of a recurrence set because the "Update this and all future" button is working as expected. However, the picker is read only for all recurrences.
> Disable calendar picker for recurrences

- css/app-sidebar.scss
- src/views/EditSidebar.vue
Fix https://github.com/nextcloud/calendar/issues/3289
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/127004799-a90c96c1-cede-4fcf-b0a9-fcaab09f98d2.png) | ![image](https://user-images.githubusercontent.com/42591237/127004442-902e3f33-3f95-47a9-85fc-e9dc7a27a37e.png) |
> Make the sidebar usable on mobile again

- css/app-sidebar.scss
This small styling fix prevents the description of an event
to grow uncontrollably in either width (e.g. in the
presence of a long URL that otherwise cannot go to a
newline), or height (by introducing a maximum relative to
the viewport, and scrollbar otherwise).
Signed-off-by: Matteo Settenvini <matteo.settenvini@montecristosoftware.eu>
> Restrict size of text fields in event pop-up

- src/components/CalendarGrid.vue
- src/views/EditSimple.vue
Fixes #2968
New events disappear from the grid when a user switches from the simple to the sidebar editor. Now, the event stays until the user either saves it or discards it by closing either editor.
> Fix new events disappearing from the grid

- src/components/Editor/Invitees/InviteesListSearch.vue
> Fix fetching language from DAV attendee

- composer.json
- composer.lock
This prevents shipping them and their dependencies, like
symfony/console
Ref https://github.com/nextcloud/circles/issues/807
> Make coding standards a dev dep

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
The version number and changelog of the master branch were lacking behind the latest released versions (stable2.3). This PR updates both.
> Set version to latest version, amend changelog

- package-lock.json
- package.json
- src/components/Shared/TimezoneSelect.vue
- src/fullcalendar/duration.js
- src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
- src/fullcalendar/eventSources/freeBusyResourceEventSource.js
- src/models/event.js
- src/store/calendarObjectInstance.js
- src/store/calendarObjects.js
- src/store/calendars.js
- src/utils/calendarObject.js
- tests/assets/loadAsset.js
- tests/javascript/unit/models/calendarObject.test.js
- tests/javascript/unit/models/event.test.js
- tests/javascript/unit/models/recurrenceRule.test.js
- tests/javascript/unit/models/schedulingObject.test.js
- webpack.js
I updated all imports and fixed jest in preparation for the upcoming bundled release of calendar-js.
Until the new version is released on npm, you have to checkout my branch manually and then install it by running `npm install /path/to/cloned/and/built/calendar-js`.
> Use bundled version of calendar-js

- src/components/Editor/Properties/PropertyTitleTimePicker.vue
- src/components/Shared/DatePicker.vue
- src/views/EditSidebar.vue
This PR appends the datepicker in the AppSidebar to body. This prevents the datepicker to be cut off.
After:
Before:
Closes #2880.
> Append the datepicker in the sidebar to body

- src/components/AppNavigation/CalendarList.vue
Fix #3394
Inspired by https://github.com/nextcloud/server/pull/28767
<details>
```
docker run -d \
-e CALENDAR_BRANCH=enh/3394/fix-moving-calendars \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.178.34 \
--user=www-data \
```
</details>
> fix calendar handling on android

- css/app-navigation.scss
- css/app-settings.scss
- css/app-sidebar.scss
- package.json
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingPublishItem.vue
- src/components/AppNavigation/CalendarList/CalendarListItemSharingShareItem.vue
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/components/AppNavigation/EmbedTopNavigation.vue
- src/components/AppNavigation/Settings.vue
- src/components/AppNavigation/Settings/SettingsImportSection.vue
- src/components/Editor/Alarm/AlarmListItem.vue
- src/components/Editor/Alarm/NoAlarmView.vue
- src/components/Editor/NoAttendeesView.vue
- src/components/Editor/Properties/PropertyColor.vue
- src/components/Editor/Properties/PropertySelect.vue
- src/components/Editor/Properties/PropertySelectMultiple.vue
- src/components/Editor/Properties/PropertyText.vue
- src/components/Editor/Resources/ResourceList.vue
- src/components/EmptyCalendar.vue
- src/mixins/PropertyMixin.js
- src/models/rfcProps.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
- tests/javascript/unit/models/rfcProps.test.js
All icons of the app got replaced with the material-design equivalents. This is how the main view looks now:
After:
Before:
I think that I replaced all icons. If not, it might be best to do it in a follow up (since this PR is already quite large).
> Use material-design-icons

- css/app-sidebar.scss
- package-lock.json
- package.json
- src/components/Editor/Resources/ResourceListSearch.vue
- src/components/Editor/Resources/ResourceRoomType.vue
- src/models/resourceProps.js
- src/services/caldavService.js
Fix #3417
~Requires https://github.com/nextcloud/cdav-library/pull/554~ via this PR
Implements filtering rooms by type and availability. The availability will be hidden from the search results if the user only searches for available rooms/resources.
I took all supported room types from https://github.com/nextcloud/calendar/issues/3184#issuecomment-872172487. Letting the user filter room types using a text input will reduce the usability. Maybe we can implement a way to define custom room types when we implement the frontend for room creation. Then we can populate the room type dropdown from the backend.
> Filter rooms by type and availability

- webpack.js
Ref #3412 
It breaks compatibility with Firefox < 90 which we support according to our browserslist config.
Running `npm run dev && grep '#head' js/*.js` should only show occurrences in comments after applying this PR.
> Transpile yocto-queue

- css/app-sidebar.scss
Fix https://github.com/nextcloud/calendar/issues/2200
<details>
```
-e CALENDAR_BRANCH=enh/2200/fix-simple-editor-size \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.178.34 \
```
</details>
> fix simple editor size

- src/components/AppNavigation/Settings/SettingsTimezoneSelect.vue
- src/components/Shared/DatePicker.vue
After moving the TimezoneSelect to vue, and renamed it TimezonePicker, we need to replace it on calendar accordingly
> Replace timezoneselect with timezonepicker

- css/app-sidebar.scss
- src/components/Editor/Properties/PropertySelect.vue
> Equalize margins between properties on details tab

- appinfo/routes.php
- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Db/AppointmentConfigMapper.php
- lib/Service/Appointments/AppointmentConfigService.php
Fixes https://github.com/nextcloud/calendar/issues/3481
Base URL is `/apps/calendar/v1/appointment_configs`. You can `GET` it to get all configs, and `GET`, `POST` and `DELETE` a specific config at `/apps/calendar/v1/appointment_configs/123`.
> Add REST API for appointment configs

- lib/Controller/BookingController.php
- src/services/appointmentService.js
- src/views/Appointments/Booking.vue
If we push to the start of the day in UTC and then in the respective time zone, we might shift by two days. This is testable if you provide slots in UTC but book in Auckland time. November 4th slots are requested but November 2n is where the first one started.
> Fix time zone handling for appointment slots

- src/components/Editor/AvatarParticipationStatus.vue
- src/components/Editor/Resources/ResourceList.vue
- src/components/Editor/Resources/ResourceListItem.vue
- src/components/Editor/Resources/ResourceListSearch.vue
- src/services/freeBusyService.js
Suggest up to three available rooms for events with participants but no selected rooms or resources. The current number of participants is used to find fitting suggestions.
Fixes https://github.com/nextcloud/calendar/issues/3418
Todo
^ against what we discussed last week I still went with a subline because without it it is even harder to see that the resource isn't part of the event yet. We can fine tune this in follow-ups.
> Show room suggestions for events

- appinfo/routes.php
- css/app-modal.scss
- css/app-navigation.scss
- css/calendar.scss
- lib/Controller/AppointmentConfigController.php
- lib/Controller/ViewController.php
- src/components/AppNavigation/AppointmentConfigList.vue
- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/CheckedDurationSelect.vue
- src/components/AppointmentConfigModal/DurationInput.vue
- src/components/AppointmentConfigModal/DurationSelect.vue
- src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
- src/components/AppointmentConfigModal/NumberInput.vue
- src/components/AppointmentConfigModal/Select.vue
- src/components/AppointmentConfigModal/TextArea.vue
- src/components/AppointmentConfigModal/TextInput.vue
- src/components/AppointmentConfigModal/VisibilitySelect.vue
- src/components/Appointments/AppointmentDetails.vue
- src/main.js
- src/models/appointmentConfig.js
- src/services/appointmentConfigService.js
- src/store/appointmentConfigs.js
- src/store/index.js
- src/utils/randomId.js
- src/views/Calendar.vue
- tests/javascript/unit/utils/randomId.test.js
- tests/php/unit/Controller/ViewControllerTest.php
Fix https://github.com/nextcloud/calendar/issues/3483
> Implement CRUD UI for appointment configs

- css/app-navigation.scss
- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Fix #3625
Entries in the appointment config list show the default cursor instead of the pointer cursor now.
> Make appointment configs not clickable

- src/components/AppointmentConfigModal/CheckedDurationSelect.vue
- src/components/AppointmentConfigModal/DurationSelect.vue
> Set default preparation and followup durations to 0 minutes

- lib/Db/AppointmentConfig.php
- lib/Service/Appointments/AvailabilityGenerator.php
- src/appointments/main-booking.js
- src/appointments/main-overview.js
- src/services/appointmentService.js
- src/utils/localeTime.js
- src/views/Appointments/Booking.vue
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
* Factor in *start time*
* Do not let the user select times before that
* Do not generate available slot before
* Factor in *end time*
* Do not let the users select times after that
* Do not generate available slots after
* Factor in *Minimum time before next slot*
* Do not let the user select dates without a possible first bookable slot
* Do not generate available slots before
`start` and `end` are missing from the UI. You have to generate timestamps and add them to the DB manually.
> Fix appointments availability handling: start, end and time before next slot

- src/views/Appointments/Booking.vue
Fix #3641 
I opted for `:size="180"` to make it consistent with the avatar on the overview page. Doubling the size would have yielded `128`.
> Increase the avatar size on the appointment booking page

- src/views/Appointments/Booking.vue
Fix #3653 
The date selection might need some more padding on the right.
> Fix jumping timezone picker

- src/components/Appointments/AppointmentDetails.vue
Fix #3656
Fix #3657 
Fix #3658
> Improve appointment booking modal

- webpack.js
Fix #3649 
The library ical.js heavily depends on instanceof checks which will break if two separate versions of the library are used (e.g. bundled one and global one).
Ref https://webpack.js.org/guides/shimming/
1. Create some events in the near future
2. Observe that the calendar widget is working fine
3. Install notes
4. Observe that the calendar widget doesn't show any events anymore
5. Apply my patch
6. Observe that the calendar widget is working fine again
> Shim ICAL to prevent using the global object

- lib/Service/Appointments/AvailabilityGenerator.php
- lib/Service/Appointments/EventConflictFilter.php
- lib/Service/Appointments/SlotExtrapolator.php
- src/views/Appointments/Booking.vue
- tests/php/integration/Db/AppointmentConfigMapperTest.php
- tests/php/unit/BackgroundJob/CleanupOutdatedBookingJobTest.php
- tests/php/unit/Controller/AppointmentConfigControllerTest.php
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
- tests/php/unit/Service/Appointments/SlotExtrapolatorTest.php
Remove the times 60 multiplier as increments, length etc should be sent and received as seconds.
> Removed times 60 multiplier for appointments

- src/components/AppNavigation/AppointmentConfigList.vue
- src/components/AppointmentConfigModal.vue
- src/components/Shared/CalendarPicker.vue
- src/models/appointmentConfig.js
Ref https://github.com/nextcloud/calendar/pull/3470#issuecomment-978031390
~~the calendar picker still doesn't work. @st3iny any idea? Did it ever work? Did we break it?~~ it tracked by display name and my two test calendars had the same name. Fixed this by switching to the unique URL.
> Persist the calendar URI for an appointment config

- lib/AppInfo/Application.php
- lib/Db/AppointmentConfigMapper.php
- lib/Db/BookingMapper.php
- lib/Listener/UserDeletedListener.php
- lib/Service/Appointments/AppointmentConfigService.php
- lib/Service/Appointments/BookingService.php
- tests/php/unit/Listener/UserDeletedListenerTest.php
- tests/php/unit/Service/Appointments/AppointmentConfigServiceTest.php
- tests/php/unit/Service/Appointments/BookingServiceTest.php
Fixes https://github.com/nextcloud/calendar/issues/3604
To test create a new user on your dev instance, then create at least one appointment config. Delete the user after and check the database. There shouldn't be any configs of that user.
> Delete appointment configs when the user is deleted

- src/models/appointmentConfig.js
And add a fallback as well.
Bug introduced with https://github.com/nextcloud/calendar/pull/3700. The time zone was missing from the availability data structure and the validation did not allow creation of new configs.
> Fix appointment availability time zone from caldav

- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/DurationSelect.vue
Because the previous max of 1h is very short notice.
> Allow longer time before the next possible appointment slot

- lib/Service/Appointments/BookingCalendarWriter.php
The length is in seconds already.
Leftover from https://github.com/nextcloud/calendar/pull/3692
> Do not multiple event length x60

- lib/Service/Appointments/BookingService.php
- tests/php/unit/Service/Appointments/BookingServiceTest.php
The logic is a black box otherwise and impossible to debug in
production.
Example log
```json
{
"reqId": "9lovcMHpqpTdxWVQQJlX",
"level": 0,
"time": "2021-11-29T13:02:32+00:00",
"remoteAddr": "127.0.0.1",
"user": "admin",
"app": "calendar",
"method": "GET",
"url": "/apps/calendar/appointment/27/slots?startTime=1638190952&timeZone=Europe%2FVienna",
"message": "Appointment config QByBoCW64gbs has 1 intervals that result in 11 possible slots. 11 slots remain after the daily limit. 11 available slots remain after conflict checking.",
"userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
"version": "24.0.0.0"
}
```
> Log debug infos of appointment slots

- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
Fix #3723 
I also moved the code of the feature check to a v-if condition. Now, the copy link action button won't be shown if the browser does not support it.
> Improve appointment config copy to clipboard action

- src/components/Appointments/AppointmentDetails.vue
- src/views/Appointments/Booking.vue
> Fix white space in appointment descriptions

- src/views/Appointments/Booking.vue
Fix #3726
This also eliminates the jump when selecting a date with many slots.
> Fix vertical padding on booking page

- css/app-modal.scss
- css/app-sidebar.scss
- src/components/AppNavigation/Settings/ImportScreenRow.vue
- src/components/AppointmentConfigModal.vue
- src/components/Editor/Properties/PropertyCalendarPicker.vue
- src/components/Shared/CalendarPicker.vue
Fix #3722 
I refactored the existing `CalendarPicker` component to also work with multiple values so here is some proof that it still works elsewhere:
(Couldn't debug the last usage in the import modal because I failed to provide a valid ICS file.)
> Add picker for conflict calendars of appointments

- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Service/Appointments/AppointmentConfigService.php
- src/components/AppointmentConfigModal.vue
- src/models/appointmentConfig.js
The name of the conflict calendar URIs field was inconsistent between the front and back end.
Create new and edit existing appointment configs and observe that conflict calendars are saved correctly.
> Fix freebusyUris naming inconsistencies

- src/components/AppointmentConfigModal.vue
The target is always a conflict calendar. It's confusing if it can be
selected twice as the second selection has no effect.
This also drop the new targe calendar from the conflict list if it was
on there.
> Don't allow a calendar for appointment conflicts if it's the target

- src/views/Appointments/Booking.vue
Added "flex-warp: wrap;" to prevent unusable mobile design since flex-wrap default is nowrap which leads to horizontal scrolling on mobile devices
I hope this pull request is right here. It's my first pull request, so i'm sorry if it doesn't belongs here :)
Fixes #3808
> Add flex-wrap for better mobile design

- src/components/Shared/DatePicker.vue
This will show the timepicker (instead of the datepicker) directly when clicking into the date/time field. In my opinion would be having two dedicated fields for date and time be the proper solution but until then is being able to choose the time before the date the much better flow since most of the time you want to choose/change the time and not the date.
<details>
```
-e CALENDAR_BRANCH=enh/noid/pick-time-first \
-p 8443:443 \
```
</details>
> pick time first

- css/fullcalendar.scss
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/145900304-6e4e3cfb-1ecd-4503-bf1d-bed1922c144a.png) | ![image](https://user-images.githubusercontent.com/42591237/145900325-11117097-463e-43e5-81a9-f56deb396e1e.png) |
<details>
```
-e CALENDAR_BRANCH=enh/noid/show-whole-title \
-p 8443:443 \
```
</details>
> show the whole title if the event is long enough

- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/SaveButtons.vue
- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Fixes #947 
Events should be read only if invitees view them. Only the alarms can be edited.
> Fix events being editable by invitees

- css/fullcalendar.scss
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/146766498-c54a25df-b036-4aca-9830-89e4a62d8ebc.png) | ![image](https://user-images.githubusercontent.com/42591237/146767322-5ba5301f-979b-4681-99d3-f84e9bcf9198.png) |
<details>
```
-e CALENDAR_BRANCH=enh/noid/short-events \
-p 8443:443 \
```
</details>
> fix short events being to long

- src/components/CalendarGrid.vue
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/146650269-a6115b7a-102b-4553-abf7-52955d6a7d4f.png) | ![image](https://user-images.githubusercontent.com/42591237/146650144-42eb5caa-8271-469d-a787-527e38c46db3.png) |
<details>
```
-e CALENDAR_BRANCH=enh/noid/slot-duration \
-p 8443:443 \
```
</details>
> fix layout for slotduration of one hour

- src/store/calendarObjectInstance.js
This is best reviewed like this https://github.com/nextcloud/calendar/pull/3825/files?diff=unified&w=1
Close https://github.com/nextcloud/calendar/issues/3824
https://user-images.githubusercontent.com/42591237/146625622-af0640fd-7da5-4d03-acc0-cde6fbbd3d74.mp4
https://user-images.githubusercontent.com/42591237/146625491-3b64b552-e0f5-4ee8-8c19-beb51d4785c7.mp4
<details>
```
-e CALENDAR_BRANCH=enh/3824/target-time \
-p 8443:443 \
```
</details>
> improve UX regarding target time

- .github/ISSUE_TEMPLATE/feature_request.md
We renamed the label recently.
> Fix default `enhancement` label for new feature requests

- css/fullcalendar.scss
This is best reviewed like this: https://github.com/nextcloud/calendar/pull/3831/files?diff=unified&w=1
**Making today better recognizeable on big screens**
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/146953496-513dcf39-7846-4451-8227-75bf32cabb96.png) |![image](https://user-images.githubusercontent.com/42591237/146952821-9e3b9106-b92a-44b4-83da-ef28d299d2b0.png) |
| ![image](https://user-images.githubusercontent.com/42591237/146953242-1cc3ad54-05c8-4957-9f97-076ce977c98e.png) | ![image](https://user-images.githubusercontent.com/42591237/146952734-e73b7a46-043e-4344-a295-51c956b09f60.png) |
<details>
```
-e …
```
> adjust week view

- src/views/EditSidebar.vue
Fixes https://github.com/nextcloud/calendar/issues/3838
Fixes https://github.com/nextcloud/calendar/issues/3842
1. Have two or more calendars
2. Create an event in the first calendar
3. Open the editor sidebar
4. Try to switch to the second calendar
On main: calendar stays on the first one
Here: second calendar is selected
> Fix calendar selection in editor sidebar

- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Migration/Version3010Date20220111090252.php
- lib/Service/Appointments/AppointmentConfigService.php
- lib/Service/Appointments/BookingService.php
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/CheckedDurationSelect.vue
- src/components/AppointmentConfigModal/DurationSelect.vue
- src/models/appointmentConfig.js
Fix #3743
The name `futureLimit` may not be ideal but I couldn't come up with something better.
> Limit how far in the future appointments can be booked

- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/SaveButtons.vue
- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Fix #3866
Replaces https://github.com/nextcloud/calendar/pull/3884
This reverts commit 74b78b9dc601424665fa333fcfdd25726f61ec5b because it introduced some edge cases.
It can be hard to distinguish between invitee, owner and organizer so we shall not enforce invitations to be read only for now.
> Revert "Fix events being editable by invitees"

- package-lock.json
- package.json
Fixes the time zone of reminders. It was initialized to UTC but now it's copied from the event.
> Bump @nextcloud/calendar-js from 2.0.0 to 3.0.0

- webpack.config.js
Required for https://github.com/nextcloud/calendar/pull/3901
The constructor of `IgnorePlugin` has changed since webpack v5.
Ref https://webpack.js.org/plugins/ignore-plugin/#example-of-ignoring-moment-locales
> Fix usage of IgnorePlugin

- package-lock.json
- package.json
Backport of #3910
Fixes the time zone of reminders. It was initialized to UTC but now it's copied from the event.
> [stable3.0] Bump @nextcloud/calendar-js from 2.0.0 to 3.0.0

- src/components/Editor/InvitationResponseButtons.vue
- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Fixes #144
According to https://icalendar.org/CalDAV-Scheduling-RFC-6638/b-3-example-attendee-replying-to-an-invitation.html responding to an invitation is done by setting the participation status and sending the modified ics data to the server. Thunderbird seems to do the same thing.
The local participation status in the invitees list is updated right away (without reloading the page). There is one minor side effect: The accept/decline buttons internally trigger a full save which also persists changes of e.g. reminders. Fixing this would need a lot of potentially ugly code. Again, Thunderbird also ignores this case and other changes to the event are also saved upon accepting or declining.
| Simple | Sidebar|
| ---    | ---    |
| ![Screenshot 2022-01-04 at 18-04-30 April 2022 - Calendar …
> Accept and decline invitations

- src/store/calendarObjectInstance.js
This PR addresses issue #3863: In addition to the plain text description of an event, Thunderbird also saves a formatted HTML version inside the ALTREP parameter. NC calendar does not alter the ALTREP parameter when the plain text description is changed. This results in inconsistencies.
The proposed solution deletes the ALTREP parameter upon modification. This prevents inconsistencies. Thunderbird keeps accepting plaintext-only descriptions.
I will have opened a [similar PR](https://github.com/nextcloud/tasks/pull/1916) in nextcloud/tasks as it is equally concerned.
> Fix: Inconsistencies due to ALTREP parameter

- .github/workflows/php-test.yml
PHP v7.3 was dropped and thus breaking our master workflow.
> Drop php 7.3 for php-test workflow on master

- src/store/calendarObjectInstance.js
This is a follow-up of #3918. In this old PR only the ALTREP parameter is cleared upon modification of the description property. It therefore solves #3863. However, also all other [possible parameters](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.1.5) may cause inconsistencies. This PR deletes all parameters of the description property upon modification.
> Fix: Inconsistencies due to parameters in description property

- src/store/calendarObjectInstance.js
Similar to #3924, this PR fixes an inconsistency issue. This time it is about the additional location information that Apple applications store in  the `X-APPLE-STRUCTURED-LOCATION` property. This is a supplement to the regular `LOCATION` property. It includes coordinates and a custom map reference. Upon change of `LOCATION` in a non-Apple application, `X-APPLE-STRUCTURED-LOCATION` becomes invalid. This PR solves this inconsistency by removing the `X-APPLE-STRUCTURED-LOCATION` property upon change of the location.
Discussion can be found in #3905.
> Fix: Inconsistencies due to Apple's additional location property

- appinfo/info.xml
Fix #3957 
I created a migration via #3877 but forgot to bump the version.
> Bump app version to fix migration

- lib/BackgroundJob/CleanUpOutdatedBookingsJob.php
This contributes the Calendar part of https://github.com/nextcloud/groupware/issues/28.
Only the hourly sync job is time sensitive, the rest can be done at off times.
`method_exists` checks will allow us to ship this to older Nextcloud releases.
> Mark background jobs as time sensitive/insensitive

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Per https://github.com/nextcloud/calendar/issues/3993#issuecomment-1050840836
> Rename 'Download' to 'Export'

- lib/Controller/ViewController.php
- src/components/Editor/Alarm/AlarmList.vue
- src/components/Editor/Alarm/AlarmListItem.vue
- src/store/settings.js
- src/views/Calendar.vue
- tests/javascript/unit/store/settings.test.js
- tests/php/unit/Controller/ViewControllerTest.php
This contributes the second part of https://github.com/nextcloud/calendar/issues/3993.
* Admins can enforce `DISPLAY` or `EMAIL` as alarm type
* The value is used as new default for an reminder
* If a reminder matches the enforced type, we hide the radio group all together (there would only be one option after all)
* If a reminder doesn't match the enforced type (event created before enforcement or another client) then the user decide to stay on the old value or switch to the enforced one
I will update the Calendar admin docs for this.
```shell
occ config:app:set calendar forceEventAlarm_type --value=EMAIL
```
> Optionally enforce a event alarm type

- css/app-sidebar.scss
Removed the unnecessary and off-style box-shadow from the participation status indicator, making it look less blurry too:
Before | After
-|-
> Remove blurriness from event participation indicator

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
This PR changes the icon for disabled calendars to `CheckboxBlankCircleOutline` so it can be better distinguished from enabled calendars. Since the color is not needed anymore as a difference, I figured we can keep it the same, even if the calendar is disabled. This is how it looks now:
Compared to before:
@jancborchardt @nimishavijay In case you prefer to still have disabled calendars using `var(--color-text-lighter)` instead of the calendar color, let me know, and I will change it.
Closes #4005.
> Use CircleOutline for disabled calendar icon

- src/views/Calendar.vue
This fixes a typo in the translation of the default calendar name. Closes #4046.
> Fix translation for default calendar name

- lib/Controller/ViewController.php
- src/components/Editor/Alarm/AlarmList.vue
- src/components/Editor/Alarm/AlarmListItem.vue
- src/store/settings.js
- src/views/Calendar.vue
- tests/javascript/unit/store/settings.test.js
This fixes selecting an alarm type if `forceEventAlarmType` is not set. The tricky thing is that it was not clear to me what the desired outcome of the code was. Hence, I interpreted it in a way that made most sense to me, but I might be wrong. This is how it looks now:
`forceEventAlarmType` is not set (or not `DISPLAY` or `EMAIL`):
One can select the alarm type. If it's `AUDIO` or something else, this will be shown.
`forceEventAlarmType` is `DISPLAY` or `EMAIL`:
No selection is possible, the alarm is created with the forced type.
Fixes #4032 and #4051.
> Fix alarm type selection if forceAlarmType is null

- src/components/AppNavigation/EmbedTopNavigation.vue
Leftover of https://github.com/nextcloud/calendar/pull/4015
> Rename calendar 'Download' to 'Export'

- src/views/EditSidebar.vue
- src/views/EditSimple.vue
> Hide invitation response buttons of read only events

- src/components/CalendarGrid.vue
Summary: Disable jumping in week view and day view when clicking on any event
(as it was seen in https://user-images.githubusercontent.com/42591237/146625491-3b64b552-e0f5-4ee8-8c19-beb51d4785c7.mp4)
<details>
```
-e CALENDAR_BRANCH=enh/noid/fix-scrolling \
-p 8443:443 \
```
</details>
> fix auto scroll when clicking on any event in week view

- src/fullcalendar/interaction/eventClick.js
- src/fullcalendar/interaction/select.js
- src/utils/router.js
- tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
- tests/javascript/unit/fullcalendar/interaction/select.test.js
- tests/javascript/unit/utils/router.test.js
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/161429831-91430dff-f2b6-439b-9c8e-5fe5bd894cff.png) | ![image](https://user-images.githubusercontent.com/42591237/161431428-dc2ed746-5e9b-457c-9869-c0ef9e524846.png) |
<details>
```
-e CALENDAR_BRANCH=enh/noid/show-popover \
-p 8443:443 \
```
</details>
> show the popover also on smaller screens to a certain degree

- src/components/Shared/DatePicker.vue
This closes #2936.
The goal is to create a more "guided" user experience by providing explicit actions to confirm an action
> add ok-button to datetime picker

- src/components/Editor/Invitees/InviteesListSearch.vue
When comparing email to check if it is present in the invitees list, we do not normalize the value.
This leads to inconsistencies:
1. the user will see two options when searching for Alice@exampe.com if the stored email is alice@example.com
2. the user will see one option when searching for alice@exampe.com if the stored email is alice@example.com
1 | 2
-- | --
This PR transform the values to lower cases to consolidate the number of options offered to the user.
> Compare lower case email when checking invitees

- css/app-navigation.scss
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
The navigation header did not use material icons yet.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/170679266-779ba4a1-5932-4441-9ee5-ca37cbdc78ad.png) | ![image](https://user-images.githubusercontent.com/1479486/170679213-133d1da1-8f11-41b5-9246-28dc8c3c0ed7.png) |
> Refactor navigation header arrow icons

- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
Fix #3979
The bug can be reproduced by editing an event with an organizer who is not a user, e.g. `ORGANIZER:mailto:other@domain.tld`.
| --- | --- |
| ![155034429-8c8e62da-22be-480c-8476-b8c132031e12](https://user-images.githubusercontent.com/1479486/170726112-c06f4bef-7e37-4f89-924e-368357b5ec24.png) | ![image](https://user-images.githubusercontent.com/1479486/170725777-fbd1087b-baf4-4ea3-a197-49b22b812474.png) |
> Fix and harden logic to extract an avatar link in invitee list

- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Fix https://github.com/nextcloud/calendar/issues/4270
> fix hide the 3-dot menu button for new events

- krankerl.toml
Is there a reason we don't generate optimized autoloaders?
> Generate optimized autoloaders in krankerl config

- src/components/AppNavigation/CalendarList/Trashbin.vue
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/174308575-3e849eba-0931-4849-b101-7f83addb8f8e.png) | ![image](https://user-images.githubusercontent.com/42591237/174306174-c453e5ae-8882-42ad-b7ff-e407b8c119e2.png) |
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/174308504-5fbacc0c-1065-4c3b-839c-3118b4874d8a.png) | ![image](https://user-images.githubusercontent.com/42591237/174306320-24779e86-7957-4221-9ba2-d250582d0948.png) |
<details>
```
-e CALENDAR_BRANCH=enh/noid/improve-trashbin-modal-size \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.130 \ …
```
> Improve the trashbin layout

- css/fullcalendar.scss
on week view
before
after
fixes #4291
> Fix the white space on calendar title

- lib/Controller/ViewController.php
- src/store/settings.js
- src/views/Calendar.vue
- tests/javascript/unit/store/settings.test.js
Context: on a production instance I administer (~100k users, ~15M events), the search for available slots systematically timeouts. A smaller instance (~6k) works great.
As there's no loading or error feedback on the loading page, the experience isn't great. There's probably room for improvement in the booking filters implementation.
In any case, I'd like to be able to disable this feature for the meantime, and there's probably some admins that don't care about this feature anyway.
> Add a config appsetting to allow to disable appointments

- src/components/AppNavigation/Settings/ShortcutOverview.vue
- src/mixins/EditorMixin.js
- src/models/event.js
- src/store/calendarObjectInstance.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Close https://github.com/nextcloud/calendar/issues/113
Based on https://github.com/nextcloud/calendar/pull/2621
Supersedes https://github.com/nextcloud/calendar/pull/2621
Close https://github.com/nextcloud/calendar/pull/2621
<details>
```
-e CALENDAR_BRANCH=enh/113/duplicate-event \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.130 \
```
</details>
> Duplicate calendar event

- src/components/Editor/FreeBusy/FreeBusy.vue
- src/components/Shared/DatePicker.vue
ref https://github.com/nextcloud/groupware/issues/38
> Migrate timezone and calendar icon

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
> Remove Action from CheckboxBlankCircle and add more description text

- src/components/AppNavigation/Settings/SettingsImportSection.vue
Fix #4053 
Both browsers (Chromium, Firefox) report a generic `application/x-extension-ics` mime type when importing a valid ics file on my system. We should gracefully handle this case.
Ref https://developer.mozilla.org/en-US/docs/Web/API/File/type
> Developers are advised not to rely on this property as a sole validation scheme.
> Don't rely on guessed mime type on import

- src/components/CalendarGrid.vue
- src/fullcalendar/rendering/eventOrder.js
- tests/javascript/unit/fullcalendar/rendering/eventOrder.test.js
If there are too many events on the last day of a week (e.g. Sunday), some might be hidden when the "limit events per view" checkbox is checked. 
There already is an ongoing upstream ticket at https://github.com/fullcalendar/fullcalendar/issues/6608. The bug is not yet solved by the FC maintainers but there is a (dirty) quick fix available (ref https://github.com/fullcalendar/fullcalendar/issues/6608#issuecomment-954241059). Unfortunately, this fix introduces some visual regressions because it changes the ordering of events inside the view. Take a look at my screenshots below (basically events are primarily ordered by title now). If there is a proper solution/fix for the ticket we may revert our changes.
In my opinion, missing events are more severe than having a slightly different event …
> Fix missing events in week view

- .github/workflows/php-test.yml
Nc server stable20 is not tested anymore, hence the workaround can go.
> Remove php test workaround for stable20

- package-lock.json
- package.json
I bumped jest and babel-jest.
To fix our tests I had to manually add the package `jest-environment-jsdom` as this is not included anymore since jest v28.
I also had to tweak the transformation ignore list of babel-jest.
> Bump jest and babel-jest to 29.0.2

- .github/workflows/php-test.yml
- appinfo/info.xml
- package-lock.json
- package.json
- src/components/AppNavigation/Settings.vue
- src/components/Editor/Resources/ResourceList.vue
- src/components/Editor/Resources/ResourceListSearch.vue
- src/views/Calendar.vue
The new UI is only compatible with 25+. So we need to make hard cut unfortunately. We will maintain the `v3.5` line for 24 and older.
Extracted from https://github.com/nextcloud/calendar/pull/4459.
Version checks for older versions removed.
> Drop Nextcloud 22-24 support

- css/fullcalendar.scss
Ref https://github.com/nextcloud/calendar/pull/4540#issuecomment-1257918178
| --- | --- |
| ![week-before](https://user-images.githubusercontent.com/1479486/192484696-7c9536ea-6735-4c9f-823b-4d75a60cc58f.png) | ![week-after](https://user-images.githubusercontent.com/1479486/192484694-85333232-50b2-4a1f-8ee2-e0b267d6a17e.png) |
| --- | --- |
| ![month-before](https://user-images.githubusercontent.com/1479486/192484646-5535ae7d-f943-4807-bf96-1e5ac4ec9129.png) | ![month-after](https://user-images.githubusercontent.com/1479486/192484640-07466e07-52d3-4790-8a0f-b8ae2ca3248b.png) |
> Add primary light background to month week and header

- css/app-navigation.scss
Fix https://github.com/nextcloud/calendar/issues/4524
Fix https://github.com/nextcloud/calendar/issues/4523
| --- | --- |
| ![before](https://user-images.githubusercontent.com/1479486/191466397-33c2b0b2-ddb5-4405-9095-ddad05c788f6.png) | ![after](https://user-images.githubusercontent.com/1479486/192509451-8f5759fb-5d96-4fdb-bb05-e831d04069c8.png) |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/1479486/191468514-d1f6da33-055a-4a1b-8064-bc7e1cfabee9.png) | ![after](https://user-images.githubusercontent.com/1479486/192509783-809665ea-59bb-4dea-8b39-ae4aeee057d3.png) |
> Fix padding of left sidebar header

- src/components/Editor/Properties/PropertySelectMultiple.vue
- src/components/Editor/Properties/PropertySelectMultipleColoredTag.vue
This PR sketches a possible solution to fixes #3939 and fixes #3802. However, there might be better/easier ways to fix this.
The underlying issue was a binding problem in the Multiselect controls: The bound data source (the event's categories) is changed in the `selectValue` handler. As far as I understand, this causes rerendering inside the handler. That is why the selection does not complete and categories can be selected multiple times.
This is solved by having the Multiselect controls work on their own data (`value`). The event's categories are synchronized on startup and upon selection/deselection.
However, this proposal needs more attention. The following problems need to be addressed:
* After opening an event, the category list is not collapsed, but squeezed in.
* See warnings in …
> Fix category selection

- lib/Service/Appointments/BookingCalendarWriter.php
- lib/Service/Appointments/BookingService.php
- lib/Service/Appointments/MailService.php
- tests/php/unit/Service/Appointments/BookingServiceTest.php
- tests/php/unit/Service/Appointments/MailServiceTest.php
Fixes #3855
| Before  | After |
| ------------- | ------------- |
| Subject: Your appointment "Have Lunch With Me" needs confirmation | Subject: Your appointment "Have Lunch With Me" with admin needs confirmation |
| ![image](https://user-images.githubusercontent.com/7427347/193627773-bb43a644-553a-4b6f-a8c6-84c835efc614.png)  |  ![image](https://user-images.githubusercontent.com/7427347/193628163-aa658334-1bd4-43f8-b38a-43bfaf2d093b.png) |
New booking info email:
> Add booking email with ics attachment

- .github/dependabot.yml
And assign reviewers as per https://github.com/nextcloud/groupware/issues/54.
> Ask Dependabot for GH action updates

- package-lock.json
- package.json
~The release of `@fullcalendar/vue` v5.11.3 is still pending.~
**EDIT:** Turns out that a release of the vue package is not required.
> Bump @fullcalendar and peers from 5.11.2 to 5.11.3

- src/components/CalendarGrid.vue
> Only add title to event order when we're using the week-view

- src/views/Appointments/Overview.vue
Fix #4638
It works again but we should iterate the design once more with our designers because the page layout doesn't fit the new design too well. Scrolling was broken too but works now.
We should switch to the new `NcGuestContent` component ASAP.
| --- | --- |
[appt-overview-scrolling.webm](https://user-images.githubusercontent.com/1479486/196430753-b12cd627-d144-43d0-97ea-a106bef62864.webm)
> Fix appointment overview page design

- src/components/Appointments/AppointmentDetails.vue
> Fix appointment details styling when in a small screen 

- lib/Service/Appointments/MailService.php
- tests/php/unit/Service/Appointments/MailServiceTest.php
> Remove duplicate location in booking confirmation email

- lib/Dashboard/CalendarWidget.php
Follow up to dashboard api.
Tested also with iOS.
@ChristophWurst please backport it to next minor release
> Set dashboard options for rounded icons

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
Before | After
-|-
Please review @raimund-schluessler @JuliaKirschenheuter @nimishavijay :)
Resulting color & contrast:
> [stable3.5] Fix contrast issue with share icon

- .github/workflows/php-test.yml
For https://github.com/nextcloud/groupware/issues/40
> The early bird catches the PHP8.2 bug
> Include PHP8.2 in CI test matrix

- src/components/AppointmentConfigModal.vue
to 'Appointment Name' to avoid translation errors to 'Surname' in UK English
| Before: | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/7427347/199976005-3e7c027e-1968-4a31-bde1-cc86e24dbdb2.png) | ![image](https://user-images.githubusercontent.com/7427347/199976516-e2df7e45-0c0b-455e-bd85-98c089469314.png)|
> Change Appointment Config 'name' label

- src/store/calendarObjectInstance.js
Ref https://github.com/nextcloud/calendar/issues/3863#issuecomment-1315672382   
Ref https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcical/d7f285da-9c7a-4597-803b-b74193c898a8
Followup to https://github.com/nextcloud/calendar/pull/3924
> Delete X-ALT-DESC property value on changing the description

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/EditCalendarModal.vue
- src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
- src/components/AppNavigation/EditCalendarModal/ShareItem.vue
- src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
- src/store/calendars.js
- src/views/Calendar.vue
Fix #4124  
Fix #4711 
**WIP**
| Calendar list item | Modal |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1479486/201921138-40c9da58-07a1-4231-94bc-29454fe1ee6b.png) | ![image](https://user-images.githubusercontent.com/1479486/201912057-cfd44336-9fdb-4bb5-b986-155aba47e155.png) |
There is no three dot menu anymore in the calendar list. There will be a single pencil icon/button which opens the modal.
> Move calendar sharing and settings to a modal

- css/dashboard.css
Second attempt. ;-)
This should fix the black calendar icon and leave the icon in the customization modal untouched.
> Fix black calendar icon on dashboard widget in dark mode

- src/components/Appointments/AppointmentBookingConfirmation.vue
- src/views/Appointments/Booking.vue
~Requires https://github.com/nextcloud/nextcloud-vue/pull/3369~
Partially reverts https://github.com/nextcloud/calendar/pull/4628 and https://github.com/nextcloud/calendar/pull/4593
[appointments.webm](https://user-images.githubusercontent.com/1479486/205261593-cb7ba1d7-f57d-41fa-b77a-ccd03310c9e8.webm)
> Use NcGuestContent for public appointment pages

- src/components/Shared/DatePicker.vue
hack approved by John 
before
after
the popover jumps a bit when clicking, that is fixed on vue 7.1.0
needs
> Fix timezone multi-select popup

- .github/workflows/lint-info-xml.yml
Ref https://github.com/nextcloud/groupware/issues/41
To maintain fewer actions in our repository.
> ci: use shared workflow for appinfo lint

- .github/workflows/lint-php-cs.yml
Ref https://github.com/nextcloud/groupware/issues/41
To maintain fewer actions in our repository.
> ci: use shared workflow for php-cs

- src/components/AppNavigation/EditCalendarModal.vue
Fix #4844
We shouldn't use a vue-router link (`:to`) if we just want to trigger a download.
> fix: calendar export button

- .github/workflows/package.yml
Backport of https://github.com/nextcloud/calendar/pull/4878
Updating krankerl is required due to its dependency on openssl.
This fixes the package workflow.
> [stable4.2] ci(package): update ubuntu and krankerl

- .github/workflows/package.yml
Backport of https://github.com/nextcloud/calendar/pull/4878
Updating krankerl is required due to its dependency on openssl.
This fixes the package workflow.
> [stable3.5]  ci(package): update ubuntu and krankerl

- src/components/AppNavigation/EditCalendarModal.vue
Fix https://github.com/nextcloud/calendar/issues/4890
Thanks to @raimund-schluessler for spotting the issue.
> fix: debounce calendar modal save and edit methods

- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/models/calendarShare.js
- src/store/calendars.js
- src/utils/attendee.js
- src/utils/color.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- src/views/Calendar.vue
Fallback assumes no privilege given.
Related: https://github.com/nextcloud/calendar/issues/4904
Fixes https://github.com/nextcloud/calendar/issues/4843
Author-Change-Id: IB#1126265
Signed-off-by: Pawel Boguslawski <pawel.boguslawski@ib.pl>
> can_subscribe_link loadstate fallback added

- .github/workflows/lint.yml
- .github/workflows/php-test.yml
- PHP 7.4 can't be tested against server master as is it isn't supported anymore. But we can at least test it against server stable25.
- PHP 8.2 doesn't need to be tested against as it isn't supported by this branch.
This also saves some runner time.
> [stable4.2] chore: cleanup php versions in workflows

- src/dashboard.js
Save some time on the initial page load as js files need to be parsed by the browser even though they are cached. This also has the benefit that the js is only loaded if a user actually uses the calendar widget.
> perf: Lazy load dashboard components

- src/components/AppNavigation/EditCalendarModal.vue
- src/components/Editor/Properties/PropertyColor.vue
Fix #5013
| Before | After | 
| --- | --- |
| ![grafik](https://user-images.githubusercontent.com/1479486/220873850-f56f5658-1b1a-4e5b-8001-7a6fcb77248d.png) | ![grafik](https://user-images.githubusercontent.com/1479486/220873519-84e608ff-9e9b-42ca-9168-ec8cbf3d835c.png) |
> fix: bring back advanced color picker fields

- src/services/attachmentService.js
Attachments feature is broken when hosting the server under a custom web root.
> fix(attachments): generate proper urls to dav service

- lib/Notification/Notifier.php
- tests/php/unit/Notification/NotifierTest.php
Notifications on appointment bookings weren't dispatched because of undefined array key errors in the removed code.
Problematic line:
`$replacements[] = $parameter[$placeholder];`
All rich parameters are automatically replaced by the INotification class. I guess the removed statements were debugging leftovers.
1. Create some appointment config.
2. Book and confirm an appointment.
3. **Here:** Observe that a (browser/client) notification is shown.
4. **Main:** No notification will be shown because undefined array key errors. 
This works best if the account owning the appointment config is setup in a desktop client. Browser notifications tend to be a bit delayed sometimes.
> fix(appointments): calendar booking notifications

- src/views/EditSidebar.vue
Fix https://github.com/nextcloud/calendar/issues/3421
The start date has to be converted to the correct timezone before formatting it.
| Before | After
| --- | --- |
| ![before](https://user-images.githubusercontent.com/14975046/129847065-8ce772e4-585c-4947-82ac-09f67d1c4f04.png) | ![grafik](https://user-images.githubusercontent.com/1479486/228017093-3fb9fb47-4ce3-43a6-abf6-e1e611325427.png) |
> fix: sidebar editor subtitle not respecting event's timezone

- src/components/CalendarGrid.vue
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/fullcalendar/localization/dateFormattingConfig.js
- src/fullcalendar/localization/localeProvider.js
- src/utils/moment.js
Fixes #2663
This is my first commit, so please bear with me if I have made some mistakes 😄 .
Before: locale was not respected, fullCalendar displayed dates and time according to language
Now: Dates and times are now rendered by the two new functions in the options object.
I might have missed some things and this pull request does not currently have tests, as I do not know what is normally tested and how it is tested.
> Respect locale when displaying date and time in calendar

- src/components/Editor/Attachments/AttachmentsList.vue
- src/views/Calendar.vue
Hello! Fixes this - https://github.com/nextcloud/calendar/issues/5073
So far, I can't test it definitively, as there is a little problem with nextcloud-vue, which is solved here: https://github.com/nextcloud/nextcloud-vue/pull/3907 
However, I've moved the creation of the folder when the attachment is loaded, and also added an option to check the status of the folder's creation to reduce the number of requests when loading attachments before reloading the page.
> Creating attachments folder when uploading attachments

- src/components/AppNavigation/EditCalendarModal.vue
This pull request fixes issue #4864. By removing the use of debounce, the user can preview different colors for the calendar through the color picker, closing it when ready to save the edits.
Possible regression of https://github.com/nextcloud/calendar/pull/4515
> fix: calendar color picker

- src/components/AppNavigation/EditCalendarModal/ShareItem.vue
Fixes: #4713
Change 
`An error occurred, unable to change the unshare the calendar.` 
to 
`An error occurred while unsharing the calendar.`
> fix: improve grammar

- css/import.scss
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>
**Before :** 
**After :** 
Note : I notice that the file is a .css and that it's content is written in SCSS. Should I run a "npm run sass" ?
> Fix 2 import buttons alignment in calendar import modal

- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Db/Booking.php
- lib/Events/AppointmentBookedEvent.php
- lib/Listener/AppointmentBookedListener.php
- lib/Migration/Version4004Date20230414163505.php
- lib/Service/Appointments/AppointmentConfigService.php
- lib/Service/Appointments/BookingCalendarWriter.php
- lib/Service/Appointments/BookingService.php
- lib/Service/Appointments/MailService.php
- package-lock.json
- package.json
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/CheckedDurationSelect.vue
- src/components/AppointmentConfigModal/TextInput.vue
- src/models/appointmentConfig.js
- src/store/settings.js
- tests/php/unit/Service/Appointments/BookingServiceTest.php
Fixes https://github.com/nextcloud/calendar/issues/3480
> Create Talk rooms for appointments

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
This is the MVP version of https://github.com/nextcloud/calendar/issues/962. We plan to add an advanced modal to our app later so users don't have to leave the page.
| ![Bildschirmfoto vom 2023-04-27 09-24-53](https://user-images.githubusercontent.com/1374172/234790509-daa0ed4d-28b6-4866-a03a-1d4009bb4a0d.png) | ![Bildschirmfoto vom 2023-04-27 09-24-06](https://user-images.githubusercontent.com/1374172/234790448-7f4ff7cb-5ff9-4385-9f75-8b58eddfcff1.png) |
> feat: Add link to the Thunderbird holiday calendar page

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/Subscription/HolidaySubscriptionPicker.vue
- src/resources/holiday_calendars.json
- src/services/caldavService.js
- src/store/calendars.js
For https://github.com/nextcloud/calendar/issues/962
> feat(webcal): Thunderbird holiday subscription picker

- css/public.scss
- lib/Controller/PublicViewController.php
- tests/php/unit/Controller/PublicViewControllerTest.php
The public calendar view used 'base' `Template` responses, preventing the footer that's being used on other public sharing pages from showing. This makes use of `PublicTemplateResponse` to show it automatically. It's however hidden (unchanged) on embed view.
Reference: https://help.nextcloud.com/t/feature-request-impressum-and-privacy-declaration-links/161162
> fix(Public-Sharing): Show footer with server details and eventual ToS through PublicTemplateResponse

- src/utils/attendee.js
- tests/javascript/unit/utils/attendee.test.js
There is an issue when you upload a new ics file to nextcloud calendar that does not contain attendees.
Since there is an assumption that the attendee is going to be a string (and not undefined), the tooltip crashes when you try to edit an event.
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
at b9 (attendee.js:30:10)
at o.userAsAttendee (EditorMixin.js:234:22)
at e.get (vue.runtime.esm.js:3446:33)
at e.evaluate (vue.runtime.esm.js:3547:27)
at o.userAsAttendee (vue.runtime.esm.js:5537:25)
at o.isViewedByAttendee (EditorMixin.js:222:16)
at e.get (vue.runtime.esm.js:3446:33)
at e.evaluate (vue.runtime.esm.js:3547:27)
at o.isViewedByAttendee (vue.runtime.esm.js:5537:25)
at o.<anonymous> (EditSimple.vue:1:4915)
```
This PR should fix this by coercing non strings to …
> Fix issue with Attendee not being string crashing tooltip

- src/components/Subscription/HolidaySubscriptionPicker.vue
Fixes https://github.com/nextcloud/calendar/issues/5192
| ![Bildschirmfoto vom 2023-05-04 12-51-34](https://user-images.githubusercontent.com/1374172/236184155-97004ab5-5df5-4e3f-9ac0-0de0607d83b3.png) | ![Bildschirmfoto vom 2023-05-04 12-47-58](https://user-images.githubusercontent.com/1374172/236184161-6df90564-9902-4a43-8e02-2521734a4a95.png) |
> feat(webcal): Name button *Subscribed* for existing calendars

- src/mixins/EditorMixin.js
- src/store/principals.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Check if the calendar is read-only first to avoid error due to non-existent currentUserPrincipal which causes endless loading on events with atendees in publicly shared calendars.
This should resolve issues #4011 and #4706
Closes #4011
Closes #4706
Closes #4169
> fix: userAsAttendee failing in case of public links

- src/components/Shared/CalendarPicker.vue
Fixes #5223 and #4697
See discussion on #5223
Basically, 'multiple' calendar pickers should not be disabled when the number of calendars is 2 or fewer. Because 'multiple' select calendars can have 0, 1, 2... calendars selected. So they should only be disabled if calendars < 1
> fix: Do not disable multiple calendar picker with one option

- lib/Service/Appointments/BookingCalendarWriter.php
This is a really simple fix for #4263 -  I won't argue that this is the best or most 'complete' fix, but it's already a big improvement on having *all* appointments use the same name.
The format is now: `[DisplayName] - [AppointmentName]`
Throwing this out there in the hopes it can get merged quickly. If people still think having a field to enter 'topic' or 'meeting title' is worthwhile, then #4263 can be kept open for that. :)
> Include name of booking creator in event name in calendar

- lib/Service/Appointments/MailService.php
- src/components/Appointments/AppointmentBookingConfirmation.vue
Does two things to fix #5189
1. Uses an 'email' icon instead of a 'check' icon on the page after submitting an appointment request. The checkmark is confusing and implies that the booking has been confirmed.
Before:
After:
2. Moved the 'confirm' button further up in the confirmation email, so people can see it more clearly that they have to click it
Problem:
I would also say the wording on the page on no.1 should also be improved, but I'm not sure how that works with translations so I've left it for now.
> Make it clearer that confirmation is needed for appointments

- package-lock.json
- package.json
I replaced the obsolete package babel-core with @babel/core and properly added babel-jest to the dev dependencies.
Following the guide at https://jestjs.io/docs/getting-started#using-babel
Required for https://github.com/nextcloud/calendar/pull/5281
> chore(deps-dev): fix babel and jest deps and peers

- composer.json
- tests/php/integration/Composer/AutoloaderTest.php
Fixes https://github.com/nextcloud/calendar/issues/5191
https://github.com/nextcloud/server/pull/6853 + authoritative class loaders for apps distributed via the app store is problematic.
What I have tested
* `composer/autoload.php` + authoritative class loader optimization: :boom: (main)
* `composer/autoload.php` + apcu class loader optimization: :sunglasses: 
* `composer/autoload.php` + basic class map optimization: :sunglasses: (here)
* no `composer/autoload.php`: :sunglasses: 
To do
1) Run ``composer i``
2) ``composer run test tests/php/integration/Composer``
> fix: Allow dynamic autoloading for classes added during upgrade

- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderNewEvent.vue
Note : It may not affect negatively previous major versions (just a shorter wording)
@nextcloud/designers
> "Event" instead of "New event" to fit new design (since Nextcloud 27)

- src/mixins/EditorMixin.js
- tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
The problem was in the "beforeRouteLeave" because it didn't contemplated the case when the from route was the Popover to create the event and the to route was the popover to edit an existing event. 
Fixes https://github.com/nextcloud/calendar/issues/3820
> Fix creating empty events

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/Subscription/HolidaySubscriptionPicker.vue
"Holiday" (only) and "Public holiday" don't have the same meaning.
"Public holiday" is appropriate (and "Holiday" only is not).
> "Public" holiday calendar

- lib/Controller/ViewController.php
- lib/Service/CategoriesService.php
- src/components/Editor/Properties/PropertySelectMultiple.vue
- src/components/Editor/Properties/PropertySelectMultipleColoredOption.vue
- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
- tests/php/unit/Controller/ViewControllerTest.php
- tests/php/unit/Service/CategoriesServiceTest.php
This commit add all available "collaborative tags" and all already used categories into option groups of the tags-menu of the side-bar editor.
Determining the set of already used categories is a little bit ugly: it used the oc_calendarobject_props table which might be considered "internal". However, this is the Nextcloud calendar app which only talks to the Nextcloud calendar server. So using this "internal ingredient" might be acceptable.
This commit addresses and is a related to a couple of open issues:
nextcloud/calendar#3735 Calendar Categories: Propose Categories already used
- this should be fixed by this commit
nextcloud/calendar#1644 Add own categories, delete default ones
- this is partly fixed in the sense that collaboritive tags are now also proposed as calendar categories.
- …
> Augment the category menu by system tags and already used categories

- .github/workflows/psalm-matrix.yml
- .nextcloudignore
- composer.json
- lib/BackgroundJob/CleanUpOutdatedBookingsJob.php
- lib/Controller/BookingController.php
- lib/Controller/PublicViewController.php
- lib/Controller/ViewController.php
- lib/Dashboard/CalendarWidget.php
- lib/Db/AppointmentConfigMapper.php
- lib/Db/BookingMapper.php
- lib/Listener/UserDeletedListener.php
- lib/Service/Appointments/DailyLimitFilter.php
- lib/Service/Appointments/MailService.php
- psalm.xml
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
- tests/psalm-baseline.xml
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
Closes https://github.com/nextcloud/calendar/issues/3765
For code QA. There are existing issues Psalm could locate. Most were fixable. The four remaining ones were added to the baseline.
> chore: Set up static analysis

- src/views/EditSimple.vue
Fix: #4598
1. Create an event
2. Open the event again in simplified editor
3. Duplicate event
4. Click "More" to show sidebar editor
5. Change something
6. Save Event
On main this leads to updating the original event.
In this PR a new event is created (with the copied and edited data)
> fix(duplicateEvent): Open duplicate in sidebar not original

- appinfo/routes.php
- lib/Controller/SettingsController.php
- package-lock.json
- package.json
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderViewMenu.vue
- src/components/AppNavigation/EmbedHeader/EmbedHeaderViewButtons.vue
- src/components/AppNavigation/Settings/ShortcutOverview.vue
- src/components/CalendarGrid.vue
- src/components/Shared/DatePicker.vue
- src/filters/dateRangeFormat.js
- src/fullcalendar/localization/dateFormattingConfig.js
- src/utils/date.js
Closes #159
Note: Shortcut for ListView is changed from 4 to 5 for consistency.
It could use a little style enhancement.
FullCalendar provides two "year" views: [this one (multiMonthYear)](https://fullcalendar.io/docs/multimonth-grid-demo) and [another one (dayGridYear)](https://fullcalendar.io/docs/daygridyear-view-demo). This one seems more suitable.
> Introduce year grid view (with FC multiMonthYear plugin)

- src/components/Appointments/AppointmentDetails.vue
The server can take a bit of time to response after clicking the 'Book the appointment button' (see below video - might be my server/email server is slow, hence why it taskes 8+ seconds!). To improve UX and to avoid the user clicking the button multiple times, we should disable the button while loading and/or add a loading icon.
https://github.com/nextcloud/calendar/assets/150431/ceacf31a-7ed6-47d9-8288-435a86d8f53c
Ideally, the code would also either replace the 'Book the appointment' text with a loading spinner, or grey out the entire popup window and add a loading icon, but that's beyond my ability 😿
> feat(appointments): Disable the booking button while loading

- src/mixins/EditorMixin.js
Followup to #5161
The categories are not injected on some views, e.g. the public view.
1. Create a calendar and share it publicly via a link.
2. Open the calendar in a private/anonymous tab.
3. Observe how shit breaks because the initial state for categories is missing and no fallback is specified.
> fix(categories): fall back to empty array

- lib/Controller/PublicViewController.php
- lib/Controller/ViewController.php
- src/store/settings.js
- src/views/Calendar.vue
- src/views/EditSidebar.vue
- tests/javascript/unit/store/settings.test.js
Revival of #4401 
Tested and works.
This PR was approved and then lost. I rebased it and fixed all conflicts.
> feat(editor): implement app config to hide resources tab

- css/app-navigation.scss
- css/fullcalendar.scss
This fixes the leftovers of https://github.com/nextcloud/groupware/issues/2
The only part where this is still a problem is in month view in mobile mode, but all the rest is significantly better so I would consider it done for now.
https://github.com/nextcloud/calendar/assets/925062/a04a018a-f41d-4b8e-9540-c1a3af597f43
https://github.com/nextcloud/calendar/assets/925062/1a7ceb80-8fd4-4c3b-a967-40561fc8a26b
> Fix navigation toggle overlap

- css/app-navigation.scss
To illustrate the issues, the view switcher on the right is in hovered state:
- More whitespace to the top of the navigation than to the left
- Using hardcoded values instead of variables
- "Event" and "Today" vertically not aligned with view switcher
Before | After
-|-
> Fix navigation button positioning

- src/services/talkService.js
- src/store/calendarObjectInstance.js
Fixes https://github.com/nextcloud/calendar/issues/5376
> feat(talk): Make event attendees Talk room participants

- src/components/Editor/Invitees/InviteesList.vue
- src/services/talkService.js
Fall back to description if location is filled, e.g. for a hybrid event.
This contributes part 2 of https://github.com/nextcloud/calendar/issues/5389.
1. Set up Calendar and Talk
2. Create an event
3. Click the *Create Talk room* button
On `main` there will be an URL inserted into the description.
On this branch the URL will be written to the location if it's empty or not set. If it is, the URL is appended to the description.
> feat: Write Talk URL into location, not description

- css/calendar.scss
- css/props-linkify-links.scss
- package-lock.json
- package.json
- src/components/Editor/Properties/PropertyText.vue
- src/mixins/PropertyLinksMixin.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
Fix #5389 
One way to resolve #5030
> make links clickable in locations and description areas - rel: #5030

- appinfo/info.xml
- lib/AppInfo/Application.php
- lib/Controller/AppointmentConfigController.php
- lib/Db/AppointmentConfig.php
- lib/Db/AppointmentConfigMapper.php
- lib/Db/Booking.php
- lib/Events/BeforeAppointmentBookedEvent.php
- lib/Listener/AppointmentBookedListener.php
- lib/Migration/Version4050Date20230614163505.php
- lib/Service/Appointments/AppointmentConfigService.php
- lib/Service/Appointments/BookingCalendarWriter.php
- lib/Service/Appointments/BookingService.php
- lib/Service/Appointments/MailService.php
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/CheckedDurationSelect.vue
- src/components/AppointmentConfigModal/TextInput.vue
- src/models/appointmentConfig.js
- src/store/settings.js
- tests/php/unit/Service/Appointments/BookingServiceTest.php
- tests/psalm-baseline.xml
Reverts nextcloud/calendar#5306 and brings back https://github.com/nextcloud/calendar/pull/4025
1) Install and enable Calendar and Talk
2) Create an appointment config in calendar, tick the *Create talk room* checkbox
3) Open the booking URL in a private tab
4) Book and confirm an appointment
5) Open Talk as the organizer
6) See the Talk conversation created for the event
> Revert "Revert "Create Talk rooms for appointments""

- CHANGELOG.md
Resolves https://github.com/nextcloud/calendar/issues/5402
> build: release v4.5.0-beta2

- src/components/Appointments/AppointmentDetails.vue
- src/views/Appointments/Booking.vue
> Fix appointment booking loading

- css/app-sidebar.scss
Fix #5444
Backports are not needed as stable4.4 and stable3.5 are not affected.
| --- | --- |
| ![Screenshot_20230904_113259](https://github.com/nextcloud/calendar/assets/1479486/5779cfb5-1f5f-4efd-b569-8d2b43ca282b) | ![Screenshot_20230904_113204](https://github.com/nextcloud/calendar/assets/1479486/3f6b8905-9a9f-4656-a423-8b0ddeaefdc9) |
> fix(editor): top right actions not positioned properly

- lib/AppInfo/Application.php
- lib/Controller/ViewController.php
- lib/Dashboard/CalendarWidget.php
- lib/Dashboard/CalendarWidgetV2.php
- psalm.xml
- tests/psalm-baseline.xml
Ref https://github.com/nextcloud/server/pull/39937
The old, bundled widget has to stay until we exclusively support the corresponding server versions.
> perf(dashboard): implement widget item api v2

- src/components/Editor/Invitees/InviteesList.vue
Only show it for organizers. The server doesn't process the request for others.
Fixes https://github.com/nextcloud/calendar/issues/3149
> fix(scheduling): Disable free/busy for attendees

- src/components/Editor/Invitees/InviteesList.vue
- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
> Shared calendars shouldn't allow adding attendees if the calendar is not yours

- src/components/Editor/AvatarParticipationStatus.vue
Instead of broken user avatars. This is not a comprehensive fix but a workaround for #3099, which is not trivial to fix.
| ![Bildschirmfoto vom 2023-09-06 09-16-11](https://github.com/nextcloud/calendar/assets/1374172/7b9c1c9a-e780-4b5f-b9a8-6d23e22ba5b4) | ![Bildschirmfoto vom 2023-09-06 09-13-32](https://github.com/nextcloud/calendar/assets/1374172/c9b36e8d-5d27-4de7-9721-3cdee05dc238) |
> fix(scheduling): Use attendee placeholder avatars

- src/utils/moment.js
> simpler locale fall back code

- src/mixins/EditorMixin.js
Companion for https://github.com/nextcloud/server/pull/40301
Handle exceptions that may happen when resolving recurrence next to an actual recurrence id.
| ![image](https://github.com/nextcloud/calendar/assets/3902676/55805b21-d51b-48d5-b7a4-6cc3f579f999) | ![image](https://github.com/nextcloud/calendar/assets/3902676/579c04f1-238b-4c5c-8558-37dcde5908bc) |
**How to test**
- You need an invalid object id and recurrence next to trigger the state.
- Have the activity app
- Create an event
- Patch apps/dav/lib/CalDAV/Activity/Provider/Event.php with the patch below
- Open activity
- Click on calendar event
- Without the patch: Endless loading animation
**Patch**
```
Index: apps/dav/lib/CalDAV/Activity/Provider/Event.php
IDEA additional info:
Subsystem: …
```
> fix: error handling for exceptions for recurrence next

- css/fullcalendar.scss
Fix https://github.com/nextcloud/calendar/pull/5475#issuecomment-1730188885
Close https://github.com/nextcloud/groupware/issues/2
> Fix overlapping toggle also in Firefox

- lib/Dashboard/CalendarWidget.php
- lib/Dashboard/CalendarWidgetV2.php
The dashboard will now correctly show and sort recurring events.
This also works without the server patch and will just hide outdated recurrences in this case. I think we should merge this asap to have proper event ordering.
> fix(dashboard): properly handle recurring events

- src/components/Editor/Invitees/InviteesList.vue
Unification of spelling in Transifex.
> Unification of spelling

- lib/Controller/AppointmentController.php
- lib/Controller/EmailController.php
- lib/Service/Appointments/BookingCalendarWriter.php
- lib/Service/Appointments/MailService.php
- tests/php/unit/Controller/EmailControllerTest.php
- tests/php/unit/Service/Appointments/MailServiceTest.php
ref https://github.com/nextcloud/groupware/issues/53
> use \OCP\IUserManager::getDisplayName

- lib/Service/Appointments/BookingCalendarWriter.php
- lib/Service/Appointments/MailService.php
- tests/php/unit/Service/Appointments/MailServiceTest.php
> revert unecessary refactoring of getDisplayName()

- package-lock.json
- package.json
Ref https://github.com/nextcloud/calendar-availability-vue/pull/165
| --- | --- |
| ![before](https://user-images.githubusercontent.com/6078378/270280979-1698704b-6277-4b78-95c3-483c702229f5.png) | ![grafik](https://github.com/nextcloud/calendar-availability-vue/assets/1479486/af3a7e2f-c436-47a9-b38b-29d0a01a94c5)  |
> [stable5.4] chore(deps): bump @nextcloud/calendar-availability-vue to 1.0.1

- .github/workflows/lint-php.yml
- .github/workflows/php-test.yml
- appinfo/info.xml
- composer.json
- composer.lock
> Add PHP8.3 support

- src/fullcalendar/interaction/eventDrop.js
Following change resets participation state of all attendees (except organizer) on eventDrop to NEEDS-ACTION. Considering that eventDrop would be always a significant change. This will trigger resending of an invitation.
This is a workaround for sabre-dav doesn't respecting [RFC 6638 3.2.8](https://datatracker.ietf.org/doc/html/rfc6638#section-3.2.8): https://github.com/sabre-io/dav/issues/1282
Addresses: https://github.com/nextcloud/server/issues/13862
> Reset attendees participation on eventDrop

- lib/Service/Appointments/BookingCalendarWriter.php
0) Have Talk set up
1) Create an appointment config, enable the Talk link integration
2) Open the booking page
3) Book
4) Confirm
4) Open the event as organizer
main: Event has no location set
here: Event has location set to the Talk URL
> fix(appointments): Write Talk link to event

- lib/Service/Appointments/MailService.php
I noticed that the confirmation email I receive when somebody else books an appointment has the from/to names mixed up.
Right now it looks like this:
To clarify, it's set as:
```
From: MY NAME <no-reply@nextcloud.address>
To: PERSON WHO BOOKED <my-email@domain.com>
```
but it should be:
```
From: PERSON WHO BOOKED <no-reply@nextcloud.address>
To: MY NAME <my-email@domain.com>
```
This is really confusing, the names are mixed so it looks like the email has been send *from* me but *to* the person who booked. That's the case for all the other emails (to the person who booked) but this one should be the other way around :)
> fix(appointments): switch to/from order for the booking information email (to the organizer)

- appinfo/routes.php
- lib/Controller/ContactController.php
- lib/Controller/ViewController.php
- lib/Service/ServiceException.php
- psalm.xml
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
- src/services/circleService.js
- src/services/isCirclesEnabled.js
- src/store/calendarObjectInstance.js
- tests/php/unit/Controller/ContactControllerTest.php
- tests/php/unit/Controller/ViewControllerTest.php
```
This commit adds support for adding circles as attendees to a calendar event.
The relationship between the imported group and members will be compliant with
the iCal specification.
A circle with the title "testcircle" will be added as an attendee with iCal
attributes "CUTYPE=GROUP` and uri "mailto:circle+CIRCLEID@CIRCLE_INSTANCE".
Members of the circle will be imported as standard attendees. Each member gets
assigned to the circle group entry by assigning them to the group uri using the
iCal member property: "MEMBER='mailto:circle+CIRCLEID@CIRCLE_INSTANCE'".
Searching for circles is only enabled if the circles app is activated.
Circles added to the list of attendees get imported only once and are not
synced yet. While adding a circle, a notice about this is shown to the user.
Only …
```
> feat: Ability to invite circles

- src/components/Editor/Alarm/AlarmListItem.vue
Fix #5617 
https://github.com/nextcloud/calendar/assets/1479486/37192df6-aacc-4bd8-a1bc-0b04e8452d12
> fix(sidebar): hide alarm actions menu when starting to edit

- lib/Controller/ViewController.php
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/components/Subscription/PublicCalendarSubscriptionPicker.vue
- src/store/settings.js
- src/views/Calendar.vue
- tests/javascript/unit/store/settings.test.js
- tests/php/unit/Controller/ViewControllerTest.php
This PR enables the admin to define custom public calendars to be subscribed.
linked to #962, #5167
> Allow to define and subscribe to custom public calendars

- src/components/Editor/Attachments/AttachmentsList.vue
- src/services/attachmentService.js
Firefox does not have FileList.forEach.
Fixes https://github.com/nextcloud/calendar/issues/5655
Additionally, I've added try-catch with an error toast for when upload still fails.
1) Start Firefox
2) Create an event
3) Open the sidebar
4) Upload a local attachment
> fix(attachments): Convert FileList to array for FireFox

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Uploading attachments in Firefox
> Release v4.6.2

- src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
- Share only works by display name right now
- Search by email to share calendar is broken completely as there is a `filterBy` option in [vue-select](https://vue-select.org/api/props.html#filterby) whose return value defaults to `return (label || '').toLocaleLowerCase().indexOf(search.toLocaleLowerCase()) > -1`
- `label` in  our code is set to `displayName` so only search by `displayName` works
- Since we already get our results by searching(DAV & OCS), I don't see why we need the `filterBy` option in the first place
- So I just make the return value `true`
- In case we do need the option, we should make it check for both `displayName` and `email` attributes
> don't filter results while sharing

- src/components/AppointmentConfigModal/Confirmation.vue
Fix: #5664 
|before|after|
|---|---|
|![image](https://github.com/nextcloud/calendar/assets/74607597/6dbe0a14-5cb9-4aaa-aadd-6e776a51711f)|![image](https://github.com/nextcloud/calendar/assets/74607597/08b8fea4-b735-4ce5-a7c1-45f7215551e2)|
> fix(appointments): Fix button style

- src/components/Shared/CalendarPicker.vue
Dav Object contains circular reference which breaks NcSelect  
part of #5648
> fix Circular structure in calendar object

- lib/Controller/AppointmentConfigController.php
- lib/Controller/BookingController.php
- src/components/AppointmentConfigModal.vue
- src/components/Appointments/AppointmentDetails.vue
- src/views/Appointments/Booking.vue
- tests/psalm-baseline.xml
Limits the number of bookings a single user can do.
> fix(appointments): Rate limit config creation and booking

- lib/Controller/AppointmentConfigController.php
- lib/Controller/BookingController.php
- src/components/AppointmentConfigModal.vue
- src/components/Appointments/AppointmentDetails.vue
- src/views/Appointments/Booking.vue
Manual backport of https://github.com/nextcloud/calendar/pull/5680.
NcNotecard doesn't exist for nc/vue 5 so I simplified the HTML.
> [stable3.5] fix(appointments): Rate limit config creation and booking

- src/components/AppNavigation/EditCalendarModal.vue
This mod removes `Share link` action in calendar edit dialog when publishing is disabled for this calendar. Was tested with https://github.com/nextcloud/server/pull/34873 applied to nextcloud-server v28.
Related: https://github.com/nextcloud/server/pull/34873#issuecomment-1408607619
Author-Change-Id: IB#1126264
> Remove Share link action if calendar publishing is disabled

- src/services/talkService.js
Inviting guests to a private group chat has the implication that the Talk room has to be opened up for guests. This is unexpected.
This patch adjusts the logic to only invite guest users if the Talk room is already open for guests. Otherwise they are ignored.
Fixes https://github.com/nextcloud/calendar/issues/5687
Repro steps from https://github.com/nextcloud/calendar/issues/5687
In addition, test it with an open conversation. Guests will be added.
> fix(talk): Only invite guest accounts to open Talk conversations

- src/views/Calendar.vue
The public view of calendars is currently broken. It loads indefinitely because some initial state is missing and breaking the main Calendar view.
Only main seems to be affected.
> fix: missing public calendar initial state

- src/components/AppNavigation/AppointmentConfigList/AppointmentConfigListItem.vue
- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
- src/components/AppNavigation/EditCalendarModal/SharingSearch.vue
- src/components/AppointmentConfigModal/NoEmailAddressWarning.vue
Fix https://github.com/nextcloud/calendar/issues/5694
I tested all migrated components locally for visual regressions.
> chore(vue3): migrate deprecated slot syntax

- webpack.config.js
Due to #5699 
Backports are not necessary.
```
WARNING in ./node_modules/moment/min/moment-with-locales.js 2159:16-50 Module not found: Error: Can't resolve './locale' in '/home/richard/src/nextcloud/master/dev_apps/calendar/node_modules/moment/min'
@ ./node_modules/@nextcloud/moment/dist/index.mjs 1:0-50 2:0-65 6:0-8 9:58-72 9:73-81 15:0-17:2
```
> chore: fix npm build warning about moment locales

- src/components/Appointments/AppointmentDetails.vue
- src/utils/localeTime.js
> fix(appointments): add date to booking detail view

- lib/Service/Appointments/AvailabilityGenerator.php
- lib/Service/Appointments/BookingService.php
- lib/Service/Appointments/DailyLimitFilter.php
- lib/Service/Appointments/EventConflictFilter.php
- lib/Service/Appointments/MailService.php
- lib/Service/Appointments/SlotExtrapolator.php
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
- tests/php/unit/Service/Appointments/DailyLimitFilterTest.php
- tests/php/unit/Service/Appointments/SlotExtrapolatorTest.php
Add moar logging because something is suspicious suspicious.
> enh(appointments): add moar debug logging and overwrite app id

- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/EditCalendarModal.vue
Fix https://github.com/nextcloud/calendar/issues/5755
| --- | --- |
| ![grafik](https://github.com/nextcloud/calendar/assets/1479486/86b10868-ad33-4f2c-b156-6a50754e8e61) ![grafik](https://github.com/nextcloud/calendar/assets/1479486/a69fc352-d156-4e9c-8475-598cbd087b98) | ![grafik](https://github.com/nextcloud/calendar/assets/1479486/da15c442-fa3f-4d2f-9216-c9b4152ed364) ![grafik](https://github.com/nextcloud/calendar/assets/1479486/4bf37de0-b01d-4c0f-ae0b-bb3faca1f066) |
> fix: disable resharing of incoming shared calendars

- src/views/EditSidebar.vue
Just use the user's time zone to display the sub line. This fixes displaying events with custom time zones that might not be known by our global time zone manager, e.g. when they are defined in the event itself.
| --- | --- |
| ![grafik](https://github.com/nextcloud/calendar/assets/1479486/05219c2e-17c2-4374-a9f3-3b606d4e0eec) | ![grafik](https://github.com/nextcloud/calendar/assets/1479486/fc6b89f1-6975-424a-a6a2-87c9d7efe7de) |
The event is in `America/New_York`.
`19:20 Tuesday in New York City` is `01:20 Wednesday in Germany`
Now is 17:20 so the event starts in 8 hours for me in Germany.
Subline: `in 8 hours`
> fix(editor): convert start date to user's tz for the sub line

- src/fullcalendar/eventSources/freeBusyBlockedForAllEventSource.js
Fix https://github.com/nextcloud/calendar/issues/5754
Ref (for the syntax) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator#async_generator_iteration
> fix(freebusy): free for all blocks

- src/components/AppNavigation/Settings.vue
:broom: 
```
$ grep 'nextcloud min-version' appinfo/info.xml
<nextcloud min-version="26" max-version="29" />
```
> chore: remove obsolete server version check

- css/app-settings.scss
- src/components/AppNavigation/Settings.vue
- src/components/Shared/CalendarPicker.vue
- src/models/principal.js
- src/store/calendarObjects.js
- src/store/calendars.js
- src/store/principals.js
- tests/javascript/unit/models/principal.test.js
Resolves https://github.com/nextcloud/calendar/issues/1835
Based on https://github.com/nextcloud/calendar/pull/2331 and https://github.com/nextcloud/calendar/pull/4310
Closes https://github.com/nextcloud/calendar/pull/2331
Closes https://github.com/nextcloud/calendar/pull/4310
Requires:
- https://github.com/nextcloud/cdav-library/pull/871
- https://github.com/nextcloud/server/pull/43745
> feat: add a setting for the default calendar url

- package-lock.json
- package.json
> chore(deps): bump @nextcloud/cdav-library to ^1.3.0

- css/freebusy.scss
- src/components/Appointments/AppointmentDetails.vue
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/components/Editor/Invitees/InviteesList.vue
- src/store/calendarObjectInstance.js
- src/utils/freebusy.js
- src/views/EditSidebar.vue
Fixes #39
| Current state | Goal |
|https://github.com/nextcloud/calendar/assets/40746210/50a499d4-4c40-413e-b171-a8d76843c762|![image](https://github.com/nextcloud/calendar/assets/40746210/f9936455-d227-48b1-b529-d8d2b23b8ec0)| 
Todo list from design team: 
--***Nimisha***
Differences from current free/busy view:
New features:
-- ***Jan***
> Enh: free busy UI

- lib/Service/Appointments/AvailabilityGenerator.php
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Fixes https://github.com/nextcloud/calendar/issues/5791
The rounding by length might lead to more efficient slot generation but it breaks appts.
> fix(appointments): Round by increment

- src/components/Editor/FreeBusy/FreeBusy.vue
- src/components/Editor/Invitees/InviteesList.vue
| <img width="1310" alt="image" src="https://github.com/nextcloud/calendar/assets/40746210/21bfe74a-69b5-42f1-873d-bb66fe1535d3"> | <img width="1310" alt="image" src="https://github.com/nextcloud/calendar/assets/40746210/47068e37-9b96-4b6f-91cf-63b8b8b6f660"> |
Headings will  be fixed with https://github.com/nextcloud/server/issues/43393
> Enh: Improvement to the free/busy ui design

- src/components/Editor/SaveButtons.vue
- src/views/EditSimple.vue
- Move the primary button to the last position
- Grow buttons on the simple editor to prevent their text from being cut off
| Simple | Sidebar |
| --- | --- |
| ![Screenshot_20240306_153130](https://github.com/nextcloud/calendar/assets/1479486/5f3427fd-149d-4940-94d0-786711a1960a) | ![Screenshot_20240306_153154](https://github.com/nextcloud/calendar/assets/1479486/abe7bc05-3087-4e60-9522-7631c37e11b7) |
> fix(editor): grow save buttons and change their order

- lib/Service/Appointments/AvailabilityGenerator.php
- tests/php/unit/Service/Appointments/AvailabilityGeneratorTest.php
Thanks @nickvergessen who figured out that the `ciel()` function wasn't working properly because `(int)` is stronger than `x*y`, so the results were [not correct](https://www.youtube.com/watch?v=Jk6jVl1fAn0)
> fix(appointments): slot generation deviation for increments that don't fit modulo

- src/components/CalendarGrid.vue
- src/fullcalendar/rendering/eventOrder.js
- tests/javascript/unit/fullcalendar/rendering/eventOrder.test.js
The underlying issue has been fixed upstream.
This reverts:
- c5b5f162e0ec5adae9bb57dcf75dfbbaba00afc0 (#4431)
- 5334250382703499a1c832f23a50cd321d712d8a (#4646)
Have a look at the screenshots below. Note that 
1. All events are shown in both before and after screenshots -> no regressions introduced
2. The events are ordered by name again -> old/original sort order restored
> fix: restore original event ordering

- css/app-sidebar.scss
- src/views/EditSidebar.vue
Regression was introduced by de1cf849af30518efd22d32e8f88af93bef00cb1 in combination with the new reference widget. The global stylesheet is imported by the reference entry point and thus overrides some styles in other apps.
1. Install talk.
2. Open a conversation.
3. Look at the sidebar.
> fix: move global sidebar style overrides to sfc

- lib/Dashboard/CalendarWidgetV2.php
It might be confusing to users if the time doesn't update. Ten minutes should be fine from a performance standpoint.
cc @AndyScherzinger as discussed recently
> feat(dashboard): reload widget once every 10 minutes

- tests/php/unit/Controller/BookingControllerTest.php
- tests/php/unit/Dashbaord/CalendarWidgetTest.php
- tests/php/unit/Service/Appointments/BookingServiceTest.php
I don't get why this fails now and worked in the past.
> test: replace \Safe\DateTimeImmutable with \DateTimeImmutable

- src/views/Calendar.vue
Fix #5878
| b | a |
| ![image](https://github.com/nextcloud/calendar/assets/40746210/304501f1-cb90-48ac-aacc-7224c30a5776) | <img width="870" alt="image" src="https://github.com/nextcloud/calendar/assets/40746210/459e79e7-cea6-499b-9222-761997f74aae"> |
> Fix: Hide widget header for non-existent calendars

- src/components/Editor/Invitees/InviteesListSearch.vue
Fixes https://github.com/nextcloud/calendar/issues/5872
NcSelect only shows options that **match the current search input**. If you search for user *Alice* with an email of *accounting@acme.com* you will not see her in the suggestions. If her email is *alice@acme.com* you will.
This change adds the email to the property used for searching so NcSelect shows it again.
> fix(scheduling): Find attendee via email

- css/app-sidebar.scss
- src/components/Editor/Repeat/RepeatFreqInterval.vue
- src/components/Editor/Resources/ResourceListSearch.vue
- src/components/Editor/Resources/ResourceSeatingCapacity.vue
Fixes https://github.com/nextcloud/calendar/issues/5864
Details tab for reminders:
| ![image](https://github.com/nextcloud/calendar/assets/7427347/55edfe0a-1cc1-401b-b4d5-674558ca9fe3) | ![Screenshot from 2024-04-22 17-21-04](https://github.com/nextcloud/calendar/assets/6078378/e23ecdba-5707-4290-9e87-6badb29ae969) | 
Resources tab:
| ![image](https://github.com/nextcloud/calendar/assets/7427347/2c6b3793-0534-4944-a5a9-499f7206eabb) | ![Screenshot from 2024-04-22 17-21-53](https://github.com/nextcloud/calendar/assets/6078378/42116795-899a-44ef-a9a0-f7a19f74abfb) |
> fix(files): replace input fields with `NcTextField`

- src/store/calendarObjects.js
Fix https://github.com/nextcloud/calendar/issues/5942
The feature to set the default calendar is only available in Nextcloud >= 29 so users might be confused by the default calendar choice which they can't influence.
Simply use the old logic (first sorted calendar) on older instances.
> fix: don't apply default calendar on Nextcloud < 29

- src/components/Editor/Properties/PropertySelectMultiple.vue
Fix #5785 
An artifact of the nextcloud-vue migration.
The component is not used anywhere else besides the category select so this is a safe change.
> fix(editor): add and remove categories from events

- src/components/Editor/CalendarPickerHeader.vue
Fix https://github.com/nextcloud/calendar/issues/5855
This is dirty but the `NcActionButton` does not allow custom components inside its default template slot. Only text can be used.
| Light | Dark |
| --- | --- |
| ![picker-light](https://github.com/nextcloud/calendar/assets/1479486/308ea30d-6998-4166-8468-e8a4bab4fa1c) | ![Screenshot_20240503_171632](https://github.com/nextcloud/calendar/assets/1479486/f5954488-36e5-469c-a427-948292a5c9fd) |
> fix(editor): add indicator to calendar picker

- src/components/AppNavigation/Settings.vue
- src/store/calendarObjects.js
Ref https://github.com/nextcloud/calendar/issues/5942
Partially reverts https://github.com/nextcloud/calendar/pull/5790
The default calendar URL from the backend is more restrictive as it is primarily meant for incoming invitations. This commit effectively reverts the editor's calendar picker default choice to how it behaved before v4.7.0.
As discussed in a meeting with Christoph.
> fix(editor): don't respect default calendar in the calendar picker

- src/components/CalendarGrid.vue
Follow-up to  https://github.com/nextcloud/calendar/pull/5891
Reverts https://github.com/nextcloud/calendar/pull/5995
I converted the FullCalendar options to a computed prop again. It still works in private and public widgets. I assume this was just an oversight. This also means that we can get rid of some reactivity hacks as the computed prop is now properly reactive again.
1. Open the calendar app.
2. Switch to  month view.
3. Navigate to the next month using the top left navigation buttons.
4. Click on some day.
5. Observe the grid changing back to the previous month which includes today. 
Things that I tested successfully:
1. Main calendar grid view in the app.
2. Resize observer still works (see #5995).
6. Private widgets in a Talk room (internal link).
7. Public widgets in a Talk …
> fix: navigation when clicking on the grid on a custom week/month

- src/store/calendarObjectInstance.js
- src/utils/alarms.js
Fixes https://github.com/nextcloud/calendar/issues/3040
> fix(alarms): also update DISPLAY alarms

- src/components/Editor/Properties/PropertySelectMultiple.vue
Fix #5993
https://github.com/nextcloud/calendar/assets/1479486/20158423-ac96-4c3b-9419-df74c32fb517
> fix(editor): creating custom categories

- package-lock.json
This audit fix resolves 3 of the total 12 vulnerabilities found in your project.
* [express](#user-content-express)
* [follow-redirects](#user-content-follow-redirects)
* [webpack-dev-middleware](#user-content-webpack-dev-middleware)
* Express.js Open Redirect in malformed URLs
* Severity: **moderate** (CVSS 6.1)
* Reference: [https://github.com/advisories/GHSA-rv95-896h-c2vc](https://github.com/advisories/GHSA-rv95-896h-c2vc)
* Affected versions: <4.19.2
* Package usage:
* `node_modules/express`
* follow-redirects' Proxy-Authorization header kept across hosts
* Severity: **moderate** (CVSS 6.5)
* Reference: [https://github.com/advisories/GHSA-cxjh-pqwp-8mfp](https://github.com/advisories/GHSA-cxjh-pqwp-8mfp)
* Affected versions: <=1.15.5
* Package usage:
* `node_modules/follow-redirects` …
> [stable4.7] Fix npm audit

- src/components/Shared/DatePicker.vue
Fix https://github.com/nextcloud/calendar/issues/6025
https://github.com/nextcloud/calendar/assets/1479486/9eb7422b-2a55-453d-a801-18f6b1f55d53
https://github.com/nextcloud/calendar/assets/1479486/cd1d4f57-67f4-40a3-ac92-566af5782cd6
> fix: time zone picker when using the simple editor

- src/components/Editor/CalendarPickerHeader.vue
Only happens when there is a single calendar available and the calendar picker is "disabled".
| --- | --- |
| ![grafik](https://github.com/nextcloud/calendar/assets/1479486/db2f32ce-39b6-4ccf-bac6-a02f214bb633) | ![grafik](https://github.com/nextcloud/calendar/assets/1479486/e4757ff5-6552-42f6-b51b-2d621d6d2211) |
> [stable4.7] fix: calendar picker width in disabled state

- src/components/Editor/CalendarPickerHeader.vue
Breaks the picker when it's not disabled :see_no_evil: I was able to reproduce the initial problem on main as well and will open a proper fix + backport.
> Revert "[stable4.7] fix: calendar picker width in disabled state"

- src/components/Editor/CalendarPickerHeader.vue
Follow-up to https://github.com/nextcloud/calendar/pull/6032
**Before:**
| Short name | Long name |
| --- | --- |
| ![grafik](https://github.com/nextcloud/calendar/assets/1479486/b336dbe0-290d-43ec-b5c5-c4f1d1648ee1) | ![grafik](https://github.com/nextcloud/calendar/assets/1479486/6ef05f05-145e-418e-87c2-319a4f8857dd) |
| Short name | Long name |
| --- | --- |
| ![grafik](https://github.com/nextcloud/calendar/assets/1479486/54513276-f3a2-4eaf-a008-66cd4c1155d3) | ![grafik](https://github.com/nextcloud/calendar/assets/1479486/80de28ce-8829-480a-afe8-ff4f6ead6207) |
| Short name | Long name |
| --- | --- |
| ![grafik](https://github.com/nextcloud/calendar/assets/1479486/49500302-2e98-48a7-a133-77d1ef9b4ae7) | ![grafik](https://github.com/nextcloud/calendar/assets/1479486/d445ca9c-16e9-4185-9 …
> fix(editor): calendar picker width

- src/components/AppNavigation/Settings.vue
To improve the situation in https://github.com/nextcloud/server/issues/45503
Omit calendars that don't support VEVENTs from the default calendar picker.
> fix: default calendar needs to support VEVENTs

- composer.lock
background: https://github.com/nextcloud/calendar/pull/5607 is incomplete. composer.json was changed without composer.lock, so the two files got out of sync
> fix: composer out of sync files

- composer.lock
Manual backport of https://github.com/nextcloud/calendar/pull/6058
background: https://github.com/nextcloud/calendar/pull/5607 is incomplete. composer.json was changed without composer.lock, so the two files got out of sync
> [stable4.7] fix: composer out of sync files

- css/app-sidebar.scss
1. Install Talk.
2. Open a chat room and open the right sidebar.
3. Observe the header of the right sidebar.
> fix: scope global sidebar styles to the app

- css/app-sidebar.scss
Regression from https://github.com/nextcloud/calendar/pull/6081
The rule specificity changed so some styles were no longer overwritten by nc-vue.
> fix: sidebar editor tab scrolling

- src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
There were some breaking changes in the dialogs library we missed.
**Before:** Default attachment folder picker doesn't open.
**After:** It opens as usual.
Does not need to be backported as the dependency bump was not backported.
> fix: attachment folder picker

- css/fullcalendar.scss
> feat: reduce opacity for past events

- lib/Controller/ViewController.php
- lib/Listener/CalendarReferenceListener.php
- lib/Service/CalendarInitialStateService.php
- tests/php/unit/Service/CalendarInitialStateServiceTest.php
Fix https://github.com/nextcloud/assistant/issues/92#issuecomment-2202580698 
Fix #6076
> Fix: move state init to a service

- lib/Service/CalendarInitialStateService.php
> fix: check if userId is null

- src/fullcalendar/localization/localeProvider.js
- src/utils/localization.js
- src/utils/moment.js
Ref https://github.com/nextcloud/calendar/issues/384 (does not solve the issue but helps with it)
Initialize moment, FullCalender and our date picker using the global first day of week setting from server. It is currently derived from a user's locale and provided by `@nextcloud/l10n`.
This should make Calendar more consistent with the locale preview in the personal user settings (below the locale select).
https://github.com/nextcloud-libraries/nextcloud-l10n/blob/b65c8b6d9ff9c3178aeae466ccdc7a8e1406cf32/lib/date.ts#L5-L17
> fix: use first day of week setting from server

- src/components/AppNavigation/EditCalendarModal/PublishCalendar.vue
> fix: update calendar sharing icon

- .github/workflows/npm-test.yml
- .github/workflows/php-test.yml
Otherwise, PRs from (community) forks will never have green CI. In my opinion we can tolerate having no coverage info from the occasional community contributor as long as the tests are successful.
> ci: allow coverage upload to fail

- src/components/AppNavigation/CalendarList.vue
- src/components/AppNavigation/CalendarList/CalendarListItem.vue
- src/components/AppNavigation/CalendarList/CalendarListNew.vue
- src/views/Calendar.vue
Close https://github.com/nextcloud/calendar/issues/5083
| A | B |
| - | - |
| ![image](https://github.com/nextcloud/calendar/assets/76647797/820083eb-2557-447e-9ea7-e0426529307b) | ![image](https://github.com/nextcloud/calendar/assets/76647797/32f58f57-bbd6-47d7-a0d1-c98c4c47ed12) |
> Improve sidebar organization

- lib/Service/Appointments/MailService.php
- tests/php/unit/Service/Appointments/MailServiceTest.php
Fixes https://github.com/nextcloud/calendar/issues/6156
> fix(appointments): Set organiser email to correct langauge

- lib/Service/Appointments/BookingCalendarWriter.php
Fixes https://github.com/nextcloud/calendar/issues/6156
> fix(appointments): properly localise the calendar events

- src/components/AppNavigation/EditCalendarModal.vue
Fix https://github.com/nextcloud/calendar/issues/6136
| A | B |
| - | - |
|![image](https://github.com/user-attachments/assets/5370f4ed-2d24-4741-a555-6fca34be4f6f) | ![Screenshot from 2024-07-15 17-22-26](https://github.com/user-attachments/assets/d53ee300-4d8b-478b-a72e-1d5fdb79006c) |
> EditCalendarModal: add spacing

- css/global.scss
- src/views/EditSimple.vue
Fix https://github.com/nextcloud/calendar/issues/6137
| A | B |
| - | - |
| ![Screenshot from 2024-07-15 17-44-12](https://github.com/user-attachments/assets/343b7e41-3b88-466b-929a-927aaf2182be) | ![Screenshot from 2024-07-15 17-43-45](https://github.com/user-attachments/assets/292cbea7-2bb2-4093-bfe6-e5f4bd2916ec) |
> EditSimple: add spacing

- src/components/Editor/AvatarParticipationStatus.vue
Fix https://github.com/nextcloud/calendar/issues/6150
| A | B |
| - | - |
| ![Screenshot from 2024-07-15 15-11-57](https://github.com/user-attachments/assets/eaf45d73-78ed-4d59-a194-32bdcc71cf0b) | ![Screenshot from 2024-07-15 15-11-37](https://github.com/user-attachments/assets/a928d0c5-75b9-40dd-a465-e096964ce451) |
And to prove that it's aligned :)
> Align invitee list item status information with the status icon

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
| A | B |
| - | - |
| ![Screenshot from 2024-07-16 14-37-59](https://github.com/user-attachments/assets/98683a4c-aa81-4ac3-b91b-b1c02314a923) | ![Screenshot from 2024-07-16 14-37-24](https://github.com/user-attachments/assets/b29a5296-ad51-4a7a-b078-e58783e1440d) |
(Also adds hover text)
> Make the new calendar caption more coherent with the appointments caption

- src/components/Editor/Invitees/InviteesList.vue
| b | a |
| <img width="470" alt="image" src="https://github.com/user-attachments/assets/3cde8802-56ad-473b-890f-6ec73efa385e"> | <img width="470" alt="image" src="https://github.com/user-attachments/assets/c7f6660b-854f-40d6-ae2d-21054d0fb036"> |
> fix: make sidebar tabs spacing consistent

- css/fullcalendar.scss
Fixes https://github.com/nextcloud/calendar/issues/6139
| --- | --- |
| ![image](https://github.com/nextcloud/calendar/assets/1374172/fc50cd76-df3c-420f-8f22-78041da19548) | ![grafik](https://github.com/user-attachments/assets/6c3a5f99-4053-4efb-bff6-021c6f2fc460) |
> fix(fc): tiny white border on highlighted cells

- .github/workflows/php-test.yml
- composer.lock
- vendor-bin/cs-fixer/composer.json
- vendor-bin/cs-fixer/composer.lock
- vendor-bin/phpunit/composer.json
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
Needs a follow up for the test matrix as we shouldn't test against stable27 / 28 / 29 any more.
> feat: update php and nextcloud versions

- css/app-navigation.scss
Fix https://github.com/nextcloud/server/issues/44638
Once again, our global app navigation styles leak to other apps. Scoping them should be a safe operation as the navigation sidebar on the left is not shown outside of the app.
Best reviewed as: https://github.com/nextcloud/calendar/pull/6186/files?w=1
| --- | --- |
| ![image](https://github.com/nextcloud/server/assets/925062/606b9aef-b986-4e61-9f01-53bbb2988f5c) | ![Screenshot_20240722_153705](https://github.com/user-attachments/assets/3eb70dfb-3d9f-492e-b62b-13e42ddbe9b6) |
There are no visual regressions due to changed style precedence.
| --- | --- |
| ![Screenshot_20240722_153627](https://github.com/user-attachments/assets/ed95248f-21b8-4f1e-85c4-210f499526b9) | …
> fix(navigation): scope all styles to the calendar app

- src/components/AppNavigation/EditCalendarModal.vue
- src/models/calendar.js
- src/store/calendars.js
- tests/javascript/unit/models/calendar.test.js
Fixes https://github.com/nextcloud/calendar/issues/3193
~Needs https://github.com/nextcloud/cdav-library/pull/908~
~Needs https://github.com/nextcloud/cdav-library/pull/909~
How to test:
- Uncheck the checkbox in the Edit Calendar Modal
- Check oc_calendars row for the calendar - the value for the transparency should change to 1 for transparent when the checkbox is unchecked.
> feat: allow calendar-wide transparency settings

- src/components/AppNavigation/EditCalendarModal.vue
Resolves https://github.com/nextcloud/calendar/issues/6154
| --- | --- |
| ![grafik](https://github.com/user-attachments/assets/c7aa1804-bb20-46eb-abe2-3e49a9505382) | ![grafik](https://github.com/user-attachments/assets/2a075f25-0568-466d-8023-26beada40a5c) |
> feat: reduce header sizes in calendar modal

- src/components/Editor/FreeBusy/RoomAvailabilityList.vue
- src/components/Editor/FreeBusy/RoomAvailabilityModal.vue
- src/components/Editor/Resources/ResourceListSearch.vue
- src/models/attendee.js
- src/services/caldavService.js
- src/services/freeBusySlotService.js
- src/store/principals.js
- src/views/Calendar.vue
- tests/javascript/unit/models/attendee.test.js
Fix https://github.com/nextcloud/calendar/issues/3185
~Requires https://github.com/nextcloud/cdav-library/pull/890~
1. Install https://github.com/nextcloud/calendar_resource_management
2. Run the following script to add some rooms:
```
occ calendar-resource:building:create 'Arkham Asylum' \
--address 'Amadeus Way, Gotham NG11 0AS' \
--description 'Elizabeth Arkham Asylum for the Criminally Insane' \
--wheelchair-accessible false
occ calendar-resource:story:create 1 '1st floor'
occ calendar-resource:story:create 1 '2nd floor'
occ calendar-resource:room:create 1 arkham_meeting_1 'The Joker' joker@arkham-asylum.com 'meeting-room' \
--contact-person-user-id amadeus \
--capacity 10 \
--room-number 404 \
--has-phone '+1 555 777 123' \
--has-video-conferencing true \
--has-tv false \ …
```
> feat: implement resources and rooms overview

- src/components/AppNavigation/Settings.vue
Fix https://github.com/nextcloud/calendar/issues/6138
| A | B |
| - | - |
| ![Screenshot from 2024-07-24 10-47-42](https://github.com/user-attachments/assets/b14d9d1b-57f8-4db3-84b4-1bfa091e0773) | ![Screenshot from 2024-07-24 10-46-42](https://github.com/user-attachments/assets/7d82e1c5-10ec-4bb5-beb2-e23d3e5f4ad4) |
> Settings: set proper width for all NcSelects to be the same width

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Issue labels don't work any more since they use the old `0 - to triage` and `1 -  to develop`
> chore(workflows): fix issue labels

- src/components/Editor/Invitees/InviteesListSearch.vue
In case if multiple attendees have empty email, the second one won't show in search result by 
block of alreadyInvitedEmails. Add email is not empty check in findAttendeesFromContactsAPI
> Fix: when a attendee is a second person without email, skip alreadyInvitedEmails check

- css/fullcalendar.scss
Fixes https://github.com/nextcloud/calendar/issues/6183
| ![Bildschirmfoto vom 2024-08-06 13-34-18](https://github.com/user-attachments/assets/8329868e-8aa8-400e-89a8-e0d79aa5f24d) | ![Bildschirmfoto vom 2024-08-06 13-35-21](https://github.com/user-attachments/assets/75b0a5f3-d143-4f2e-bbde-b7f062ee5dd7) |
> fix(fc): Adjust *today* border radius

- README.md
Now points to documentation repo, not screenshot repo which is no longer maintained
> chore: update screenshot link

- src/components/AppNavigation/CalendarList.vue
Fixes https://github.com/nextcloud/calendar/issues/6259
| b | a |
| ![image](https://github.com/user-attachments/assets/84d2abd6-8019-4a9e-aa3b-2deb5703cd14) | ![image](https://github.com/user-attachments/assets/e8a7a677-269a-4976-aff4-5f487a078ab1) |
> Fix: list hidden shared calendars correctly

- src/components/Editor/Invitees/InviteesListSearch.vue
Fix https://github.com/nextcloud/calendar/issues/6227
| After | Before |
| - | - |
| ![image](https://github.com/user-attachments/assets/bd48460c-8fe4-4509-8d86-e5ed55ca4738) | ![image](https://github.com/user-attachments/assets/5db2444e-49a5-4786-92d3-61942015cd53) |
The culprit was NcSelect styling (as per usual)
> InviteesListSearch: make avatar status not clip

- css/fullcalendar.scss
Fix https://github.com/nextcloud/calendar/issues/6226
The solution is a bit hacky, but I can't think of anything better...
| - | - |
| ![image](https://github.com/user-attachments/assets/758c7edd-0796-4361-ab55-97a5da4870be) | ![image](https://github.com/user-attachments/assets/1b5beea0-9908-49e2-afcb-9c5f8db88846) |
> FullCalendar CSS: make events in weekly view have the correct width

- src/components/AppNavigation/Settings.vue
> fix: default reminder ui bug

- css/fullcalendar.scss
Fix #6281
| b | a |
| <img width="208" alt="image" src="https://github.com/user-attachments/assets/e82f5140-ddb4-4bdd-9d5c-2d2fe5a4d936"> | <img width="208" alt="image" src="https://github.com/user-attachments/assets/0c0ae377-ce13-4345-ac58-d19fa272fe68"> |
> fix: Events with overlapping time visually overlap

- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
- src/mixins/EditorMixin.js
- src/views/EditSidebar.vue
- src/views/EditSimple.vue
> feat: add organizer selection

- src/models/event.js
- src/store/calendarObjectInstance.js
Fix https://github.com/nextcloud/calendar/issues/5793
That `eventComponent` is black magic...
> CalendarObjectInstance: reset attendee participation status on duplication of an event

- src/services/attachmentService.js
- src/utils/propfindErrorParse.js
Fix https://github.com/nextcloud/calendar/issues/6245
Mostly copied from https://github.com/nextcloud/spreed/blob/main/src/utils/propfindErrorParse.ts
> fix(attachmentService, propfindErrorParse): add an error message for when a file is not compatible for windows

- css/app-navigation.scss
- css/public.scss
- src/components/AppNavigation/EmbedTopNavigation.vue
> fix(embed): calendar header overlapping and adjust to compact design

- src/utils/propfindErrorParse.js
Fix https://github.com/nextcloud/calendar/pull/6303/files#r1743478384
> fix(l10n): propfind error message translation source

- src/components/AppNavigation/CalendarList/CalendarListNew.vue
Resolves: https://github.com/nextcloud/calendar/issues/6341
> fix(CalendarListNew): Public Calendar Modal Opening

- src/components/Editor/FreeBusy/FreeBusy.vue
- src/services/freeBusySlotService.js
- tests/javascript/unit/services/freeBusySlotService.test.js
Fix https://github.com/nextcloud/calendar/issues/6162
Improve the slot suggestions and make the algorithm more understandable
> Fix some issues in free/busy suggestions

- css/fullcalendar.scss
| - | - |
| ![image](https://github.com/user-attachments/assets/95cd9cb3-4a3b-466d-92e5-aee05c53e792) | ![image](https://github.com/user-attachments/assets/fb865b20-cfc8-4d27-9770-14b1072aa864) |
> style(fullCalendar): make weekly events slightly shorter

- src/components/AppNavigation/AppointmentConfigList.vue
- src/components/AppointmentConfigModal.vue
- src/components/AppointmentConfigModal/Confirmation.vue
"Appointment" notion is no clear and creates confusion because this feature don't directly create an appointment but create an "appointment request form". I propose a new notion : "Appointment request form".
I made some wording change test with my browser dev tools. Please check below (real tests from reviewers are welcome) :
> "Appointment schedule" notion instead of only "Appointments" for a better UX

- src/components/Editor/Attachments/AttachmentsList.vue
Nextcloud 29 (stable4.7) and below are not affected.
> fix(attachments): add missing file picker confirm

- src/resources/holiday_calendars.json
From conversation in #6011:
Imported content from https://github.com/thunderbird/thunderbird-website/blob/master/media/caldata/autogen/calendars.json (version from Apr 1, 2024, 9:39 PM GMT+2) bringing the number of calendars from about 56 to about 86.
Adds 'locale', 'language', and 'updated' fields that are not used by Nextcloud at the moment but present in Thunderbird’s source file.
> Update holiday_calendars.json to be in sync with Thunderbird

- src/components/AppNavigation/CalendarList/Trashbin.vue
- src/components/AppNavigation/EditCalendarModal/ShareItem.vue
- src/components/AppNavigation/Settings/SettingsAttachmentsFolder.vue
- src/components/Editor/Attachments/AttachmentsList.vue
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
- src/components/Shared/CalendarPicker.vue
- src/components/Shared/DatePicker.vue
> chore: `npm run lint:fix`

- lib/Db/AppointmentConfig.php
- lib/Db/Booking.php
Psalm was failing on the entity parameter types.
> fix: Entity parameter types

- css/app-navigation.scss
- src/components/AppNavigation/AppNavigationHeader/AppNavigationHeaderDatePicker.vue
fix #6402
| b | a |
| <img width="303" alt="image" src="https://github.com/user-attachments/assets/d5781b4f-1bda-4c4e-bb05-dedcda5be9d5"> | https://github.com/user-attachments/assets/e334b714-4049-4367-8f87-aec766020365 |
> fix(rtl): navigation buttons

- .github/workflows/php-test.yml
- appinfo/info.xml
> chore: add PHP 8.4

- .github/CODEOWNERS
- appinfo/info.xml
To align with https://github.com/nextcloud/groupware/pull/86.
> docs: Update app maintainers

- src/components/AppointmentConfigModal.vue
- src/components/Shared/CalendarPicker.vue
> fix(calendarPicker): undefined calendar

- lib/Controller/ContactController.php
- tests/php/unit/Controller/ContactControllerTest.php
> fix(teams): resolve undefined variable error and add logging

- lib/Service/Appointments/TimezoneGenerator.php
- tests/php/unit/Service/Appointments/TimezoneGeneratorTest.php
Resolves: https://github.com/nextcloud/calendar/issues/6476
Testing: See issue ticket for details.
> fix: handle timezones with no transitions properly

- src/components/AppointmentConfigModal.vue
Resolves: https://github.com/nextcloud/calendar/issues/3786
Requires: https://github.com/nextcloud/server/pull/48621
Adjusted "Additional calendars to check for conflicts" selection logic to list all users calendars, personal and shared to be selectable for conflicts.
> feat: Allow shared calendars as appointment conflict calendars

- lib/Controller/BookingController.php
- tests/php/unit/Controller/BookingControllerTest.php
Resolves: #6407 
Resolves: #5913
> fix: appointment slots start and end time

- .github/workflows/appstore-build-publish.yml
- .github/workflows/appstore-conventional-build-publish.yml
- .github/workflows/conventional_commits.yml
* Add a fully automated workflow for releases. It does the same as a manual process, except for any milestone cleanups.
* Change the old workflow to only run manually to avoid a double release with the new workflow pushing over to the releases org
* Set up the repository release environment and add necessary keys
This workflow released Mail v4.0.2 yesterday.
> [stable5.0] ci: Add release automation

- .github/workflows/conventional_commits.yml
- README.md
stable5.0 is clean for https://github.com/nextcloud/calendar/pull/6507 but we should try to enforce the commit style in this repo too.
> ci: Enforce conventional commits

- .github/CODEOWNERS
- appinfo/info.xml
Backport of https://github.com/nextcloud/calendar/pull/
> [stable5.0] docs: Update app maintainers

- .github/workflows/appstore-conventional-build-publish.yml
^ looks suspicious, but it was me through the automation. By specifying our command bot as committer I hope to make it more transparent that releases are legit, but automated.
> [stable5.0] fix(release): Specify committer for automated releases

- README.md
Close #5119
Local version of https://github.com/nextcloud/calendar/pull/5119
Picked up Simon's suggestion to flip the order.
> chore: Add event attachments to README.md

- src/views/Appointments/Booking.vue
> enhanc: keep calendar always open

- .tx/backport
- REUSE.toml
Ref https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync
We use this for Contacts and Mail too and it seems to work well.
> ci: Enable translation backports

- .github/workflows/appstore-conventional-build-publish.yml
Same as https://github.com/nextcloud/mail/pull/10429
> fix(release): Fix wget output option

- src/components/Editor/Attachments/AttachmentsList.vue
- src/store/calendarObjectInstance.js
- src/views/EditSidebar.vue
**Summary:**
It’s possible to attach files to an event. An internal or public share link is stored within the event.
On the main branch, adding a folder currently doesn’t work (while selection is possible, the folder isn’t actually added). It’s unclear to me from the initial implementation https://github.com/nextcloud/calendar/pull/4251 whether folder support was intended or not.
Folders typically don’t have a content type returned, so I added a fallback to display the folder icon.
| B | A |
| ![Screenshot From 2024-11-29 15-57-02](https://github.com/user-attachments/assets/2b233bb3-cb32-4794-946e-28517d384f6c) | ![Screenshot From 2024-11-29 15-39-05](https://github.com/user-attachments/assets/16db6acf-6d88-47fe-8949-0a4068580f95) | 
> [!WARNING]
> Adding another …
> Event attachments: Enable directory selection

- src/fullcalendar/interaction/eventClick.js
- tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
The URL to tasks in the Task app changed with https://github.com/nextcloud/tasks/pull/2480 which was released with Tasks 0.16.0. This fix should be backported to the last version supporting Nextcloud 28 which is the oldest server version supported by Tasks 0.16.0.
Closes #6533.
> fix: adjust url for task links

- appinfo/routes.php
- lib/Controller/ContactController.php
- lib/Service/ContactsService.php
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/InviteesListSearch.vue
- src/store/calendarObjectInstance.js
- src/views/EditSidebar.vue
- tests/php/unit/Controller/ContactControllerTest.php
- tests/php/unit/Service/ContactsServiceTest.php
Fixes https://github.com/nextcloud/calendar/issues/167
To Do
> feat: allow inviting contact groups

- src/components/AppNavigation/Settings.vue
Found by @alexanderdd, currently the checkbox does the opposite of what it should
> Settings: invert edit simple checkbox

- src/components/AppNavigation/CalendarList.vue
Fix https://github.com/nextcloud/calendar/issues/6501
So the problem with this bug is that the way that dragging the calendars previously worked is conceptually incompatible with the division of calendars into different sections, mostly because of the hidden calendars. The hidden calendars being part of the order, but being in a different place from all the others, causes the order coming from `vue-draggable` to be wrong. Another issue discussed with Christoph is the drag to reorder feature is pretty hard to discover.
Here are a few things I thought about:
- Instead of having one big orderable section, have 3, one for personal, one for shared, and one for deck. This however still doesn't fix the issue of hidden calendars.
- One potential solution to the hidden calendars is making all …
> Fix calendar lists not being orderable any more

- lib/Controller/BookingController.php
- src/services/appointmentService.js
- src/views/Appointments/Booking.vue
- tests/php/unit/Controller/BookingControllerTest.php
Resolves: https://github.com/nextcloud/calendar/issues/6528
Testing Recommendation
1. Test with existing appointment schedule and fresh appointment schedule (make sure when creating a new appointment schedule the browser time zone matches the calendar time zone, as there is another bug that will affect this)
2. Test by selecting different time zones negative (North America/South America), positive (Australia/China/Etc) and matching the appointment schedule
3. Test by changing browser time zone (either override browser setting or change system time zone). You can check your browser time zone here: https://webbrowsertools.com/timezone/
4. Test by selecting time zones with an offset greater than the current time. (if the current time is 10.00 select zone that has offset of +11 hours, if the …
> fix: send date as string instead of epoch

- src/fullcalendar/interaction/eventClick.js
- tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
Manual backport of https://github.com/nextcloud/calendar/pull/6550
> [stable5.0] fix: adjust url for task links

- src/components/Editor/AvatarParticipationStatus.vue
> fix: avatar status icon text misalignment

- src/views/Appointments/Booking.vue
fixes  #6570
to avoid any breaking changes on other parts where ncselect is used, lets force it on calendar
> fix: max-width for long timezones names

- src/components/Editor/AvatarParticipationStatus.vue
the issue on FF only:
what is happening:
In Chromium the base position of the icon horizontally is "middle of the avatar" while in Firefox it is "on the left".
I have no idea, why it shown like that. Looks like it applies `justify-self: center`; from` material-design-icon`. But that shouldn't happen. Because it is not in a flex container. Chrome shows a warning that this property cannot be applied. But it is actually applied. Screenshot below.
Then the icon is moved using absolute position (left: 81px). And because the base position is different, it is different afterwards. 81px is a value used relative to chromium's invalid rendering.
The layout is  bad in general. ✅ icon and "Invitation accepted" string are children of a small avatar and then moved via position absolute/relative to a …
> fix: firefox avatar icon styling inconsistency

- src/components/Editor/AddTalkModal.vue
- src/services/talkService.js
- src/store/calendarObjectInstance.js
- src/views/EditSidebar.vue
fixes #6581
This PR adds the ability to link Talk rooms to calendar events. Users can create a new Talk room or select an existing one, and the link is added to the event's location or description(when the location field is already filled).
How to test:
1. Activate talk app
2. Create an event on calendar
3. Open the side bar by clicking more details
4. Find the Add Talk button
hover state and selected state
the side bar after selecting an existing convesation
> feat:select existing talk room for conversations on calendar events

- lib/AppInfo/Application.php
- package-lock.json
- package.json
- src/components/Editor/FreeBusy/FreeBusy.vue
- src/components/Editor/Invitees/InviteesList.vue
- src/contactsMenu.js
- src/views/ContactsMenuAvailability.vue
- tests/psalm-baseline.xml
- webpack.config.js
Part of https://github.com/nextcloud/server/issues/44776
Requires https://github.com/nextcloud/server/pull/49375 and https://github.com/nextcloud-libraries/nextcloud-vue/pull/6238
Add a new action to the contacts menu to show the user's availability. The plan is to reuse the free-busy modal for this.
https://github.com/user-attachments/assets/6d765163-05fe-42ce-b4a8-11ddf48f3a62
https://github.com/user-attachments/assets/eca4eb29-a5b2-4c6d-b9b5-1716099bdd5c
> feat: add availability action to the contacts menu

- src/views/EditSimple.vue
the editing state has now a overlay, similar to modal or dialog. It closes if you click the close button on the popover. The viewing state stays the same.
fixes #6582
before
after
> feat: Add overlay between calendar and open simple editor

- src/components/Editor/AvatarParticipationStatus.vue
- src/components/Editor/Invitees/InviteesList.vue
- src/components/Editor/Invitees/InviteesListItem.vue
- src/components/Editor/Invitees/OrganizerListItem.vue
- src/components/Editor/Resources/ResourceList.vue
- src/components/Editor/Resources/ResourceListItem.vue
Resolves https://github.com/nextcloud/calendar/issues/4983
I refactored the logic and moved it to a computed prop to facilitate making use of the schedule status as well.
I also implemented some custom status messages if the scheduling fails for some reason (statuses `3.x` and `5.x`).
| Invitees | Resources |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/588690b6-a578-4585-91a0-99a8110ee271) | ![spectacle_20241124_205940](https://github.com/user-attachments/assets/e5ddf31c-1be6-499f-92c0-27927772ab2c) |
(In the example above, the user `test` was just added and the event was not saved yet. The same applies to the resource `Croc`.)
> feat(editor): improve attendee and resource status display

- src/views/EditSidebar.vue
> fix: location and description not being saved

- css/app-sidebar.scss
> fix: color picker size

- src/views/EditSimple.vue
> fix: simple calendar view width

- src/main.js
fixes https://github.com/nextcloud/assistant/issues/16
[NcRichContenteditable](https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable) uses a `div` for text input so shortkeys defined via `vue-shortkey` do not get avoided unless they are explicitly excluded
> Fix: avoid hotkeys in contenteditable

- src/components/Editor/Properties/PropertyText.vue
- src/components/Editor/Properties/PropertyTitleTimePicker.vue
- src/views/EditSimple.vue
fixes #6630 
this pr fixes 2 issues, the popover jumping and the description being smaller when you start typing
https://github.com/user-attachments/assets/461f6631-24fc-4d61-9395-c9a95033662d
> fix: simple editor size and jumping

- src/components/Editor/AddTalkModal.vue
- src/services/talkService.js
- src/views/EditSidebar.vue
fixes #6641 
All _rooms_ should be names _conversation_
Close modal after creating convesation
Remove leftover method
> fix: close modal after creating conversation

- src/fullcalendar/localization/dateFormattingConfig.js
Fix https://github.com/nextcloud/calendar/issues/6463
Regardless of a user's locale setting.
| Locale | Screenshot | 
| --- | --- |
| en_US | ![image](https://github.com/user-attachments/assets/939bb043-c14c-4013-920b-8c2fb3e33074) | 
| de | ![image](https://github.com/user-attachments/assets/29254562-39c2-4176-aec2-b6e3dabbd43e) |
> fix(freebusy): slot header format not respecting user's locale

- src/components/Editor/FreeBusy/FreeBusy.vue
Addresses the following console error message:
```
[ERROR] calendar: FreeBusyEventSource: Timezone undefined not found, falling back to UTC.
```
> fix(freebusy): free busy ignoring user's time zone

- .github/workflows/package.yml
PHP 8.0 and 15 are EOL and not supported anymore in our ecosystem. Let's automate the version retrieval from `info.xml` and `package.json` similar to other workflows.
> ci(package): automate detection of node, npm and php versions

- src/components/Editor/AddTalkModal.vue
Fix https://github.com/nextcloud/calendar/issues/6676
| --- | --- |
| ![spectacle_20250128_143821](https://github.com/user-attachments/assets/7920ccbc-45a2-4a0c-b157-6b29f87805ff) | ![spectacle_20250128_143958](https://github.com/user-attachments/assets/12871cd9-c57e-4c2f-bd08-b39ac7645e85) |
> fix: sort talk conversations by most recent activity

- src/mixins/EditorMixin.js
- src/store/calendarObjectInstance.js
Fix https://github.com/nextcloud/calendar/issues/6660
I think this comes from an unfound bug in the Pinia migration
> fix: free busy not updating date

- src/components/Editor/FreeBusy/FreeBusy.vue
> [stable5.0] fix(freebusy): free busy ignoring user's time zone

- src/components/Editor/FreeBusy/FreeBusy.vue
> [stable4.7] fix(freebusy): free busy ignoring user's time zone

- src/components/AppNavigation/CalendarList/PublicCalendarListItem.vue
Follow-up to https://github.com/nextcloud/calendar/pull/6681
Remove some dead code from the public calendar list item component. It is not possible to toggle them and the method is not used anymore.
> refactor: clean up public calendar list item

- css/app-sidebar.scss
- src/views/EditSidebar.vue
> fix: force height for descr and location

- css/fullcalendar.scss
- src/fullcalendar/eventSources/eventSourceFunction.js
- src/fullcalendar/rendering/eventDidMount.js
- tests/javascript/unit/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.test.js
Fix https://github.com/nextcloud/calendar/issues/3869
Based on https://github.com/nextcloud/calendar/issues/3869#issuecomment-1026921383
> Visually distinguish invitations in calendar grid

- .github/workflows/package.yml
Older versions fail instantly as they were deprecated a long time ago.
> [stable4.7] ci(package): bump upload-artifact action to v4

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
(Generated from all `feat` and `fix` commits since `v5.0.10`.)
- Support for Nextcloud 31
- Support for PHP 8.4
- Add availability action to the contacts menu
- Add organizer selection
- Add overlay between calendar and open simple editor
- Add timezone to all emails
- Allow adding attendees in simple editor
- Allow inviting contact groups
- Allow shared calendars as appointment conflict calendars
- Disable autocompletion for event property field
- Fix dragging to order calendars
- Improve attendee and resource status display
- Improve the description text
- Select existing talk roomfor convesations
- Use native date and time picker
- Add an error message for when a file is not compatible for windows
- Add missing file picker confirm
- Adjust event click test to changed task url
- Adjust …
> chore(release): v5.1.0

- src/components/Editor/Alarm/AlarmTimeUnitSelect.vue
Fix https://github.com/nextcloud/calendar/issues/3441
This is a simple fix for the collision of translations for `second`. Please refer to https://github.com/nextcloud/calendar/issues/3441#issuecomment-984052425 for more information.
IMO, the impact is minimal and acceptable. Users will only notice it if they create an alarm with a relative time of 1 hour, minute, second, etc.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/f9abff7a-7073-4bd6-b83e-6de0f666432d) | ![image](https://github.com/user-attachments/assets/da13af78-93f4-498d-9ae7-4949d0c9b0ca) |
> fix: always show alarm unit in pural

- src/components/Editor/Repeat/RepeatFirstLastSelect.vue
- src/filters/recurrenceRuleFormat.js
Ref https://github.com/nextcloud/calendar/issues/3441#issuecomment-2672825421
Add context for translators to disambiguate second and seconds.
> fix(l10n): add context for translators (second vs. seconds)

- src/services/talkService.js
For https://github.com/nextcloud/spreed/issues/14401 we need an object type for the calendar- created Talk rooms.
This PR adds the object type "event" and passes is as an `objectType` when creating a talk room. Since there is only one room type created directly from the calendar, it should be ok to have this as a static value (same as the room type always being `3`).
@st3iny is there any chance to also pass the UUID for the `objectId`? I'm guessing it doesn't exists yet at this point in the process?
> feat(talkintegration): add object type to talk room creation

- CHANGELOG.md
- CHANGELOG.md.license
Fix https://github.com/nextcloud/calendar/actions/runs/13660296339/job/38189668415?pr=6782 (on stable branches)
I split it into two commits because only the standalone license file needs to be backported.
> Move changelog license header to a separate file

- .github/workflows/npm-audit-fix.yml
- .tx/backport
The old branch `stable5.1` can be removed once the final release is out. It will be be fully superseded by `stable5.2`.
> chore: add stable5.2 to the npm audit fix action and transifex integration

- src/components/Editor/Invitees/InviteesListItem.vue
Resolves: Issue with attendee action showing in popover viewing mode. The action also had no affect since the modal was only in viewing mode.
Before:
After:
> fix: do not show attendee actions in viewing mode

- src/views/EditSimple.vue
Resolves: Issue with attendee list showing blank place holder when there are no attendees. We do not show blank place holders for location or description, attendees list should function the same way, less in more.
Before:
After - Viewing Mode - No attendees
After - Editing Mode - No attendees
After - Viewing Mode - With attendees
After - Editing Mode - With attendees
> fix: do not show attendee list when there are no attendees in viewing mode

- src/components/Editor/Invitees/InviteesListSearch.vue
The app can invite *Contact groups* but not *Nextcloud groups*
Raised at https://github.com/nextcloud/calendar/issues/2955#issuecomment-2720732187.
> fix(editor): Rephraze ambiguous "group" invites

- src/components/Editor/AvatarParticipationStatus.vue
The participation status `Invited you` doesn't make sense when I'm viewing an event in a shared calendar to which I'm not directly invited.
The following screenshots show an event created by user1 in a shared calendar to which user3 has read-only access. User1 invited user2 to the event. It is viewed from the perspective of the unrelated user3.
| --- | --- |
| ![spectacle_20250318_104147](https://github.com/user-attachments/assets/6840616e-2323-47f5-b0af-b3abf15ce9c6) | ![image](https://github.com/user-attachments/assets/95be5025-d784-4ae4-bfa6-120583e283ba) |
> fix: show generic participation status for the organizer

- .github/workflows/lint-php-cs.yml
Fix php-cs sometimes failing due to PHP 8.4 being installed/used. The changes are copied from our workflow template repository.
Example at https://github.com/nextcloud/calendar/actions/runs/13922573639/job/38959076617?pr=6833
> fix(lint-php-cs): use minimum available php version

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- Conditional styling for participation status
- Object type for Talk rooms
- Always show alarm unit in pural
- Close modal after creating conversation
- Date selector resetting time
- Do not show attendee actions in viewing mode
- Do not show attendee list when there are no attendees in viewing mode
- Do not show items from deleted calendars in widget
- EditSideBar bug
- Force height for descr and location
- Free busy ignoring user's time zone
- Free busy not updating date
- Keyboard shortcut modal not being responsive
- Monthly recurrance type and bymonthday selection
- Remove toggle functionality from public view
- Rephraze ambiguous "group" invites
- Restrict attendees edit priveleges in the frontend
- Restrict calendar visibility toggle to checkbox only
- Show display name instead of …
> chore(release): v5.2.0

- src/components/Editor/AddTalkModal.vue
As discussed in https://github.com/nextcloud/spreed/issues/14689
| ![Screenshot from 2025-03-20 16-33-40](https://github.com/user-attachments/assets/6158bdb5-fbae-463b-bbbc-1c34577fd0ce) | ![Screenshot from 2025-03-20 16-34-07](https://github.com/user-attachments/assets/fbc44b53-c9b7-48ba-8051-46a54c919446) |
Test event is a room created by Calendar via the Talk integration.
> feat(talkintegration): filter out event type rooms from suggestions

- src/fullcalendar/rendering/eventDidMount.js
| - | - |
| ![image](https://github.com/user-attachments/assets/30c2e430-c695-4fe5-8868-affc4fe0739d) | ![image](https://github.com/user-attachments/assets/5e47b5cc-ebfb-4302-82f5-2a7ae5ce1b64) |
> Make time text color in calendar grid be main text color

- src/components/Editor/Properties/PropertyTitleTimePicker.vue
| Small screen | Normal screen |
| --- | --- |
| ![spectacle_20250224_191734](https://github.com/user-attachments/assets/e6645ec0-6912-4d82-b799-fe13b5968ade) | ![spectacle_20250224_191715](https://github.com/user-attachments/assets/c1c3c7c7-50ed-472b-ae16-d02cdfac1e4d) |
> fix(editor): wrap date selects on small screens

- package-lock.json
This audit fix resolves 14 of the total 24 vulnerabilities found in your project.
* [@babel/helpers](#user-content-\@babel\/helpers)
* [@babel/runtime](#user-content-\@babel\/runtime)
* [@nextcloud/l10n](#user-content-\@nextcloud\/l10n)
* [@nextcloud/moment](#user-content-\@nextcloud\/moment)
* [axios](#user-content-axios)
* [node-gettext](#user-content-node-gettext)
* [vue-loader](#user-content-vue-loader)
* …
> [stable5.2] Fix npm audit

- psalm.xml
- vendor-bin/psalm/composer.json
- vendor-bin/psalm/composer.lock
Unfortunately, upstream has set *very* strict PHP version requirements that fail to comply with our platform config despite being on the same minor version (`8.1` vs `~8.1.17`). So renovate fails to do the bump by itself.
Ref https://github.com/nextcloud/calendar/pull/6680#issuecomment-2620258454
Supersedes https://github.com/nextcloud/calendar/pull/6680
> chore(deps-dev): bump vimeo/psalm from 5.26.1 to v6

- src/views/EditSidebar.vue
Regression from https://github.com/nextcloud/calendar/pull/6809 and https://github.com/nextcloud/calendar/pull/6882
The "Add Talk conversation" button should be shown if there are no attendees yet. It should only be hidden if the given user is an attendee and can't edit the event.
> fix(editor): show add talk button if there are no attendees yet

- package-lock.json
- package.json
Fixes a regression in the avatar component.
> [stable5.2] fix(deps): bump @nextcloud/vue to ^8.25.1

- src/components/AppNavigation/CalendarList/Trashbin.vue
This seems to be a copy/paste error.
1. Delete an event.
2. Open the trash bin and permanently delete it.
3. Observe the invalid toast message.
**Before:** Could not restore calendar or event
**After:** Could not delete calendar or event
> fix: trashbin error toast wording when deleting items

- src/views/Appointments/Booking.vue
Closes https://github.com/nextcloud/calendar/pull/6948 (alternative to)
Resolves https://github.com/nextcloud/calendar/issues/6771
1. Create an appointment config.
2. Click on "Preview".
3. Switch to a mobile layout.
4. Observe that the layout is broken and unusable.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/ac126259-8cf7-40ed-aba1-aaa507ccccdf) | ![image](https://github.com/user-attachments/assets/1857d093-a772-4115-94fd-177eb13a4e42) |
> fix(appointments): mobile booking view not being responsive

- src/mixins/EditorMixin.js
Regression after https://github.com/nextcloud/calendar/pull/6888
To test: have an event with different start and end times, change start time, end time should also change to be the same interval as before
> Fix timepicker not adjusting end date

- src/services/talkService.js
Fix adding of attendees into Talk event rooms by displayed name (`commonName`) instead of email
GET request `/core/autocomplete` does not handle emails, but user ids and display name, so could be a better substitution
Also search result contains email in 'shareWithDisplayNameUnique' field, so can be compared with event attendee to match before saving
In worst case search result will be ignored and function falls back to email attendee (as in Before)
Before | After
-- | --
> fix: adjust populating of Talk room

- src/views/Appointments/Booking.vue
Fix https://github.com/nextcloud/calendar/issues/6521
| - | - |
| ![image](https://github.com/user-attachments/assets/93476693-f797-42f8-873e-9e23611fcdc4) | ![image](https://github.com/user-attachments/assets/a2166a93-bc4b-4f65-b0fe-883afa0a86b9) |
| ![image](https://github.com/user-attachments/assets/5e79fa29-7aa0-4e5e-bff1-69c2a1fddca3) | ![image](https://github.com/user-attachments/assets/987cf1aa-fb95-4a60-b2b4-499b31adaafe) |
> Booking: change color of disabled days in datepicker

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
- send date as sting instead of epoch from appointment selector
> chore: Release 4.7.18

- src/components/CalendarGrid.vue
~Fixes creating events on touch devices. Try to tap or tap-and-drag on the grid to create an event.~
Reduces the duration for long presses on touch devices when creating new events from 1 to 0.5 seconds.
Can be reproduced on phones or on desktop browsers using the developer tools.
Ref https://fullcalendar.io/docs/longPressDelay
> fix: reduce long press event delay to 500 ms

- .github/workflows/appstore-conventional-build-publish.yml
Copied from the Mail app.
This version of the workflow creates a release on the nextcloud-releases repository and lets the regular release workflow take over there. This is less error prone and there were some problems when both release workflows were triggered at the same time by accident in the past.
> ci: modernize conventional release workflow

- tests/php/unit/bootstrap.php
Ref https://github.com/nextcloud/server/pull/52951
> chore(tests): cleanup bootstrap.php to be forward-compatible

- lib/Dashboard/CalendarWidget.php
- tests/php/unit/Dashbaord/CalendarWidgetTest.php
Resolves: #6767
Requires: https://github.com/nextcloud/server/pull/51081
> fix: do not show hidden calendars

- package-lock.json
This audit fix resolves 9 of the total 19 vulnerabilities found in your project.
* [brace-expansion](#user-content-brace-expansion)
* [vue-loader](#user-content-vue-loader)
* [vue-template-compiler](#user-content-vue-template-compiler)
* Caused by vulnerable dependency:
* Affected versions: 4.2.0-beta.1 - 6.3.1
* Package usage:
* …
> [stable5.3] Fix npm audit

- src/components/Editor/Resources/ResourceList.vue
Removes a console warning like `[Vue warn]: Error in render: "TypeError: can't access property "uri", this.calendarObjectInstance.organizer is null"` whenever the last attendee is removed from an event.
> fix: handle missing organizer gracefully when fetching room suggestions

- css/app-full.scss
- src/components/Editor/AvatarParticipationStatus.vue
| Before | After | 
| - | - | 
| <img width="518" height="379" alt="image" src="https://github.com/user-attachments/assets/77872456-2e32-42eb-b462-e6ea2f334336" /> | <img width="508" height="370" alt="image" src="https://github.com/user-attachments/assets/b7f08772-687b-49de-ae67-d0b6e526a425" /> |
| <img width="623" height="221" alt="image" src="https://github.com/user-attachments/assets/80f68cb7-f872-4a98-8715-72286d0fed83" /> | <img width="623" height="215" alt="image" src="https://github.com/user-attachments/assets/c411cd0c-ae30-405c-82d2-61c78f3d87cd" /> |
I had to change the position style for the full page modal view, seeing as in that case there are two different cases, one in which the columns have their full width (`500px` max width), or in responsive mode when they become …
> Make attendee participation status not ellipse early

- src/components/AppNavigation/Settings.vue
**Before:** `Enable simplified editor` checkbox not remembering the state between page reloads
**After:** The checkbox reflects the current state accurately.
I also went ahead and migrated all other checkboxes from `:checked` to `:model-value` for compatibility to ensure forward compatibility with Vue 3.
> fix(settings): forward compatibility of all checkboxes

- src/components/Editor/FreeBusy/FreeBusy.vue
- src/fullcalendar/eventSources/freeBusyResourceEventSourceFunction.js
| b | a |
|<img width="1373" height="886" alt="image" src="https://github.com/user-attachments/assets/66fad863-dbe1-4edb-8a20-8f7b2dd154fa" /> |<img width="1373" height="886" alt="image" src="https://github.com/user-attachments/assets/3e2f937c-d591-4a28-8092-0bf3d0c22f45" /> |
> fix(free-busy): use own calendar color for organiser busy blocks

- src/components/Editor/FreeBusy/FreeBusy.vue
> fix: fix compiler SCSS warning

- __mocks__/@nextcloud/calendar-availability-vue/index.js
- src/fullcalendar/interaction/eventClick.js
- src/models/appointmentConfig.js
- src/services/talkService.js
- tests/javascript/unit/fullcalendar/interaction/eventClick.test.js
- tests/javascript/unit/models/appointmentConfig.test.js
- tests/javascript/unit/services/talkService.test.js
Leverage getBaseUrl() of `@nextcloud/router`.
Problems: Instances with a custom port, for example, HTTPS on 8443.
> fix: make absolute URL generation more robust

- css/app-full.scss
Follow-up to #7185
1. Open Talk
2. Create a public conversation
3. Open the conversation in a private tab on a phone or responsive mode on desktop with a screen narrower than 785px
main: no *X* icon at the top right
here: *X* icon at top right
Calendar editor stays identical before/after
> fix(ui): scope mobile css rules for full editor

- package-lock.json
This audit fix resolves 17 of the total 19 vulnerabilities found in your project.
* [@linusborg/vue-simple-portal](#user-content-\@linusborg\/vue-simple-portal)
* [@nextcloud/calendar-availability-vue](#user-content-\@nextcloud\/calendar-availability-vue)
* [@nextcloud/vue-select](#user-content-\@nextcloud\/vue-select)
* [floating-vue](#user-content-floating-vue)
* [linkifyjs](#user-content-linkifyjs)
* …
> [stable5.4] Fix npm audit

- lib/Service/Appointments/BookingCalendarWriter.php
Ref https://github.com/nextcloud/server/pull/54160
Needs to be backported to `stable5.4` depending on whether https://github.com/nextcloud/calendar/pull/7229 is merged.
> fix: use createFromStringMinimal() instead of createFromString()

- CHANGELOG.md
- appinfo/info.xml
- package-lock.json
- package.json
This reverts commit 72e3a3d8790a5aef2e1373f2ade2dbd632834cb8.
A new branch `stable5.5` was created for the new minor version.
> Revert "chore(release): v5.5.0"

- src/components/Editor/FreeBusy/FreeBusy.vue
> fix(free-busy): make backgound solid for attendees' slots

- package-lock.json
This audit fix resolves 16 of the total 18 vulnerabilities found in your project.
* [@linusborg/vue-simple-portal](#user-content-\@linusborg\/vue-simple-portal)
* [@nextcloud/calendar-availability-vue](#user-content-\@nextcloud\/calendar-availability-vue)
* [@nextcloud/vue-select](#user-content-\@nextcloud\/vue-select)
* [floating-vue](#user-content-floating-vue)
* …
> [stable5.5] Fix npm audit

- lib/Service/Proposal/ProposalService.php
ErrorException: Warning: Undefined variable $mailService
#0 /calendar/lib/Service/Proposal/ProposalService.php(515): OCA\Calendar\Service\Proposal\ProposalService::sendEmailNotifications
#1 /calendar/lib/Service/Proposal/ProposalService.php(426): OCA\Calendar\Service\Proposal\ProposalService::generateNotifications
#2 /calendar/lib/Service/Proposal/ProposalService.php(258): OCA\Calendar\Service\Proposal\ProposalService::modifyProposal
#3 /calendar/lib/Controller/ProposalController.php(148): OCA\Calendar\Controller\ProposalController::modify
> fix: Warning: Undefined variable $mailService

- .github/workflows/php-test.yml
- composer.json
We use `test:unit` and `test:unit:dev` everywhere else.
> chore(composer): rename test script to test:unit

- src/contactsMenu.js
| | Before | After |
| --- | --- | --- |
| js/calendar-contacts-menu.js | 3.5M | 333K |
| total | 24M | 21M |
> perf: reduce contacts menu entrypoint bundle size

- tests/php/unit/Controller/EmailControllerTest.php
- tests/php/unit/Controller/PublicViewControllerTest.php
- tests/php/unit/Service/CalendarInitialStateServiceTest.php
The method `withConsecutive()` is deprecated and was removed from more recent versions of PHPUnit.
> test: migrate withConsecutive() to willReturnMap()

- package-lock.json
This audit fix resolves 14 of the total 16 vulnerabilities found in your project.
* [@linusborg/vue-simple-portal](#user-content-\@linusborg\/vue-simple-portal)
* [@nextcloud/calendar-availability-vue](#user-content-\@nextcloud\/calendar-availability-vue)
* [@nextcloud/vue-select](#user-content-\@nextcloud\/vue-select)
* [axios](#user-content-axios)
* [floating-vue](#user-content-floating-vue)
* [vue-template-compiler](#user-content-vue-template-compiler)
* …
> [stable6.0] Fix npm audit

- src/main.js
Errors handled by Vue were not forwarded to Sentry by default.
> chore: redirect vue errors to sentry

- lib/Service/Proposal/ProposalService.php
Adds functionality to automatically created tentative time blocking events in calendars when a proposal is created.
https://github.com/nextcloud/server/pull/53831
> feat: Meeting proposals calendar time blockers

- src/components/CalendarGrid.vue
- src/fullcalendar/rendering/eventOrder.js
- tests/javascript/unit/fullcalendar/rendering/eventOrder.test.js
> fix: order all-day events by name

- .github/workflows/e2e-test.yml
CI might fail if it tries to install old/outdated packages.
> ci(e2e-test): run apt-get update before installing stunnel

- src/components/Editor/Properties/PropertyTitleTimePicker.vue
- src/components/Shared/DatePicker.vue
Fixes #7509 by only committing date/time changes when the user leaves the input field. This is similiar e.g. to the behavior of Thunderbird.
> Prevent event date change glitch

- appinfo/routes.php
- lib/Controller/BookingController.php
- src/services/appointmentService.js
- tests/php/unit/Controller/BookingControllerTest.php
Mixing two IDs makes reading logs more complex than necessary. Let's be consistent.
> fix(appointments): unify IDs
